const coniferdata = {
  pines: [
    {
      id: 1,
      name: "Pinyon Pine",
      scientificName: "Pinus edulis",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Pinon.jpg",
      description: "Pinyon pines are a staple of New Mexico’s landscape and culture, prized for their rich, buttery piñon nuts harvested for generations. Native to the Four Corners region, these hardy evergreens thrive in the high desert with minimal water, making them ideal for xeriscaping. Their rounded canopies and dense foliage provide year-round greenery, shade, and privacy, while deep roots help stabilize soil. From Farmington to Las Cruces, the pinyon pine remains a cherished symbol of the state’s rugged beauty and resilience.",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
      waterRequirement: "Low Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "15' x 30'",
    },
    {
      id: 1,
      name: "Austrian Pine",
      scientificName: "Pinus nigra",
      image: "https://jfschmidt.com/wp-content/uploads/2023/03/pinus-austrian-web-01.jpg",
      description: "Austrian pines are hardy evergreens well-suited to Albuquerque, growing 40 to 60 feet tall and providing excellent windbreaks, shade, and privacy. Their long, dark green needles form a dense canopy that withstands harsh sun and urban conditions. Drought-tolerant once established, they thrive in well-drained soils, making them a low-maintenance choice for adding greenery and structure to the high desert landscape.",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
      waterRequirement: "Low Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "15' x 30'",
    },
    {
      id: 2,
      name: "Afghan Pine",
      scientificName: "Pinus eldarica",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/pine-tree-6902428_1920.jpg",
      description: "Afghan pines are fast-growing evergreens that thrive in Albuquerque’s arid climate, reaching 30 to 60 feet tall. Native to the Middle East and Central Asia, they feature long, slender needles and a pyramidal shape, making them a popular choice for windbreaks, shade, and landscaping. Highly drought-tolerant once established, Afghan pines adapt well to poor soils and intense sun, requiring minimal maintenance.",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
      waterRequirement: "Moderate Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "15' x 30' tall",
    },
    {
      id: 3,
      name: "Stone Pine",
      scientificName: "Pinus pinea",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/stonePine.jpg",
      description: "Stone pines, also known as Italian stone pines, are distinctive evergreens valued for their broad, umbrella-like canopies and edible pine nuts. Native to the Mediterranean, they adapt well to Albuquerque’s climate. Their dense rounded crowns provide excellent shade, while their deep roots help stabilize soil. With their unique shape and low-maintenance needs, stone pines make a striking and practical addition to high desert landscapes.",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
      waterRequirement: "Moderate Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "15' x 30' tall",
    },
  ],

  junipers: [
    {
      id: 4,
      name: "Wichita Blue Juniper",
      scientificName: "Juniperus scopulorum 'Wichita Blue'",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/blueJuniper.jpg",
      description: "Wichita Blue junipers are striking evergreens known for their silvery-blue foliage and upright, pyramidal shape. They are an excellent choice for windbreaks, privacy screens, or ornamental accents in Albuquerque’s dry climate. Highly drought-tolerant and low-maintenance, they thrive in well-drained soils and full sun. Their dense foliage provides year-round color and structure, making them a durable and visually appealing addition to high desert landscapes.",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
      waterRequirement: "Moderate Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "10' x 20'",
    },
    {
      id: 4,
      name: "Spartan Juniper",
      scientificName: "Juniperus chinensis 'Spartan'",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
      description: "Spartan junipers are elegant, fast-growing evergreens prized for their narrow, columnar shape and rich green foliage. These Junipers are ideal for privacy screens, windbreaks, or as striking vertical accents in Albuquerque’s arid climate. Drought-tolerant and low-maintenance, they thrive in full sun and well-drained soils, requiring little pruning to maintain their sleek form. Their resilience and year-round greenery make them a versatile and attractive choice for high desert landscapes.",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
      waterRequirement: "Moderate Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "10' x 20'",
    },
    {
      id: 4,
      name: "Utah Juniper",
      scientificName: "Juniperus osteosperma",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/utahJuniper.jpg",
      description: "Utah junipers are rugged, drought-tolerant evergreens that thrive in Albuquerque’s harsh high desert. With their gnarly, twisted, and irregular growth, they stand out with dense, gray-green foliage and small, berry-like cones. These trees feature thick, woody trunks and branches, resilient to poor soils, intense sun, and minimal water. Often seen growing seemingly straight through rocks and mountainsides, Utah junipers create a striking spectacle, their enduring presence adding a dramatic touch to the landscape.",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
      waterRequirement: "Moderate Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "10' x 20'",
    },
    {
      id: 4,
      name: "Rocky Mountain Juniper",
      scientificName: "Juniperus scopulorum",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/rockmtnJuniper.jpg",
      description: "Following the mountain range down from Colorado, Rocky Mountain junipers are hardy evergreens that flourish in Albuquerque’s high desert. With their dense, blue-green foliage and distinctive, twisted branches, they offer a rugged, picturesque presence in any landscape. Known for their resilience, these junipers thrive in poor soils, intense sun, and low water conditions, making them an excellent choice for xeriscaping. Their small, berry-like cones attract wildlife, while their deep roots help stabilize soil, making them a practical and visually appealing addition to New Mexico’s rugged terrain.",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
      waterRequirement: "Moderate Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "10' x 20'",
    },
    {
      id: 4,
      name: "One Seed Juniper",
      scientificName: "Juniperus monosperma",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/oneseedJuniper.jpg",
      description: "One-seed junipers, also known as the New Mexico Juniper, are tough, drought-tolerant evergreens native to the high desert of New Mexico. Preferring higher altitudes, this resilient tree is found in limited areas outside of the state. With its bushy, upright form that grows from the ground up, the One-seed juniper offers a unique, striking shape that adds character to any yard or landscape. Well-suited for Albuquerque's intense sun, poor soils, and minimal water, it is an ideal choice for xeriscaping.",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
      waterRequirement: "Moderate Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "10' x 20'",
    },
  ],

  cedars: [
    {
      id: 4,
      name: "Red Cedar",
      scientificName: "Juniperus scopulorum",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
      description: "A drought-tolerant conifer with dense foliage and berries...",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
      waterRequirement: "Moderate Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "10' x 20'",
    },
    {
      id: 4,
      name: "Deodor Cedar",
      scientificName: "Cedrus deodara",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
      description: "A drought-tolerant conifer with dense foliage and berries...",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
      waterRequirement: "Moderate Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "10' x 20'",
    },
    {
      id: 4,
      name: "Atlas Cedar",
      scientificName: "Cedrus deodara",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
      description: "A drought-tolerant conifer with dense foliage and berries...",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
      waterRequirement: "Moderate Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "10' x 20'",
    },
    {
      id: 4,
      name: "Cypress Cedar",
      scientificName: "Cedrus deodara",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
      description: "A drought-tolerant conifer with dense foliage and berries...",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
      waterRequirement: "Moderate Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "10' x 20'",
    },
  ],
  spruces: [
    {
      id: 4,
      name: "Blue Spruce",
      scientificName: "Picea pungens",
      image: "https://jfschmidt.com/wp-content/uploads/2023/03/picea-fatalbert-web-01.jpg",
      description: "Blue spruce is a striking evergreen known for its silvery-blue needles and symmetrical, conical shape. Native to the Rocky Mountain region, this tree thrives in Albuquerque’s high desert, offering year-round color and structure to landscapes. With its dense foliage and strong, upright growth, blue spruce makes an excellent choice for privacy screens, windbreaks, or ornamental accents anywhere from Santa Fe to Rio Rancho.",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
      waterRequirement: "Moderate Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "10' x 20'",
    },
    {
      id: 4,
      name: "Engelmann Spruce",
      scientificName: "Picea engelmannii",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/engelmannSpruce.jpg",
      description: "Engelmann spruce is a hardy evergreen native to the Rocky Mountains, known for its slender, conical shape and soft, bluish-green needles. While it thrives in cooler, higher elevations, it can perform well in the Albuquerque and Santa Fe regions, where it adds dense, symmetrical growth and vibrant color to the landscape. Ideal for windbreaks or privacy screens, Engelmann spruce is adaptable to various soil types and tolerates both drought and cold conditions.",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
      waterRequirement: "Moderate Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "10' x 20'",
    },
    {
      id: 4,
      name: "Sitka Spruce",
      scientificName: "Picea sitchensis",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/sitka.jpg",
      description: "Sitka spruce is a majestic evergreen native to the Pacific Northwest, known for its tall, straight trunk and soft, bluish-green needles. While it typically thrives in cooler, coastal climates, it can adapt to Albuquerque and Santa Fe regions with the right care. Its dense, pyramid-shaped canopy provides excellent shade, privacy, and wind protection. Sitka spruce prefers moist, well-drained soils and does best in areas with moderate temperatures, so it may not fare as well in the hotter, drier climates of southern New Mexico, such as Las Cruces.",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
      waterRequirement: "Moderate Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "10' x 20'",
    },
    {
      id: 4,
      name: "Norway Spruce",
      scientificName: "Picea abies",
      image: "https://jfschmidt.com/wp-content/uploads/2023/06/picea-columnarnorway-web-01.jpg",
      description: "Norway spruce is a tall, fast-growing evergreen known for its symmetrical, pyramidal shape and dense, dark green needles. This tree features drooping branches and long, cylindrical cones, giving it a distinctive appearance. Norway spruce is adaptable to various soil types and tolerates both drought and cold conditions once established. With its elegant form and dense foliage, it provides excellent coverage and shade, making it a striking addition to a variety of landscapes.",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
      waterRequirement: "Moderate Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "10' x 20'",
    },
  ],
  firs: [
    {
      id: 4,
      name: "Douglas Fir",
      scientificName: "Juniperus scopulorum",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/douglasFir.jpg",
      description: "A drought-tolerant conifer with dense foliage and berries...",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
      waterRequirement: "Moderate Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "10' x 20'",
    },
    {
      id: 4,
      name: "White Fir",
      scientificName: "Juniperus scopulorum",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Fir.jpg",
      description: "A drought-tolerant conifer with dense foliage and berries...",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
      waterRequirement: "Moderate Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "10' x 20'",
    },
    {
      id: 4,
      name: "Fraser Fir",
      scientificName: "Juniperus scopulorum",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
      description: "A drought-tolerant conifer with dense foliage and berries...",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
      waterRequirement: "Moderate Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "10' x 20'",
    },
  ],
  cypress: [
    {
      id: 4,
      name: "Italian Cypress",
      scientificName: "Juniperus scopulorum",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/italianCypress.jpg",
      description: "A drought-tolerant conifer with dense foliage and berries...",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
      waterRequirement: "Moderate Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "10' x 20'",
    },
    {
      id: 4,
      name: "Arizona Cypress",
      scientificName: "Juniperus scopulorum",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/arizonaCypress.jpeg",
      description: "A drought-tolerant conifer with dense foliage and berries...",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
      waterRequirement: "Moderate Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "10' x 20'",
    },
    {
      id: 4,
      name: "Smooth Cypress",
      scientificName: "Juniperus scopulorum",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/cypress-357846_1920.jpg",
      description: "A drought-tolerant conifer with dense foliage and berries...",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
      waterRequirement: "Moderate Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "10' x 20'",
    },
    {
      id: 4,
      name: "Leyland Cypress",
      scientificName: "Juniperus scopulorum",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/randomCypress.jpg",
      description: "A drought-tolerant conifer with dense foliage and berries...",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
      waterRequirement: "Moderate Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "10' x 20'",
    },
  ],
  arborvitaes: [
    {
      id: 4,
      name: "American Arborvitae",
      scientificName: "Juniperus scopulorum",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/arborvitae-4913378_1920.jpg",
      description: "A drought-tolerant conifer with dense foliage and berries...",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
      waterRequirement: "Moderate Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "10' x 20'",
    },
    {
      id: 4,
      name: "Green Giant Arborvitae",
      scientificName: "Juniperus scopulorum",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/thuja-6656032_1920.jpg",
      description: "A drought-tolerant conifer with dense foliage and berries...",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
      waterRequirement: "Moderate Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "10' x 20'",
    },
    {
      id: 4,
      name: "Emerald Arborvitae",
      scientificName: "Juniperus scopulorum",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/arborvitae.jpg",
      description: "A drought-tolerant conifer with dense foliage and berries...",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
      waterRequirement: "Moderate Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "10' x 20'",
    },
  ],


};

export default coniferdata;
