const coniferdata = {
  pines: [
    {
      id: 1,
      name: "Pinyon Pine",
      scientificName: "Pinus edulis",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Pinon.jpg",
      description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
      waterRequirement: "Low Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "15' x 30'",
    },
    {
      id: 1,
      name: "Austrian Pine",
      scientificName: "Pinus edulis",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Pinon.jpg",
      description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
      waterRequirement: "Low Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "15' x 30'",
    },
    {
      id: 2,
      name: "Afghan Pine",
      scientificName: "Pinus Eldarica",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/austrainPine.jpg",
      description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
      waterRequirement: "Moderate Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "15' x 30' tall",
    },
    {
      id: 3,
      name: "Stone Pine",
      scientificName: "Pinus Eldarica",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/austrainPine.jpg",
      description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
      waterRequirement: "Moderate Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "15' x 30' tall",
    },
  ],

  junipers: [
    {
      id: 4,
      name: "Wichita Blue Juniper",
      scientificName: "Juniperus scopulorum",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
      description: "A drought-tolerant conifer with dense foliage and berries...",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
      waterRequirement: "Moderate Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "10' x 20'",
    },
    {
      id: 4,
      name: "Spartan Juniper",
      scientificName: "Juniperus scopulorum",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
      description: "A drought-tolerant conifer with dense foliage and berries...",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
      waterRequirement: "Moderate Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "10' x 20'",
    },
    {
      id: 4,
      name: "Alligator Juniper",
      scientificName: "Juniperus scopulorum",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
      description: "A drought-tolerant conifer with dense foliage and berries...",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
      waterRequirement: "Moderate Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "10' x 20'",
    },
    {
      id: 4,
      name: "Rocky Mountain Juniper",
      scientificName: "Juniperus scopulorum",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
      description: "A drought-tolerant conifer with dense foliage and berries...",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
      waterRequirement: "Moderate Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "10' x 20'",
    },
    {
      id: 4,
      name: "One Seed Juniper",
      scientificName: "Juniperus scopulorum",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
      description: "A drought-tolerant conifer with dense foliage and berries...",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
      waterRequirement: "Moderate Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "10' x 20'",
    },
  ],

  cedars: [
    {
      id: 4,
      name: "Red Cedar",
      scientificName: "Juniperus scopulorum",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
      description: "A drought-tolerant conifer with dense foliage and berries...",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
      waterRequirement: "Moderate Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "10' x 20'",
    },
    {
      id: 4,
      name: "Deodor Cedar",
      scientificName: "Cedrus deodara",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
      description: "A drought-tolerant conifer with dense foliage and berries...",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
      waterRequirement: "Moderate Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "10' x 20'",
    },
    {
      id: 4,
      name: "Atlas Cedar",
      scientificName: "Cedrus deodara",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
      description: "A drought-tolerant conifer with dense foliage and berries...",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
      waterRequirement: "Moderate Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "10' x 20'",
    },
    {
      id: 4,
      name: "Cypress Cedar",
      scientificName: "Cedrus deodara",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
      description: "A drought-tolerant conifer with dense foliage and berries...",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
      waterRequirement: "Moderate Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "10' x 20'",
    },
  ],
  spruces: [
    {
      id: 4,
      name: "Colorado Blue Spruce",
      scientificName: "Juniperus scopulorum",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
      description: "A drought-tolerant conifer with dense foliage and berries...",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
      waterRequirement: "Moderate Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "10' x 20'",
    },
    {
      id: 4,
      name: "Engelmann Spruce",
      scientificName: "Juniperus scopulorum",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
      description: "A drought-tolerant conifer with dense foliage and berries...",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
      waterRequirement: "Moderate Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "10' x 20'",
    },
    {
      id: 4,
      name: "Stika Spruce",
      scientificName: "Juniperus scopulorum",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
      description: "A drought-tolerant conifer with dense foliage and berries...",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
      waterRequirement: "Moderate Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "10' x 20'",
    },
    {
      id: 4,
      name: "Alberta Spruce",
      scientificName: "Juniperus scopulorum",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
      description: "A drought-tolerant conifer with dense foliage and berries...",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
      waterRequirement: "Moderate Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "10' x 20'",
    },
    {
      id: 4,
      name: "Norway Spruce",
      scientificName: "Juniperus scopulorum",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
      description: "A drought-tolerant conifer with dense foliage and berries...",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
      waterRequirement: "Moderate Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "10' x 20'",
    },
  ],
  firs: [
    {
      id: 4,
      name: "Douglas Fir",
      scientificName: "Juniperus scopulorum",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
      description: "A drought-tolerant conifer with dense foliage and berries...",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
      waterRequirement: "Moderate Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "10' x 20'",
    },
    {
      id: 4,
      name: "White Fir",
      scientificName: "Juniperus scopulorum",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
      description: "A drought-tolerant conifer with dense foliage and berries...",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
      waterRequirement: "Moderate Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "10' x 20'",
    },
    {
      id: 4,
      name: "Fraser Fir",
      scientificName: "Juniperus scopulorum",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
      description: "A drought-tolerant conifer with dense foliage and berries...",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
      waterRequirement: "Moderate Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "10' x 20'",
    },
  ],
  cypress: [
    {
      id: 4,
      name: "Italian Cypress",
      scientificName: "Juniperus scopulorum",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
      description: "A drought-tolerant conifer with dense foliage and berries...",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
      waterRequirement: "Moderate Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "10' x 20'",
    },
    {
      id: 4,
      name: "Arizona Cypress",
      scientificName: "Juniperus scopulorum",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
      description: "A drought-tolerant conifer with dense foliage and berries...",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
      waterRequirement: "Moderate Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "10' x 20'",
    },
    {
      id: 4,
      name: "Smooth Cypress",
      scientificName: "Juniperus scopulorum",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
      description: "A drought-tolerant conifer with dense foliage and berries...",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
      waterRequirement: "Moderate Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "10' x 20'",
    },
    {
      id: 4,
      name: "Leyland Cypress",
      scientificName: "Juniperus scopulorum",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
      description: "A drought-tolerant conifer with dense foliage and berries...",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
      waterRequirement: "Moderate Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "10' x 20'",
    },
  ],
  arborvitaes: [
    {
      id: 4,
      name: "American Arborvitae",
      scientificName: "Juniperus scopulorum",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
      description: "A drought-tolerant conifer with dense foliage and berries...",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
      waterRequirement: "Moderate Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "10' x 20'",
    },
    {
      id: 4,
      name: "Green Giant Arborvitae",
      scientificName: "Juniperus scopulorum",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
      description: "A drought-tolerant conifer with dense foliage and berries...",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
      waterRequirement: "Moderate Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "10' x 20'",
    },
    {
      id: 4,
      name: "Emerald Arborvitae",
      scientificName: "Juniperus scopulorum",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
      description: "A drought-tolerant conifer with dense foliage and berries...",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
      waterRequirement: "Moderate Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "10' x 20'",
    },
  ],


};

export default coniferdata;
