const fruitdata = {
apples: [
      {
        id: 1,
        name: "Fuji Apple",
        scientificName: "Pinus edulis",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Pinon.jpg",
        description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30'",
      },
      {
        id: 2,
        name: "Honeycrisp Apple",
        scientificName: "Pinus Eldarica",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/austrainPine.jpg",
        description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30' tall",
      },
      {
        id: 3,
        name: "Granny Smith Apple",
        scientificName: "Pinus Eldarica",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/austrainPine.jpg",
        description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30' tall",
      },
    ],
  
    cherries: [
      {
        id: 4,
        name: "Bing Cherry",
        scientificName: "Juniperus scopulorum",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
        description: "A drought-tolerant conifer with dense foliage and berries...",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "10' x 20'",
      },
      {
        id: 4,
        name: "Wichita Juniper",
        scientificName: "Rainer Cherry",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
        description: "A drought-tolerant conifer with dense foliage and berries...",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "10' x 20'",
      },
      {
        id: 4,
        name: "Wichita Juniper",
        scientificName: "Monmorency Cherry",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
        description: "A drought-tolerant conifer with dense foliage and berries...",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "10' x 20'",
      },
    ],
  
    peaches: [
      {
        id: 4,
        name: "Redhaven Peach",
        scientificName: "Redhaven Peach",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
        description: "A drought-tolerant conifer with dense foliage and berries...",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "10' x 20'",
      },
      {
        id: 4,
        name: "Elberta Peach",
        scientificName: "Redhaven Peach",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
        description: "A drought-tolerant conifer with dense foliage and berries...",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "10' x 20'",
      },
      {
        id: 4,
        name: "Contender Peach",
        scientificName: "Redhaven Peach",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
        description: "A drought-tolerant conifer with dense foliage and berries...",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "10' x 20'",
      },
    ],
    nectarines: [
        {
          id: 4,
          name: "Fantasia",
          scientificName: "Redhaven Peach",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
          description: "A drought-tolerant conifer with dense foliage and berries...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
          waterRequirement: "Moderate Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "10' x 20'",
        },
        {
          id: 4,
          name: "Artic Star",
          scientificName: "Redhaven Peach",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
          description: "A drought-tolerant conifer with dense foliage and berries...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
          waterRequirement: "Moderate Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "10' x 20'",
        },
      ],
      apricots: [
        {
            id: 4,
            name: "Artic Star",
            scientificName: "Redhaven Peach",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },

      ],
      plums: [
        {
            id: 4,
            name: "Santa Rosa",
            scientificName: "Redhaven Peach",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
        {
            id: 4,
            name: "Methley Plum",
            scientificName: "Redhaven Peach",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
          {
            id: 4,
            name: "Stanley Plum",
            scientificName: "Redhaven Peach",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },

      ],
      pears: [
        {
            id: 4,
            name: "Bartlett Pear",
            scientificName: "Redhaven Peach",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
        {
            id: 4,
            name: "D'Anjou Pear",
            scientificName: "Redhaven Peach",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
          {
            id: 4,
            name: "Kieffer Pear",
            scientificName: "Redhaven Peach",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },

      ],
      figs: [
        {
            id: 4,
            name: "Brown Turkey Fig",
            scientificName: "Redhaven Peach",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
        {
            id: 4,
            name: "Celeste Fig",
            scientificName: "Redhaven Peach",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
      ],
      pomegranates: [
        {
            id: 4,
            name: "Wonderful Pomegranates",
            scientificName: "Redhaven Peach",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
        {
            id: 4,
            name: "Russain 26 Pomegranates",
            scientificName: "Redhaven Peach",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
      ],
      nuts: [
        {
            id: 4,
            name: "Wonderful Pomegranates",
            scientificName: "Redhaven Peach",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
        {
            id: 4,
            name: "Russain 26 Pomegranates",
            scientificName: "Redhaven Peach",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
      ],
      others: [
        {
            id: 4,
            name: "Wonderful Pomegranates",
            scientificName: "Redhaven Peach",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
        {
            id: 4,
            name: "Russain 26 Pomegranates",
            scientificName: "Redhaven Peach",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
      ],
  
  };
  
  export default fruitdata;
  