const fruitdata = {
apples: [
      {
        id: 1,
        name: "Fuji Apple",
        scientificName: "Pinus edulis",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/apples-2788599_1920.jpg",
        description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30'",
      },
      {
        id: 2,
        name: "Honeycrisp Apple",
        scientificName: "Pinus Eldarica",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/apple-4055926_1920.jpg",
        description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30' tall",
      },
      {
        id: 3,
        name: "Granny Smith Apple",
        scientificName: "Pinus Eldarica",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/grannysmith.jpg",
        description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30' tall",
      },
    ],
  
    cherries: [
      {
        id: 4,
        name: "Bing Cherry",
        scientificName: "Juniperus scopulorum",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/cherry-2369275_1920.jpg",
        description: "A drought-tolerant conifer with dense foliage and berries...",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "10' x 20'",
      },
      {
        id: 4,
        name: "Rainer Cherry",
        scientificName: "Rainer Cherry",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/cherry-212601_1920.jpg",
        description: "A drought-tolerant conifer with dense foliage and berries...",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "10' x 20'",
      },
      {
        id: 4,
        name: "Monmorency Cherry",
        scientificName: "Monmorency Cherry",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/cherry.jpg",
        description: "A drought-tolerant conifer with dense foliage and berries...",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "10' x 20'",
      },
    ],
  
    peaches: [
      {
        id: 4,
        name: "Redhaven Peach",
        scientificName: "Redhaven Peach",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/peaches-3529802_1920.jpg",
        description: "A drought-tolerant conifer with dense foliage and berries...",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "10' x 20'",
      },
      {
        id: 4,
        name: "Elberta Peach",
        scientificName: "Redhaven Peach",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/peach-2632182_1920.jpg",
        description: "A drought-tolerant conifer with dense foliage and berries...",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "10' x 20'",
      },
      {
        id: 4,
        name: "Contender Peach",
        scientificName: "Redhaven Peach",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/peach.jpg",
        description: "A drought-tolerant conifer with dense foliage and berries...",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "10' x 20'",
      },
    ],
    nectarines: [
        {
          id: 4,
          name: "Fantasia",
          scientificName: "Redhaven Peach",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/nectarines-196805_1920.jpg",
          description: "A drought-tolerant conifer with dense foliage and berries...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
          waterRequirement: "Moderate Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "10' x 20'",
        },
        {
          id: 4,
          name: "Artic Star",
          scientificName: "Redhaven Peach",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/nectarine.jpg",
          description: "A drought-tolerant conifer with dense foliage and berries...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
          waterRequirement: "Moderate Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "10' x 20'",
        },
      ],
      apricots: [
        {
            id: 4,
            name: "Artic Star",
            scientificName: "Redhaven Peach",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/apricots-6396505_1920.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
        {
            id: 4,
            name: "Artic Star",
            scientificName: "Redhaven Peach",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/apricots-6396524_1920.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
        {
            id: 4,
            name: "Artic Star",
            scientificName: "Redhaven Peach",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/apricots-824626_1920.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },

      ],
      plums: [
        {
            id: 4,
            name: "Santa Rosa",
            scientificName: "Redhaven Peach",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/plums-3628167_1920.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
        {
            id: 4,
            name: "Methley Plum",
            scientificName: "Redhaven Peach",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/plum-4344623_1920.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
          {
            id: 4,
            name: "Stanley Plum",
            scientificName: "Redhaven Peach",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/plums-3628167_1920.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },

      ],
      pears: [
        {
            id: 4,
            name: "Bartlett Pear",
            scientificName: "Redhaven Peach",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/pear-2297977_1920.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
        {
            id: 4,
            name: "D'Anjou Pear",
            scientificName: "Redhaven Peach",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/pear-3560106_1920.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
          {
            id: 4,
            name: "Kieffer Pear",
            scientificName: "Redhaven Peach",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/pear.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },

      ],
      figs: [
        {
            id: 4,
            name: "Brown Turkey Fig",
            scientificName: "Redhaven Peach",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/fig.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
        {
            id: 4,
            name: "Celeste Fig",
            scientificName: "Redhaven Peach",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/figs-7421496_1920.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
      ],
      pomegranates: [
        {
            id: 4,
            name: "Wonderful Pomegranates",
            scientificName: "Redhaven Peach",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/pomegranate-2825556_1920.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
        {
            id: 4,
            name: "Russain 26 Pomegranates",
            scientificName: "Redhaven Peach",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/fruit-3036563_1920.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
      ],
      almonds: [
        {
            id: 4,
            name: "Mission Almonds",
            scientificName: "Redhaven Peach",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/almond-tree-5951352_1920.jpg",
            description: "One of the most common varieties, the Mission Almond sometimes known as the Texas Almond, is a great almond for Southern New Mexico, but think twice before planting in the Albuquerque area. Although the most popular, almonds are notoriously early bloomers, with this variety being a VERY early bloomer. With late freezes in Albuquerque and Santa Fe, you may seldom get fruit.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
        {
            id: 4,
            name: "Bounty Almond",
            scientificName: "Redhaven Peach",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/almond-5530630_1920.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
        {
            id: 4,
            name: "All-In-One Almond",
            scientificName: "Redhaven Peach",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/almonds-2667060_1920.jpg",
            description: "All-In-One stays true to its namesake being a realiable almond producer with  a later bloom season than other almonds making it better for Northern New Mexico. Its hardiness in -20F is another reason its a great all around choice to Albuqueruque Almond Trees.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
      ],
      pecans: [
        {
            id: 4,
            name: "Western Schley Pecans",
            scientificName: "Redhaven Peach",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/nuts-315687_1920.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
        {
            id: 4,
            name: "Wichita Pecan",
            scientificName: "Redhaven Peach",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/nuts-316146_1920.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
        {
            id: 4,
            name: "Cheyenne Pecan",
            scientificName: "Redhaven Peach",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/pecan-tree-186328_1920.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
      ],
      pistachios: [
        {
            id: 4,
            name: "Kerman Pistachios",
            scientificName: "Redhaven Peach",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/pistachios-1540123_1920.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
        {
            id: 4,
            name: "Peters Pistachios",
            scientificName: "Redhaven Peach",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/pistachios-1540134_1920.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
        {
            id: 4,
            name: "Kalehghouchi Pistachios",
            scientificName: "Redhaven Peach",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/pistachio-1137886_1920.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
      ],
      others: [
        {
            id: 4,
            name: "JuJubes (Chinese Date)",
            scientificName: "Redhaven Peach",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/autumn-3400000_1920.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
        {
            id: 4,
            name: "Persimmons",
            scientificName: "Redhaven Peach",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/persimmons-6735325_1920.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
        {
            id: 4,
            name: "Grapes",
            scientificName: "Redhaven Peach",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/vines-1747224_1920.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
      ],
  
  };
  
  export default fruitdata;
  