const cactusdata =
{
    cactus: [
    {
        id: 1,
        name: "Santa Rita Prickly Pear Cactus",
        scientificName: "(Vitis vinifera)",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/vines-1747224_1920.jpg",
        description: "Grape Vines are a popular fruit crop for New Mexico, thriving in the state’s sunny, dry climate. Grapevines need full sun and well-draining, slightly sandy soil to produce high-quality fruit. They are ideal for both home gardeners and commercial growers, particularly in the southern and central regions, where the extended growing season supports their long ripening period. Grapes require regular irrigation, especially during the hot summer months, but they are fairly drought-tolerant once established. Varieties like Concord, Thompson Seedless, and Zinfandel are commonly grown, offering a range of flavors for fresh eating, drying, or wine production.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: "4-10",
        matureSize: "50-100 sq ft",
        native: false
    },
    {
        id: 1,
        name: "Spinless Prickly Pear Cactus",
        scientificName: "(Vitis vinifera)",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/vines-1747224_1920.jpg",
        description: "Grape Vines are a popular fruit crop for New Mexico, thriving in the state’s sunny, dry climate. Grapevines need full sun and well-draining, slightly sandy soil to produce high-quality fruit. They are ideal for both home gardeners and commercial growers, particularly in the southern and central regions, where the extended growing season supports their long ripening period. Grapes require regular irrigation, especially during the hot summer months, but they are fairly drought-tolerant once established. Varieties like Concord, Thompson Seedless, and Zinfandel are commonly grown, offering a range of flavors for fresh eating, drying, or wine production.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: "4-10",
        matureSize: "50-100 sq ft",
        native: false
    },
    {
        id: 1,
        name: "Engelmann Prickly Pear Cactus",
        scientificName: "(Vitis vinifera)",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/vines-1747224_1920.jpg",
        description: "Grape Vines are a popular fruit crop for New Mexico, thriving in the state’s sunny, dry climate. Grapevines need full sun and well-draining, slightly sandy soil to produce high-quality fruit. They are ideal for both home gardeners and commercial growers, particularly in the southern and central regions, where the extended growing season supports their long ripening period. Grapes require regular irrigation, especially during the hot summer months, but they are fairly drought-tolerant once established. Varieties like Concord, Thompson Seedless, and Zinfandel are commonly grown, offering a range of flavors for fresh eating, drying, or wine production.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: "4-10",
        matureSize: "50-100 sq ft",
        native: false
    },
    {
        id: 1,
        name: "Teddy Bear Cholla Cactus",
        scientificName: "(Vitis vinifera)",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/vines-1747224_1920.jpg",
        description: "Grape Vines are a popular fruit crop for New Mexico, thriving in the state’s sunny, dry climate. Grapevines need full sun and well-draining, slightly sandy soil to produce high-quality fruit. They are ideal for both home gardeners and commercial growers, particularly in the southern and central regions, where the extended growing season supports their long ripening period. Grapes require regular irrigation, especially during the hot summer months, but they are fairly drought-tolerant once established. Varieties like Concord, Thompson Seedless, and Zinfandel are commonly grown, offering a range of flavors for fresh eating, drying, or wine production.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: "4-10",
        matureSize: "50-100 sq ft",
        native: false
    },
    {
        id: 1,
        name: "Cane Cholla Cactus",
        scientificName: "(Vitis vinifera)",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/vines-1747224_1920.jpg",
        description: "Grape Vines are a popular fruit crop for New Mexico, thriving in the state’s sunny, dry climate. Grapevines need full sun and well-draining, slightly sandy soil to produce high-quality fruit. They are ideal for both home gardeners and commercial growers, particularly in the southern and central regions, where the extended growing season supports their long ripening period. Grapes require regular irrigation, especially during the hot summer months, but they are fairly drought-tolerant once established. Varieties like Concord, Thompson Seedless, and Zinfandel are commonly grown, offering a range of flavors for fresh eating, drying, or wine production.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: "4-10",
        matureSize: "50-100 sq ft",
        native: false
    },
    {
        id: 1,
        name: "Staghorn Cholla Cactus",
        scientificName: "(Vitis vinifera)",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/vines-1747224_1920.jpg",
        description: "Grape Vines are a popular fruit crop for New Mexico, thriving in the state’s sunny, dry climate. Grapevines need full sun and well-draining, slightly sandy soil to produce high-quality fruit. They are ideal for both home gardeners and commercial growers, particularly in the southern and central regions, where the extended growing season supports their long ripening period. Grapes require regular irrigation, especially during the hot summer months, but they are fairly drought-tolerant once established. Varieties like Concord, Thompson Seedless, and Zinfandel are commonly grown, offering a range of flavors for fresh eating, drying, or wine production.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: "4-10",
        matureSize: "50-100 sq ft",
        native: false
    },
    {
        id: 1,
        name: "Golden Barrel Cactus",
        scientificName: "(Vitis vinifera)",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/vines-1747224_1920.jpg",
        description: "Grape Vines are a popular fruit crop for New Mexico, thriving in the state’s sunny, dry climate. Grapevines need full sun and well-draining, slightly sandy soil to produce high-quality fruit. They are ideal for both home gardeners and commercial growers, particularly in the southern and central regions, where the extended growing season supports their long ripening period. Grapes require regular irrigation, especially during the hot summer months, but they are fairly drought-tolerant once established. Varieties like Concord, Thompson Seedless, and Zinfandel are commonly grown, offering a range of flavors for fresh eating, drying, or wine production.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: "4-10",
        matureSize: "50-100 sq ft",
        native: false
    },
    {
        id: 1,
        name: "Fishhook Barrel Cactus",
        scientificName: "(Vitis vinifera)",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/vines-1747224_1920.jpg",
        description: "Grape Vines are a popular fruit crop for New Mexico, thriving in the state’s sunny, dry climate. Grapevines need full sun and well-draining, slightly sandy soil to produce high-quality fruit. They are ideal for both home gardeners and commercial growers, particularly in the southern and central regions, where the extended growing season supports their long ripening period. Grapes require regular irrigation, especially during the hot summer months, but they are fairly drought-tolerant once established. Varieties like Concord, Thompson Seedless, and Zinfandel are commonly grown, offering a range of flavors for fresh eating, drying, or wine production.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: "4-10",
        matureSize: "50-100 sq ft",
        native: false
    },
    {
        id: 1,
        name: "Arizona Barrel Cactus",
        scientificName: "(Vitis vinifera)",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/vines-1747224_1920.jpg",
        description: "Grape Vines are a popular fruit crop for New Mexico, thriving in the state’s sunny, dry climate. Grapevines need full sun and well-draining, slightly sandy soil to produce high-quality fruit. They are ideal for both home gardeners and commercial growers, particularly in the southern and central regions, where the extended growing season supports their long ripening period. Grapes require regular irrigation, especially during the hot summer months, but they are fairly drought-tolerant once established. Varieties like Concord, Thompson Seedless, and Zinfandel are commonly grown, offering a range of flavors for fresh eating, drying, or wine production.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: "4-10",
        matureSize: "50-100 sq ft",
        native: false
    },
    {
        id: 1,
        name: "Claret Cup Cactus",
        scientificName: "(Vitis vinifera)",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/vines-1747224_1920.jpg",
        description: "Grape Vines are a popular fruit crop for New Mexico, thriving in the state’s sunny, dry climate. Grapevines need full sun and well-draining, slightly sandy soil to produce high-quality fruit. They are ideal for both home gardeners and commercial growers, particularly in the southern and central regions, where the extended growing season supports their long ripening period. Grapes require regular irrigation, especially during the hot summer months, but they are fairly drought-tolerant once established. Varieties like Concord, Thompson Seedless, and Zinfandel are commonly grown, offering a range of flavors for fresh eating, drying, or wine production.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: "4-10",
        matureSize: "50-100 sq ft",
        native: false
    },
    {
        id: 1,
        name: "Strawberry Hedgehog Cactus",
        scientificName: "(Vitis vinifera)",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/vines-1747224_1920.jpg",
        description: "Grape Vines are a popular fruit crop for New Mexico, thriving in the state’s sunny, dry climate. Grapevines need full sun and well-draining, slightly sandy soil to produce high-quality fruit. They are ideal for both home gardeners and commercial growers, particularly in the southern and central regions, where the extended growing season supports their long ripening period. Grapes require regular irrigation, especially during the hot summer months, but they are fairly drought-tolerant once established. Varieties like Concord, Thompson Seedless, and Zinfandel are commonly grown, offering a range of flavors for fresh eating, drying, or wine production.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: "4-10",
        matureSize: "50-100 sq ft",
        native: false
    },
    {
        id: 1,
        name: "Texas Rainbow Cactus",
        scientificName: "(Vitis vinifera)",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/vines-1747224_1920.jpg",
        description: "Grape Vines are a popular fruit crop for New Mexico, thriving in the state’s sunny, dry climate. Grapevines need full sun and well-draining, slightly sandy soil to produce high-quality fruit. They are ideal for both home gardeners and commercial growers, particularly in the southern and central regions, where the extended growing season supports their long ripening period. Grapes require regular irrigation, especially during the hot summer months, but they are fairly drought-tolerant once established. Varieties like Concord, Thompson Seedless, and Zinfandel are commonly grown, offering a range of flavors for fresh eating, drying, or wine production.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: "4-10",
        matureSize: "50-100 sq ft",
        native: false
    },
    {
        id: 1,
        name: "Mammillaria Cactus",
        scientificName: "(Vitis vinifera)",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/vines-1747224_1920.jpg",
        description: "Grape Vines are a popular fruit crop for New Mexico, thriving in the state’s sunny, dry climate. Grapevines need full sun and well-draining, slightly sandy soil to produce high-quality fruit. They are ideal for both home gardeners and commercial growers, particularly in the southern and central regions, where the extended growing season supports their long ripening period. Grapes require regular irrigation, especially during the hot summer months, but they are fairly drought-tolerant once established. Varieties like Concord, Thompson Seedless, and Zinfandel are commonly grown, offering a range of flavors for fresh eating, drying, or wine production.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: "4-10",
        matureSize: "50-100 sq ft",
        native: false
    },
    {
        id: 1,
        name: "Totem Pole Cactus",
        scientificName: "(Vitis vinifera)",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/vines-1747224_1920.jpg",
        description: "Grape Vines are a popular fruit crop for New Mexico, thriving in the state’s sunny, dry climate. Grapevines need full sun and well-draining, slightly sandy soil to produce high-quality fruit. They are ideal for both home gardeners and commercial growers, particularly in the southern and central regions, where the extended growing season supports their long ripening period. Grapes require regular irrigation, especially during the hot summer months, but they are fairly drought-tolerant once established. Varieties like Concord, Thompson Seedless, and Zinfandel are commonly grown, offering a range of flavors for fresh eating, drying, or wine production.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: "4-10",
        matureSize: "50-100 sq ft",
        native: false
    },

    ],
    yuccas: [
    {
        id: 1,
        name: "Adam's Needle Yucca",
        scientificName: "(Vitis vinifera)",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/vines-1747224_1920.jpg",
        description: "Grape Vines are a popular fruit crop for New Mexico, thriving in the state’s sunny, dry climate. Grapevines need full sun and well-draining, slightly sandy soil to produce high-quality fruit. They are ideal for both home gardeners and commercial growers, particularly in the southern and central regions, where the extended growing season supports their long ripening period. Grapes require regular irrigation, especially during the hot summer months, but they are fairly drought-tolerant once established. Varieties like Concord, Thompson Seedless, and Zinfandel are commonly grown, offering a range of flavors for fresh eating, drying, or wine production.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: "4-10",
        matureSize: "50-100 sq ft",
        native: false
    },
    {
        id: 1,
        name: "Chaparral Yucca",
        scientificName: "(Vitis vinifera)",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/vines-1747224_1920.jpg",
        description: "Grape Vines are a popular fruit crop for New Mexico, thriving in the state’s sunny, dry climate. Grapevines need full sun and well-draining, slightly sandy soil to produce high-quality fruit. They are ideal for both home gardeners and commercial growers, particularly in the southern and central regions, where the extended growing season supports their long ripening period. Grapes require regular irrigation, especially during the hot summer months, but they are fairly drought-tolerant once established. Varieties like Concord, Thompson Seedless, and Zinfandel are commonly grown, offering a range of flavors for fresh eating, drying, or wine production.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: "4-10",
        matureSize: "50-100 sq ft",
        native: false
    },
    {
        id: 1,
        name: "Narrow-leaf Yucca",
        scientificName: "(Vitis vinifera)",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/vines-1747224_1920.jpg",
        description: "Grape Vines are a popular fruit crop for New Mexico, thriving in the state’s sunny, dry climate. Grapevines need full sun and well-draining, slightly sandy soil to produce high-quality fruit. They are ideal for both home gardeners and commercial growers, particularly in the southern and central regions, where the extended growing season supports their long ripening period. Grapes require regular irrigation, especially during the hot summer months, but they are fairly drought-tolerant once established. Varieties like Concord, Thompson Seedless, and Zinfandel are commonly grown, offering a range of flavors for fresh eating, drying, or wine production.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: "4-10",
        matureSize: "50-100 sq ft",
        native: false
    },
    {
        id: 1,
        name: "Banana Yucca",
        scientificName: "(Vitis vinifera)",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/vines-1747224_1920.jpg",
        description: "Grape Vines are a popular fruit crop for New Mexico, thriving in the state’s sunny, dry climate. Grapevines need full sun and well-draining, slightly sandy soil to produce high-quality fruit. They are ideal for both home gardeners and commercial growers, particularly in the southern and central regions, where the extended growing season supports their long ripening period. Grapes require regular irrigation, especially during the hot summer months, but they are fairly drought-tolerant once established. Varieties like Concord, Thompson Seedless, and Zinfandel are commonly grown, offering a range of flavors for fresh eating, drying, or wine production.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: "4-10",
        matureSize: "50-100 sq ft",
        native: false
    },
    {
        id: 1,
        name: "Navajo Yucca",
        scientificName: "(Vitis vinifera)",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/vines-1747224_1920.jpg",
        description: "Grape Vines are a popular fruit crop for New Mexico, thriving in the state’s sunny, dry climate. Grapevines need full sun and well-draining, slightly sandy soil to produce high-quality fruit. They are ideal for both home gardeners and commercial growers, particularly in the southern and central regions, where the extended growing season supports their long ripening period. Grapes require regular irrigation, especially during the hot summer months, but they are fairly drought-tolerant once established. Varieties like Concord, Thompson Seedless, and Zinfandel are commonly grown, offering a range of flavors for fresh eating, drying, or wine production.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: "4-10",
        matureSize: "50-100 sq ft",
        native: false
    },
    {
        id: 1,
        name: "Soaptree Yucca",
        scientificName: "(Vitis vinifera)",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/vines-1747224_1920.jpg",
        description: "Grape Vines are a popular fruit crop for New Mexico, thriving in the state’s sunny, dry climate. Grapevines need full sun and well-draining, slightly sandy soil to produce high-quality fruit. They are ideal for both home gardeners and commercial growers, particularly in the southern and central regions, where the extended growing season supports their long ripening period. Grapes require regular irrigation, especially during the hot summer months, but they are fairly drought-tolerant once established. Varieties like Concord, Thompson Seedless, and Zinfandel are commonly grown, offering a range of flavors for fresh eating, drying, or wine production.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: "4-10",
        matureSize: "50-100 sq ft",
        native: false
    },
    {
        id: 1,
        name: "Spanish Dagger Yucca",
        scientificName: "(Vitis vinifera)",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/vines-1747224_1920.jpg",
        description: "Grape Vines are a popular fruit crop for New Mexico, thriving in the state’s sunny, dry climate. Grapevines need full sun and well-draining, slightly sandy soil to produce high-quality fruit. They are ideal for both home gardeners and commercial growers, particularly in the southern and central regions, where the extended growing season supports their long ripening period. Grapes require regular irrigation, especially during the hot summer months, but they are fairly drought-tolerant once established. Varieties like Concord, Thompson Seedless, and Zinfandel are commonly grown, offering a range of flavors for fresh eating, drying, or wine production.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: "4-10",
        matureSize: "50-100 sq ft",
        native: false
    },
    {
        id: 1,
        name: "Thompson's Yucca",
        scientificName: "(Vitis vinifera)",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/vines-1747224_1920.jpg",
        description: "Grape Vines are a popular fruit crop for New Mexico, thriving in the state’s sunny, dry climate. Grapevines need full sun and well-draining, slightly sandy soil to produce high-quality fruit. They are ideal for both home gardeners and commercial growers, particularly in the southern and central regions, where the extended growing season supports their long ripening period. Grapes require regular irrigation, especially during the hot summer months, but they are fairly drought-tolerant once established. Varieties like Concord, Thompson Seedless, and Zinfandel are commonly grown, offering a range of flavors for fresh eating, drying, or wine production.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: "4-10",
        matureSize: "50-100 sq ft",
        native: false
    },

    ],
    agave: [
    {
        id: 1,
        name: "Parry's Agave",
        scientificName: "Agave parryi",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/vines-1747224_1920.jpg",
        description: "Grape Vines are a popular fruit crop for New Mexico, thriving in the state’s sunny, dry climate. Grapevines need full sun and well-draining, slightly sandy soil to produce high-quality fruit. They are ideal for both home gardeners and commercial growers, particularly in the southern and central regions, where the extended growing season supports their long ripening period. Grapes require regular irrigation, especially during the hot summer months, but they are fairly drought-tolerant once established. Varieties like Concord, Thompson Seedless, and Zinfandel are commonly grown, offering a range of flavors for fresh eating, drying, or wine production.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: "4-10",
        matureSize: "50-100 sq ft",
        native: false
    },
    {
        id: 1,
        name: "Century Plant",
        scientificName: "Agave americana",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/vines-1747224_1920.jpg",
        description: "Grape Vines are a popular fruit crop for New Mexico, thriving in the state’s sunny, dry climate. Grapevines need full sun and well-draining, slightly sandy soil to produce high-quality fruit. They are ideal for both home gardeners and commercial growers, particularly in the southern and central regions, where the extended growing season supports their long ripening period. Grapes require regular irrigation, especially during the hot summer months, but they are fairly drought-tolerant once established. Varieties like Concord, Thompson Seedless, and Zinfandel are commonly grown, offering a range of flavors for fresh eating, drying, or wine production.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: "4-10",
        matureSize: "50-100 sq ft",
        native: false
    },
    {
        id: 1,
        name: "Whale's Tongue Agave",
        scientificName: "Agave ovatifolia",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/vines-1747224_1920.jpg",
        description: "Grape Vines are a popular fruit crop for New Mexico, thriving in the state’s sunny, dry climate. Grapevines need full sun and well-draining, slightly sandy soil to produce high-quality fruit. They are ideal for both home gardeners and commercial growers, particularly in the southern and central regions, where the extended growing season supports their long ripening period. Grapes require regular irrigation, especially during the hot summer months, but they are fairly drought-tolerant once established. Varieties like Concord, Thompson Seedless, and Zinfandel are commonly grown, offering a range of flavors for fresh eating, drying, or wine production.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: "4-10",
        matureSize: "50-100 sq ft",
        native: false
    },
    {
        id: 1,
        name: "Artichoke Agave",
        scientificName: "Agave parryi var. truncata",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/vines-1747224_1920.jpg",
        description: "Grape Vines are a popular fruit crop for New Mexico, thriving in the state’s sunny, dry climate. Grapevines need full sun and well-draining, slightly sandy soil to produce high-quality fruit. They are ideal for both home gardeners and commercial growers, particularly in the southern and central regions, where the extended growing season supports their long ripening period. Grapes require regular irrigation, especially during the hot summer months, but they are fairly drought-tolerant once established. Varieties like Concord, Thompson Seedless, and Zinfandel are commonly grown, offering a range of flavors for fresh eating, drying, or wine production.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: "4-10",
        matureSize: "50-100 sq ft",
        native: false
    },
    {
        id: 1,
        name: "Queen Victoria Agave",
        scientificName: "Agave victoriae-reginae",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/vines-1747224_1920.jpg",
        description: "Grape Vines are a popular fruit crop for New Mexico, thriving in the state’s sunny, dry climate. Grapevines need full sun and well-draining, slightly sandy soil to produce high-quality fruit. They are ideal for both home gardeners and commercial growers, particularly in the southern and central regions, where the extended growing season supports their long ripening period. Grapes require regular irrigation, especially during the hot summer months, but they are fairly drought-tolerant once established. Varieties like Concord, Thompson Seedless, and Zinfandel are commonly grown, offering a range of flavors for fresh eating, drying, or wine production.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: "4-10",
        matureSize: "50-100 sq ft",
        native: false
    },
    {
        id: 1,
        name: "Twin-Flower Agave",
        scientificName: "Agave geminiflora",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/vines-1747224_1920.jpg",
        description: "Grape Vines are a popular fruit crop for New Mexico, thriving in the state’s sunny, dry climate. Grapevines need full sun and well-draining, slightly sandy soil to produce high-quality fruit. They are ideal for both home gardeners and commercial growers, particularly in the southern and central regions, where the extended growing season supports their long ripening period. Grapes require regular irrigation, especially during the hot summer months, but they are fairly drought-tolerant once established. Varieties like Concord, Thompson Seedless, and Zinfandel are commonly grown, offering a range of flavors for fresh eating, drying, or wine production.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: "4-10",
        matureSize: "50-100 sq ft",
        native: false
    },

    ],
    


} 

export default cactusdata