const cactusdata =
{
    cactus: [
    {
        id: 1,
        name: "Santa Rita Prickly Pear Cactus",
        scientificName: "Opuntia santa-rita",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/cactus/PRICKLY_PEAR,_SANTA_RITA_(Opuntia_santa-rita)_(5-20-11)_-01_(5741328146).jpg",
        description: "Grape Vines are a popular fruit crop for New Mexico, thriving in the state’s sunny, dry climate. Grapevines need full sun and well-draining, slightly sandy soil to produce high-quality fruit. They are ideal for both home gardeners and commercial growers, particularly in the southern and central regions, where the extended growing season supports their long ripening period. Grapes require regular irrigation, especially during the hot summer months, but they are fairly drought-tolerant once established. Varieties like Concord, Thompson Seedless, and Zinfandel are commonly grown, offering a range of flavors for fresh eating, drying, or wine production.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: "4-10",
        matureSize: "50-100 sq ft",
        native: false
    },
    {
        id: 1,
        name: "Spineless Prickly Pear Cactus",
        scientificName: "(Vitis vinifera)",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/cactus/spineless-pricklypear.jpg",
        description: "Grape Vines are a popular fruit crop for New Mexico, thriving in the state’s sunny, dry climate. Grapevines need full sun and well-draining, slightly sandy soil to produce high-quality fruit. They are ideal for both home gardeners and commercial growers, particularly in the southern and central regions, where the extended growing season supports their long ripening period. Grapes require regular irrigation, especially during the hot summer months, but they are fairly drought-tolerant once established. Varieties like Concord, Thompson Seedless, and Zinfandel are commonly grown, offering a range of flavors for fresh eating, drying, or wine production.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: "4-10",
        matureSize: "50-100 sq ft",
        native: false
    },
    {
        id: 1,
        name: "Engelmann Prickly Pear Cactus",
        scientificName: "(Vitis vinifera)",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/cactus/Engelmann-prickly-pear.jpg",
        description: "Grape Vines are a popular fruit crop for New Mexico, thriving in the state’s sunny, dry climate. Grapevines need full sun and well-draining, slightly sandy soil to produce high-quality fruit. They are ideal for both home gardeners and commercial growers, particularly in the southern and central regions, where the extended growing season supports their long ripening period. Grapes require regular irrigation, especially during the hot summer months, but they are fairly drought-tolerant once established. Varieties like Concord, Thompson Seedless, and Zinfandel are commonly grown, offering a range of flavors for fresh eating, drying, or wine production.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: "4-10",
        matureSize: "50-100 sq ft",
        native: false
    },
    {
        id: 1,
        name: "Teddy Bear Cholla Cactus",
        scientificName: "(Vitis vinifera)",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/cactus/Teddy_Bear_Cholla_(51924224461).jpg",
        description: "Grape Vines are a popular fruit crop for New Mexico, thriving in the state’s sunny, dry climate. Grapevines need full sun and well-draining, slightly sandy soil to produce high-quality fruit. They are ideal for both home gardeners and commercial growers, particularly in the southern and central regions, where the extended growing season supports their long ripening period. Grapes require regular irrigation, especially during the hot summer months, but they are fairly drought-tolerant once established. Varieties like Concord, Thompson Seedless, and Zinfandel are commonly grown, offering a range of flavors for fresh eating, drying, or wine production.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: "4-10",
        matureSize: "50-100 sq ft",
        native: false
    },
    {
        id: 1,
        name: "Cane Cholla Cactus",
        scientificName: "(Vitis vinifera)",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/cactus/cane-cholla.jpg",
        description: "Grape Vines are a popular fruit crop for New Mexico, thriving in the state’s sunny, dry climate. Grapevines need full sun and well-draining, slightly sandy soil to produce high-quality fruit. They are ideal for both home gardeners and commercial growers, particularly in the southern and central regions, where the extended growing season supports their long ripening period. Grapes require regular irrigation, especially during the hot summer months, but they are fairly drought-tolerant once established. Varieties like Concord, Thompson Seedless, and Zinfandel are commonly grown, offering a range of flavors for fresh eating, drying, or wine production.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: "4-10",
        matureSize: "50-100 sq ft",
        native: false
    },
    {
        id: 1,
        name: "Staghorn Cholla Cactus",
        scientificName: "(Vitis vinifera)",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/cactus/staghorn-cholla.jpg",
        description: "Grape Vines are a popular fruit crop for New Mexico, thriving in the state’s sunny, dry climate. Grapevines need full sun and well-draining, slightly sandy soil to produce high-quality fruit. They are ideal for both home gardeners and commercial growers, particularly in the southern and central regions, where the extended growing season supports their long ripening period. Grapes require regular irrigation, especially during the hot summer months, but they are fairly drought-tolerant once established. Varieties like Concord, Thompson Seedless, and Zinfandel are commonly grown, offering a range of flavors for fresh eating, drying, or wine production.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: "4-10",
        matureSize: "50-100 sq ft",
        native: false
    },
    {
        id: 1,
        name: "Golden Barrel Cactus",
        scientificName: "(Vitis vinifera)",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/cactus/cactus-404362_1920.jpg",
        description: "Grape Vines are a popular fruit crop for New Mexico, thriving in the state’s sunny, dry climate. Grapevines need full sun and well-draining, slightly sandy soil to produce high-quality fruit. They are ideal for both home gardeners and commercial growers, particularly in the southern and central regions, where the extended growing season supports their long ripening period. Grapes require regular irrigation, especially during the hot summer months, but they are fairly drought-tolerant once established. Varieties like Concord, Thompson Seedless, and Zinfandel are commonly grown, offering a range of flavors for fresh eating, drying, or wine production.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: "4-10",
        matureSize: "50-100 sq ft",
        native: false
    },
    {
        id: 1,
        name: "Fishhook Barrel Cactus",
        scientificName: "(Vitis vinifera)",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/cactus/fishhook-barrel-cactus-4025082_1920.jpg",
        description: "Grape Vines are a popular fruit crop for New Mexico, thriving in the state’s sunny, dry climate. Grapevines need full sun and well-draining, slightly sandy soil to produce high-quality fruit. They are ideal for both home gardeners and commercial growers, particularly in the southern and central regions, where the extended growing season supports their long ripening period. Grapes require regular irrigation, especially during the hot summer months, but they are fairly drought-tolerant once established. Varieties like Concord, Thompson Seedless, and Zinfandel are commonly grown, offering a range of flavors for fresh eating, drying, or wine production.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: "4-10",
        matureSize: "50-100 sq ft",
        native: false
    },
    {
        id: 1,
        name: "California Barrel Cactus",
        scientificName: "(Vitis vinifera)",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/cactus/california-barrel-cactus-7361420_1920.jpg",
        description: "Grape Vines are a popular fruit crop for New Mexico, thriving in the state’s sunny, dry climate. Grapevines need full sun and well-draining, slightly sandy soil to produce high-quality fruit. They are ideal for both home gardeners and commercial growers, particularly in the southern and central regions, where the extended growing season supports their long ripening period. Grapes require regular irrigation, especially during the hot summer months, but they are fairly drought-tolerant once established. Varieties like Concord, Thompson Seedless, and Zinfandel are commonly grown, offering a range of flavors for fresh eating, drying, or wine production.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: "4-10",
        matureSize: "50-100 sq ft",
        native: false
    },
    {
        id: 1,
        name: "Claret Cup Cactus",
        scientificName: "(Vitis vinifera)",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/cactus/cactus-7793604_1920.jpg",
        description: "Grape Vines are a popular fruit crop for New Mexico, thriving in the state’s sunny, dry climate. Grapevines need full sun and well-draining, slightly sandy soil to produce high-quality fruit. They are ideal for both home gardeners and commercial growers, particularly in the southern and central regions, where the extended growing season supports their long ripening period. Grapes require regular irrigation, especially during the hot summer months, but they are fairly drought-tolerant once established. Varieties like Concord, Thompson Seedless, and Zinfandel are commonly grown, offering a range of flavors for fresh eating, drying, or wine production.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: "4-10",
        matureSize: "50-100 sq ft",
        native: false
    },
    {
        id: 1,
        name: "Strawberry Hedgehog Cactus",
        scientificName: "(Vitis vinifera)",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/cactus/640px-Cactus_Hedgehog_AZ_Blooming_01.jpg",
        description: "Grape Vines are a popular fruit crop for New Mexico, thriving in the state’s sunny, dry climate. Grapevines need full sun and well-draining, slightly sandy soil to produce high-quality fruit. They are ideal for both home gardeners and commercial growers, particularly in the southern and central regions, where the extended growing season supports their long ripening period. Grapes require regular irrigation, especially during the hot summer months, but they are fairly drought-tolerant once established. Varieties like Concord, Thompson Seedless, and Zinfandel are commonly grown, offering a range of flavors for fresh eating, drying, or wine production.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: "4-10",
        matureSize: "50-100 sq ft",
        native: false
    },
    {
        id: 1,
        name: "Texas Rainbow Cactus",
        scientificName: "(Vitis vinifera)",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/cactus/E._dasyacanthus_4.jpg",
        description: "Grape Vines are a popular fruit crop for New Mexico, thriving in the state’s sunny, dry climate. Grapevines need full sun and well-draining, slightly sandy soil to produce high-quality fruit. They are ideal for both home gardeners and commercial growers, particularly in the southern and central regions, where the extended growing season supports their long ripening period. Grapes require regular irrigation, especially during the hot summer months, but they are fairly drought-tolerant once established. Varieties like Concord, Thompson Seedless, and Zinfandel are commonly grown, offering a range of flavors for fresh eating, drying, or wine production.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: "4-10",
        matureSize: "50-100 sq ft",
        native: false
    },
    {
        id: 1,
        name: "Mammillaria Cactus",
        scientificName: "(Vitis vinifera)",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/cactus/mammillaaria-cactus.jpg",
        description: "Grape Vines are a popular fruit crop for New Mexico, thriving in the state’s sunny, dry climate. Grapevines need full sun and well-draining, slightly sandy soil to produce high-quality fruit. They are ideal for both home gardeners and commercial growers, particularly in the southern and central regions, where the extended growing season supports their long ripening period. Grapes require regular irrigation, especially during the hot summer months, but they are fairly drought-tolerant once established. Varieties like Concord, Thompson Seedless, and Zinfandel are commonly grown, offering a range of flavors for fresh eating, drying, or wine production.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: "4-10",
        matureSize: "50-100 sq ft",
        native: false
    },


    ],
    yuccas: [
    {
        id: 1,
        name: "Adam's Needle Yucca",
        scientificName: "(Vitis vinifera)",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/cactus/yucca/adam's-needle.jpg",
        description: "Grape Vines are a popular fruit crop for New Mexico, thriving in the state’s sunny, dry climate. Grapevines need full sun and well-draining, slightly sandy soil to produce high-quality fruit. They are ideal for both home gardeners and commercial growers, particularly in the southern and central regions, where the extended growing season supports their long ripening period. Grapes require regular irrigation, especially during the hot summer months, but they are fairly drought-tolerant once established. Varieties like Concord, Thompson Seedless, and Zinfandel are commonly grown, offering a range of flavors for fresh eating, drying, or wine production.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: "4-10",
        matureSize: "50-100 sq ft",
        native: false
    },
    {
        id: 1,
        name: "Narrow-leaf Yucca",
        scientificName: "(Vitis vinifera)",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/cactus/yucca/narrow-leaf-yucca-in-arizona-3812548_1920.jpg",
        description: "Grape Vines are a popular fruit crop for New Mexico, thriving in the state’s sunny, dry climate. Grapevines need full sun and well-draining, slightly sandy soil to produce high-quality fruit. They are ideal for both home gardeners and commercial growers, particularly in the southern and central regions, where the extended growing season supports their long ripening period. Grapes require regular irrigation, especially during the hot summer months, but they are fairly drought-tolerant once established. Varieties like Concord, Thompson Seedless, and Zinfandel are commonly grown, offering a range of flavors for fresh eating, drying, or wine production.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: "4-10",
        matureSize: "50-100 sq ft",
        native: false
    },
    {
        id: 1,
        name: "Red Yucca",
        scientificName: "(Vitis vinifera)",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/cactus/yucca/red-yucca.jpg",
        description: "Grape Vines are a popular fruit crop for New Mexico, thriving in the state’s sunny, dry climate. Grapevines need full sun and well-draining, slightly sandy soil to produce high-quality fruit. They are ideal for both home gardeners and commercial growers, particularly in the southern and central regions, where the extended growing season supports their long ripening period. Grapes require regular irrigation, especially during the hot summer months, but they are fairly drought-tolerant once established. Varieties like Concord, Thompson Seedless, and Zinfandel are commonly grown, offering a range of flavors for fresh eating, drying, or wine production.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: "4-10",
        matureSize: "50-100 sq ft",
        native: false
    },
    {
        id: 1,
        name: "Navajo Yucca",
        scientificName: "(Vitis vinifera)",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/cactus/yucca/navajo-yucca.jpg",
        description: "Grape Vines are a popular fruit crop for New Mexico, thriving in the state’s sunny, dry climate. Grapevines need full sun and well-draining, slightly sandy soil to produce high-quality fruit. They are ideal for both home gardeners and commercial growers, particularly in the southern and central regions, where the extended growing season supports their long ripening period. Grapes require regular irrigation, especially during the hot summer months, but they are fairly drought-tolerant once established. Varieties like Concord, Thompson Seedless, and Zinfandel are commonly grown, offering a range of flavors for fresh eating, drying, or wine production.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: "4-10",
        matureSize: "50-100 sq ft",
        native: false
    },
    {
        id: 1,
        name: "Soaptree Yucca",
        scientificName: "(Vitis vinifera)",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/cactus/yucca/soaptree-yucca.jpg",
        description: "Grape Vines are a popular fruit crop for New Mexico, thriving in the state’s sunny, dry climate. Grapevines need full sun and well-draining, slightly sandy soil to produce high-quality fruit. They are ideal for both home gardeners and commercial growers, particularly in the southern and central regions, where the extended growing season supports their long ripening period. Grapes require regular irrigation, especially during the hot summer months, but they are fairly drought-tolerant once established. Varieties like Concord, Thompson Seedless, and Zinfandel are commonly grown, offering a range of flavors for fresh eating, drying, or wine production.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: "4-10",
        matureSize: "50-100 sq ft",
        native: false
    },
    {
        id: 1,
        name: "Beaked Yucca",
        scientificName: "Yucca rostrata",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/cactus/yucca/Yucca_rostrata_(beaked_yucca).jpg",
        description: "Grape Vines are a popular fruit crop for New Mexico, thriving in the state’s sunny, dry climate. Grapevines need full sun and well-draining, slightly sandy soil to produce high-quality fruit. They are ideal for both home gardeners and commercial growers, particularly in the southern and central regions, where the extended growing season supports their long ripening period. Grapes require regular irrigation, especially during the hot summer months, but they are fairly drought-tolerant once established. Varieties like Concord, Thompson Seedless, and Zinfandel are commonly grown, offering a range of flavors for fresh eating, drying, or wine production.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: "4-10",
        matureSize: "50-100 sq ft",
        native: false
    },

    ],
    agaves: [
    {
        id: 1,
        name: "Parry's Agave",
        scientificName: "Agave parryi",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/cactus/agave/perry's-agave.jpg",
        description: "Grape Vines are a popular fruit crop for New Mexico, thriving in the state’s sunny, dry climate. Grapevines need full sun and well-draining, slightly sandy soil to produce high-quality fruit. They are ideal for both home gardeners and commercial growers, particularly in the southern and central regions, where the extended growing season supports their long ripening period. Grapes require regular irrigation, especially during the hot summer months, but they are fairly drought-tolerant once established. Varieties like Concord, Thompson Seedless, and Zinfandel are commonly grown, offering a range of flavors for fresh eating, drying, or wine production.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: "4-10",
        matureSize: "50-100 sq ft",
        native: false
    },
    {
        id: 1,
        name: "Century Plant",
        scientificName: "Agave americana",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/cactus/agave/century-plant.jpg",
        description: "Grape Vines are a popular fruit crop for New Mexico, thriving in the state’s sunny, dry climate. Grapevines need full sun and well-draining, slightly sandy soil to produce high-quality fruit. They are ideal for both home gardeners and commercial growers, particularly in the southern and central regions, where the extended growing season supports their long ripening period. Grapes require regular irrigation, especially during the hot summer months, but they are fairly drought-tolerant once established. Varieties like Concord, Thompson Seedless, and Zinfandel are commonly grown, offering a range of flavors for fresh eating, drying, or wine production.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: "4-10",
        matureSize: "50-100 sq ft",
        native: false
    },
    {
        id: 1,
        name: "Whale's Tongue Agave",
        scientificName: "Agave ovatifolia",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/cactus/agave/whale'stongue.jpg",
        description: "Grape Vines are a popular fruit crop for New Mexico, thriving in the state’s sunny, dry climate. Grapevines need full sun and well-draining, slightly sandy soil to produce high-quality fruit. They are ideal for both home gardeners and commercial growers, particularly in the southern and central regions, where the extended growing season supports their long ripening period. Grapes require regular irrigation, especially during the hot summer months, but they are fairly drought-tolerant once established. Varieties like Concord, Thompson Seedless, and Zinfandel are commonly grown, offering a range of flavors for fresh eating, drying, or wine production.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: "4-10",
        matureSize: "50-100 sq ft",
        native: false
    },
    {
        id: 1,
        name: "Twin-Flower Agave",
        scientificName: "Agave geminiflora",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/cactus/agave/Agave_geminiflora_-_Twin-flowered_agave_01-1.jpg",
        description: "Grape Vines are a popular fruit crop for New Mexico, thriving in the state’s sunny, dry climate. Grapevines need full sun and well-draining, slightly sandy soil to produce high-quality fruit. They are ideal for both home gardeners and commercial growers, particularly in the southern and central regions, where the extended growing season supports their long ripening period. Grapes require regular irrigation, especially during the hot summer months, but they are fairly drought-tolerant once established. Varieties like Concord, Thompson Seedless, and Zinfandel are commonly grown, offering a range of flavors for fresh eating, drying, or wine production.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: "4-10",
        matureSize: "50-100 sq ft",
        native: false
    },

    ],
aloes : [
    {
        id: 1,
        name: "Hardy Aloe",
        scientificName: "Aloe maculata",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/vines-1747224_1920.jpg",
        description: "Grape Vines are a popular fruit crop for New Mexico, thriving in the state’s sunny, dry climate. Grapevines need full sun and well-draining, slightly sandy soil to produce high-quality fruit. They are ideal for both home gardeners and commercial growers, particularly in the southern and central regions, where the extended growing season supports their long ripening period. Grapes require regular irrigation, especially during the hot summer months, but they are fairly drought-tolerant once established. Varieties like Concord, Thompson Seedless, and Zinfandel are commonly grown, offering a range of flavors for fresh eating, drying, or wine production.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: "4-10",
        matureSize: "50-100 sq ft",
        native: false
    },
    {
        id: 1,
        name: "Torch Aloe",
        scientificName: "Aloe marlothii",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/vines-1747224_1920.jpg",
        description: "Grape Vines are a popular fruit crop for New Mexico, thriving in the state’s sunny, dry climate. Grapevines need full sun and well-draining, slightly sandy soil to produce high-quality fruit. They are ideal for both home gardeners and commercial growers, particularly in the southern and central regions, where the extended growing season supports their long ripening period. Grapes require regular irrigation, especially during the hot summer months, but they are fairly drought-tolerant once established. Varieties like Concord, Thompson Seedless, and Zinfandel are commonly grown, offering a range of flavors for fresh eating, drying, or wine production.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: "4-10",
        matureSize: "50-100 sq ft",
        native: false
    },
    {
        id: 1,
        name: "Blue Elf Aloe",
        scientificName: "Aloe striata",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/vines-1747224_1920.jpg",
        description: "Grape Vines are a popular fruit crop for New Mexico, thriving in the state’s sunny, dry climate. Grapevines need full sun and well-draining, slightly sandy soil to produce high-quality fruit. They are ideal for both home gardeners and commercial growers, particularly in the southern and central regions, where the extended growing season supports their long ripening period. Grapes require regular irrigation, especially during the hot summer months, but they are fairly drought-tolerant once established. Varieties like Concord, Thompson Seedless, and Zinfandel are commonly grown, offering a range of flavors for fresh eating, drying, or wine production.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: "4-10",
        matureSize: "50-100 sq ft",
        native: false
    },
    {
        id: 1,
        name: "Short leaf Aloe",
        scientificName: "Aloe nobilis",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/vines-1747224_1920.jpg",
        description: "Grape Vines are a popular fruit crop for New Mexico, thriving in the state’s sunny, dry climate. Grapevines need full sun and well-draining, slightly sandy soil to produce high-quality fruit. They are ideal for both home gardeners and commercial growers, particularly in the southern and central regions, where the extended growing season supports their long ripening period. Grapes require regular irrigation, especially during the hot summer months, but they are fairly drought-tolerant once established. Varieties like Concord, Thompson Seedless, and Zinfandel are commonly grown, offering a range of flavors for fresh eating, drying, or wine production.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: "4-10",
        matureSize: "50-100 sq ft",
        native: false
    },
]
    


} 

export default cactusdata