const xerictrees =
{
    shadetrees: [
        {
            id: 35,
            name: "Shoal Creek Chaste Tree",
            scientificName: "Vitex agnus-castus",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/vitex.jpg",
            description: "The Shoal Creek Chaste Tree (Vitex agnus-castus ‘Shoal Creek’) is a heat- and drought-tolerant ornamental tree that thrives in Albuquerque’s arid climate. Growing 10–15 feet tall and wide, it forms a multi-trunked, vase-like shape with fragrant, gray-green foliage. From late spring through summer, it produces showy spikes of violet-blue flowers, attracting pollinators like bees and butterflies. It prefers full sun and well-draining soil, requiring low to moderate water once established.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/rainwater.png",
            waterRequirement: "Xeric",
            hardinessZones: "6-9",
            matureSize: "20' x 20'",
            native: false
          },
          {
            id: 41,
            name: "Chitalpa",
            scientificName: "Chitalpa tashkentensis",
            image: "https://jfschmidt.com/wp-content/uploads/2023/06/chitalpa-nationalarboretum-web-01.jpg",
            description: "Chitalpa is a hybrid tree combining Desert Willow and Catalpa, known for its trumpet-shaped flowers in pink, white, or lavender. Two main varieties exist: ‘Morning Cloud’ and ‘Pink Dawn,’ both were originally thought to descend from southern catalpa, but later discovered they differ in their Catalpa lineage. It has slender, lance-shaped leaves in whorls of three and produces long seed pods. Drought-tolerant and thriving in full sun, it is a great choice for any Albuquerque landscape and even works in xeriscaping.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/rainwater.png",
            waterRequirement: "Xeric",
            hardinessZones: "6-9",
            matureSize: "25' x 25'",
            native: false
          },  
          {
            id: 42,
            name: "Box Elder",
            scientificName: "Prosopis velutina",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/velvetMesquite.jpg",
            description: "The Velvet Mesquite is a hardy, drought-tolerant tree native to the southwestern U.S. It thrives in Full Sun and requires minimal water, often surviving on rainwater alone. The tree’s feathery leaves provide light shade, and it produces long seed pods that were traditionally used as food. Its deep roots help prevent soil erosion, making it ideal for xeric landscaping in Albuquerque.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/rainwater.png",
            waterRequirement: "Xeric",
            hardinessZones: "7-11",
            matureSize: "30' x 35'",
            native: true
          },
          {
            id: 42,
            name: "Velvet Mesquite",
            scientificName: "Prosopis velutina",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/velvetMesquite.jpg",
            description: "The Velvet Mesquite is a hardy, drought-tolerant tree native to the southwestern U.S. It thrives in Full Sun and requires minimal water, often surviving on rainwater alone. The tree’s feathery leaves provide light shade, and it produces long seed pods that were traditionally used as food. Its deep roots help prevent soil erosion, making it ideal for xeric landscaping in Albuquerque.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/rainwater.png",
            waterRequirement: "Xeric",
            hardinessZones: "7-11",
            matureSize: "30' x 35'",
            native: true
          },
          {
            id: 42,
            name: "New Mexico Olive",
            scientificName: "Prosopis velutina",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/velvetMesquite.jpg",
            description: "The Velvet Mesquite is a hardy, drought-tolerant tree native to the southwestern U.S. It thrives in Full Sun and requires minimal water, often surviving on rainwater alone. The tree’s feathery leaves provide light shade, and it produces long seed pods that were traditionally used as food. Its deep roots help prevent soil erosion, making it ideal for xeric landscaping in Albuquerque.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/rainwater.png",
            waterRequirement: "Xeric",
            hardinessZones: "7-11",
            matureSize: "30' x 35'",
            native: true
          },
          {
            id: 42,
            name: "Mexican Blue Palm",
            scientificName: "Prosopis velutina",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/velvetMesquite.jpg",
            description: "The Velvet Mesquite is a hardy, drought-tolerant tree native to the southwestern U.S. It thrives in Full Sun and requires minimal water, often surviving on rainwater alone. The tree’s feathery leaves provide light shade, and it produces long seed pods that were traditionally used as food. Its deep roots help prevent soil erosion, making it ideal for xeric landscaping in Albuquerque.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/rainwater.png",
            waterRequirement: "Xeric",
            hardinessZones: "7-11",
            matureSize: "30' x 35'",
            native: true
          },
          {
            id: 46,
            name: "Japanese Pagoda Tree",
            scientificName: "Styphnolobium japonicum",
            image: "https://jfschmidt.com/wp-content/uploads/2023/01/styphnolobium-millstonejapanese-web-01.jpg",
            description: "The Japanese Pagoda Tree is a graceful tree known for its compound leaves and clusters of creamy-white flowers in late summer. It thrives in full sun is highly resistant to pollution and can withstand colder temperatures, making it a triple threat and a great choice for those residing in Northern New Mexico given its range in temperature resistance. Its distinctive seed pods and drought tolerance add to its appeal.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medLowWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: "4-8",
            matureSize: "40' x 35'",
            native: false
          },
          {
            id: 48,
            name: "Washington Hawthorne",
            scientificName: "Crataegus phaenopyrum",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/washingtonHawthorn.jpg",
            description: "A small, low-branching tree, the Washington Hawthorn serves as a great ornamental tree, but can also develop a dense and dome shaped canopy that can be desireable for small amounts of shade in a pinch. White flowers in the spring transition to beatiful red berries that are coveted by wildlife, as long as they stay clear of its large thorns. This is the most heat tolerant Hawthorn, making it another great choice for an Albuquerque garden.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medLowWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: "4-8",
            matureSize: "25' x 20'",
            native: false
          },
          {
            id: 44,
            name: "Osage Orange",
            scientificName: "Maclura pomifera",
            image: "https://jfschmidt.com/wp-content/uploads/2023/03/maclura-wichita-web-01.jpg",
            description: "The Osage Orange is a tough, drought-resistant tree with dense, thorny branches and large, bumpy green fruit. Once used as a natural fence, it forms an impenetrable barrier. Valued for its strong, decay-resistant wood, it thrives in poor soils and harsh conditions, making it perfect for windbreaks and erosion control. Native to Texas, it is not commonly found in New Mexico but will do well here.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
            waterRequirement: "Low Water",
            hardinessZones: "4-9",
            matureSize: "40' x 40'",
            native: false
          },
          {
          id: 37,
          name: "Western Hackberry",
          scientificName: "Celtis reticulata",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/westernHackberry.jpg",
          description: "The Western Hackberry is a hardy, drought-tolerant tree native to the Southwestern U.S. With rough, gray bark and simple, serrated leaves, it thrives in Albuquerque’s arid climate. This tree can be perfect for xeriscaping as once it is established it requires only small amounts of water and can tolerate poor soils and strong winds. It produces small round fruit that attracts some wildlife.",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: "4-9",
          matureSize: "40' x 30'",
          native: true
        },
        
        {
          id: 38,
          name: "Smoketree",
          scientificName: "Cotinus coggygria",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/smoketree-7737797_1920.jpg",
          description: "The Smoketree is a small tree or shrub with unique, fluffy, smoke-like flower clusters that bloom in late spring to summer. Smoketree foliage is known for its vibrant colors ranging from pink, to purple to green and even red. Perfect for Albuquerque’s dry climate, it thrives in full sun with minimal water once established. Its vibrant autumn color and pollinator-friendly nature make it a favorite in xeriscaping.",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: "5-8",
          matureSize: "15' x 15'",
          native: false
        },
        
        {
          id: 39,
          name: "Golden Rain Tree",
          scientificName: "Koelreuteria paniculata",
          image: "https://jfschmidt.com/wp-content/uploads/2023/03/koelreuteria-goldenrain-web-01.jpg",
          description: "The Golden Rain Tree is known for its striking yellow flowers that bloom in late spring to summer, creating a vibrant canopy. It also produces papery, lantern-like seed pods that add visual interest into fall. Well-suited to Albuquerque’s dry climate, it requires minimal water once established and tolerates various soil types and environmental conditions.",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: "5-9",
          matureSize: "25' x 25'",
          native: false
        },
          

],

    floweringtrees: [
        {
            id: 22,
            name: "Mexican Bird of Paradise",
            scientificName: "Caesalpinia mexicana",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/flowering/bird-of-paradise-bush-3494940_1920.jpg",
            description: "The Mexican Bird of Paradise is an exotic, drought-tolerant plant known for its striking, bird-like flowers in shades of orange and yellow. It thrives in New Mexico’s sunny, dry climate and adds a dramatic flair to gardens with its upright, lush foliage. While it prefers full sun, it’s adaptable to other growing conditions if needed. Jericho recommends using this plant as a xeric tree or shrub to enhance the color in your xeriscaped sections of yard or garden.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/rainwater.png",
            waterRequirement: "Xeric",
            hardinessZones: "7-10",
            matureSize: "10' x 10'",
            native: true
          },
    ],
    coniferoustrees: [
        {
            id: 2,
            name: "Austrian Pine",
            scientificName: "Pinus nigra",
            image: "https://jfschmidt.com/wp-content/uploads/2023/03/pinus-austrian-web-01.jpg",
            description: "Austrian pines are hardy evergreens well-suited to Albuquerque, growing 40 to 60 feet tall and providing excellent windbreaks, shade, and privacy. Their long, dark green needles form a dense canopy that withstands harsh sun and urban conditions. Drought-tolerant once established, they thrive in well-drained soils, making them a low-maintenance choice for adding greenery and structure to the high desert landscape.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
            waterRequirement: "Low Water",
            hardinessZones: "3-8",
            matureSize: "55' x 35'",
            native: false
        },
        {
            id: 2,
            name: "Bristlecone Pine",
            scientificName: "Pinus nigra",
            image: "https://jfschmidt.com/wp-content/uploads/2023/03/pinus-austrian-web-01.jpg",
            description: "Austrian pines are hardy evergreens well-suited to Albuquerque, growing 40 to 60 feet tall and providing excellent windbreaks, shade, and privacy. Their long, dark green needles form a dense canopy that withstands harsh sun and urban conditions. Drought-tolerant once established, they thrive in well-drained soils, making them a low-maintenance choice for adding greenery and structure to the high desert landscape.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
            waterRequirement: "Low Water",
            hardinessZones: "3-8",
            matureSize: "55' x 35'",
            native: false
        },
        {
            id: 2,
            name: "One-Seed Pine",
            scientificName: "Pinus nigra",
            image: "https://jfschmidt.com/wp-content/uploads/2023/03/pinus-austrian-web-01.jpg",
            description: "Austrian pines are hardy evergreens well-suited to Albuquerque, growing 40 to 60 feet tall and providing excellent windbreaks, shade, and privacy. Their long, dark green needles form a dense canopy that withstands harsh sun and urban conditions. Drought-tolerant once established, they thrive in well-drained soils, making them a low-maintenance choice for adding greenery and structure to the high desert landscape.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
            waterRequirement: "Low Water",
            hardinessZones: "3-8",
            matureSize: "55' x 35'",
            native: false
        },
        {
            id: 2,
            name: "Rocky Mountain Juniper",
            scientificName: "Pinus nigra",
            image: "https://jfschmidt.com/wp-content/uploads/2023/03/pinus-austrian-web-01.jpg",
            description: "Austrian pines are hardy evergreens well-suited to Albuquerque, growing 40 to 60 feet tall and providing excellent windbreaks, shade, and privacy. Their long, dark green needles form a dense canopy that withstands harsh sun and urban conditions. Drought-tolerant once established, they thrive in well-drained soils, making them a low-maintenance choice for adding greenery and structure to the high desert landscape.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
            waterRequirement: "Low Water",
            hardinessZones: "3-8",
            matureSize: "55' x 35'",
            native: false
        },
        {
            id: 2,
            name: "Afghan Pine",
            scientificName: "Pinus nigra",
            image: "https://jfschmidt.com/wp-content/uploads/2023/03/pinus-austrian-web-01.jpg",
            description: "Austrian pines are hardy evergreens well-suited to Albuquerque, growing 40 to 60 feet tall and providing excellent windbreaks, shade, and privacy. Their long, dark green needles form a dense canopy that withstands harsh sun and urban conditions. Drought-tolerant once established, they thrive in well-drained soils, making them a low-maintenance choice for adding greenery and structure to the high desert landscape.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
            waterRequirement: "Low Water",
            hardinessZones: "3-8",
            matureSize: "55' x 35'",
            native: false
        },
        {
            id: 2,
            name: "Leyland Cypress",
            scientificName: "Pinus nigra",
            image: "https://jfschmidt.com/wp-content/uploads/2023/03/pinus-austrian-web-01.jpg",
            description: "Austrian pines are hardy evergreens well-suited to Albuquerque, growing 40 to 60 feet tall and providing excellent windbreaks, shade, and privacy. Their long, dark green needles form a dense canopy that withstands harsh sun and urban conditions. Drought-tolerant once established, they thrive in well-drained soils, making them a low-maintenance choice for adding greenery and structure to the high desert landscape.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
            waterRequirement: "Low Water",
            hardinessZones: "3-8",
            matureSize: "55' x 35'",
            native: false
        },
        {
            id: 2,
            name: "Oriental Arborvitae",
            scientificName: "Pinus nigra",
            image: "https://jfschmidt.com/wp-content/uploads/2023/03/pinus-austrian-web-01.jpg",
            description: "Austrian pines are hardy evergreens well-suited to Albuquerque, growing 40 to 60 feet tall and providing excellent windbreaks, shade, and privacy. Their long, dark green needles form a dense canopy that withstands harsh sun and urban conditions. Drought-tolerant once established, they thrive in well-drained soils, making them a low-maintenance choice for adding greenery and structure to the high desert landscape.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
            waterRequirement: "Low Water",
            hardinessZones: "3-8",
            matureSize: "55' x 35'",
            native: false
        },
    ],
    lowtrees: [
        {
        id: 22,
        name: "Goldenball Leadtree",
        scientificName: "Caesalpinia mexicana",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/flowering/bird-of-paradise-bush-3494940_1920.jpg",
        description: "The Mexican Bird of Paradise is an exotic, drought-tolerant plant known for its striking, bird-like flowers in shades of orange and yellow. It thrives in New Mexico’s sunny, dry climate and adds a dramatic flair to gardens with its upright, lush foliage. While it prefers full sun, it’s adaptable to other growing conditions if needed. Jericho recommends using this plant as a xeric tree or shrub to enhance the color in your xeriscaped sections of yard or garden.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/rainwater.png",
        waterRequirement: "Xeric",
        hardinessZones: "7-10",
        matureSize: "10' x 10'",
        native: true
        },
        {
        id: 22,
        name: "Little Walnut",
        scientificName: "Caesalpinia mexicana",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/flowering/bird-of-paradise-bush-3494940_1920.jpg",
        description: "The Mexican Bird of Paradise is an exotic, drought-tolerant plant known for its striking, bird-like flowers in shades of orange and yellow. It thrives in New Mexico’s sunny, dry climate and adds a dramatic flair to gardens with its upright, lush foliage. While it prefers full sun, it’s adaptable to other growing conditions if needed. Jericho recommends using this plant as a xeric tree or shrub to enhance the color in your xeriscaped sections of yard or garden.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/rainwater.png",
        waterRequirement: "Xeric",
        hardinessZones: "7-10",
        matureSize: "10' x 10'",
        native: true
        },
        {
        id: 22,
        name: "Texas Madrone",
        scientificName: "Caesalpinia mexicana",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/flowering/bird-of-paradise-bush-3494940_1920.jpg",
        description: "The Mexican Bird of Paradise is an exotic, drought-tolerant plant known for its striking, bird-like flowers in shades of orange and yellow. It thrives in New Mexico’s sunny, dry climate and adds a dramatic flair to gardens with its upright, lush foliage. While it prefers full sun, it’s adaptable to other growing conditions if needed. Jericho recommends using this plant as a xeric tree or shrub to enhance the color in your xeriscaped sections of yard or garden.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/rainwater.png",
        waterRequirement: "Xeric",
        hardinessZones: "7-10",
        matureSize: "10' x 10'",
        native: true
        },
        {
        id: 22,
        name: "Anacacho Orchid Tree",
        scientificName: "Caesalpinia mexicana",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/flowering/bird-of-paradise-bush-3494940_1920.jpg",
        description: "The Mexican Bird of Paradise is an exotic, drought-tolerant plant known for its striking, bird-like flowers in shades of orange and yellow. It thrives in New Mexico’s sunny, dry climate and adds a dramatic flair to gardens with its upright, lush foliage. While it prefers full sun, it’s adaptable to other growing conditions if needed. Jericho recommends using this plant as a xeric tree or shrub to enhance the color in your xeriscaped sections of yard or garden.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/rainwater.png",
        waterRequirement: "Xeric",
        hardinessZones: "7-10",
        matureSize: "10' x 10'",
        native: true
        },
    ],
}
export default xerictrees