const xerictrees =
{
    shadetrees: [
      {
        id: 43,
        name: "Quaking Aspen",
        scientificName: "Populus tremuloides",
        image: "https://jfschmidt.com/wp-content/uploads/2023/03/populus-quaking-web-01.jpg",
        description: "The Quaking Aspen is a fast-growing tree known for its striking white bark and delicate, fluttering leaves that create a distinctive rustling sound in the wind. It forms large groves of genetically identical trees and turns a brilliant golden yellow in the fall. While tolerant of dry conditions, it prefers moist soils and is best suited for higher elevations.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
        waterRequirement: "Low Water",
        hardinessZones: "1-7",
        matureSize: "50' x 30'",
        native: true
      },
   
      {
        id: 19,
        name: "Boxelder Maple",
        scientificName: "Acer negundo",
        image: "https://jfschmidt.com/wp-content/uploads/2023/03/acer-sensationbox-web-01.jpg",
        description: "The Boxelder Maple is a fast-growing, medium-sized tree native to North America. It is known for its compound leaves, which are made up of several leaflets, giving it a unique appearance compared to other maples. Boxelders are hardy and adaptable, thriving in a variety of soil types and climates, though they are often considered short-lived compared to other maple species.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
        waterRequirement: "Low Water",
        hardinessZones: "2-9",
        matureSize: "40' x 40'",
        native: true
      },

          {
            id: 42,
            name: "Velvet Mesquite",
            scientificName: "Prosopis velutina",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/velvetMesquite.jpg",
            description: "The Velvet Mesquite is a hardy, drought-tolerant tree native to the southwestern U.S. It thrives in Full Sun and requires minimal water, often surviving on rainwater alone. The tree’s feathery leaves provide light shade, and it produces long seed pods that were traditionally used as food. Its deep roots help prevent soil erosion, making it ideal for xeric landscaping in Albuquerque.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
            waterRequirement: "Low Water",
            hardinessZones: "7-11",
            matureSize: "30' x 35'",
            native: true
          },
          {
            id: 13,
            name: "Lacebark Elm",
            scientificName: "Ulmus parvifolia",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/lacebarkElm.JPG",
            description: "The Lacebark Elm is a medium-sized deciduous tree known for its unique and striking bark, which peels off in patches, revealing a camouflage of gray, green, and white. The tree has an upright, symmetrical shape and small, dark green leaves that turn yellow in the fall. It is highly resistant to diseases such as Dutch elm disease and is a popular ornamental tree for urban areas. Sometimes known as a Chinese Elm, this is not the same invasive Siberian Elm that many Albuquerque residents consider problematic.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
            waterRequirement: "Low Water",
            hardinessZones: "5-9",
            matureSize: "35' x 30'",
            native: false
          },
          {
            id: 12,
            name: "Frontier Elm",
            scientificName: "Ulmus 'Frontier'",
            image: "https://jfschmidt.com/wp-content/uploads/2023/03/ulmus-frontier-web-01.jpg",
            description: "The Frontier Elm is a moderate-sized, drought-tolerant tree well-suited to Albuquerque’s dry climate. Reaching 30–40 feet tall with a vase-like canopy, it provides ample shade while fitting into urban landscapes. Unlike many elms, it offers brilliant red to burgundy fall color, adding seasonal interest to the city’s greenery. With strong resistance to Dutch Elm Disease and Elm Leaf Beetles, the Frontier Elm is a low-maintenance, hardy choice for streets, yards, and parks in Albuquerque and other New Mexico areas.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
            waterRequirement: "Low Water",
            hardinessZones: "6-9",
            matureSize: "40' x 30'",
            native: true
          },
          {
            id: 36,
            name: "Chinese Pistache",
            scientificName: "Pistacia chinensis",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/chinesePistache.jpg",
            description: "The Chinese Pistache is a small to medium-sized tree known for its vibrant fall colors, ranging from yellow to red to purple. Chinese Pistache has a unique narrow leaf shape making it easily distinguishable from other trees. It thrives in Albuquerque’s dry climate, flourishing in full sun and tolerating moderate drought once established. Its rounded canopy provides excellent shade, making it a popular choice for urban streetscapes and parks.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
            waterRequirement: "Low Water",
            hardinessZones: "6-9",
            matureSize: "30' x 25'",
            native: false
          },
          {
            id: 42,
            name: "Mexican Blue Palm",
            scientificName: "Brahea armata",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/trees/mexican-blue-palm.jpg",
            description: "Mexican blue palm is a striking, drought-tolerant palm that thrives in New Mexico’s dry climate. Its silvery-blue, fan-shaped fronds provide a bold, architectural look, making it a standout in xeriscapes and desert gardens. This slow-growing palm prefers full sun and well-draining soil, requiring minimal water once established. Hardy to cold and heat, the Mexican blue palm is a low-maintenance choice that adds a touch of the tropics to arid landscapes.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
            waterRequirement: "Low Water",
            hardinessZones: "7-11",
            matureSize: "30' x 35'",
            native: true
          },
          {
            id: 48,
            name: "Washington Hawthorne",
            scientificName: "Crataegus phaenopyrum",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/washingtonHawthorn.jpg",
            description: "A small, low-branching tree, the Washington Hawthorn serves as a great ornamental tree, but can also develop a dense and dome shaped canopy that can be desireable for small amounts of shade in a pinch. White flowers in the spring transition to beatiful red berries that are coveted by wildlife, as long as they stay clear of its large thorns. This is the most heat tolerant Hawthorn, making it another great choice for an Albuquerque garden.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
            waterRequirement: "Low Water",
            hardinessZones: "4-8",
            matureSize: "25' x 20'",
            native: false
          },
          {
            id: 44,
            name: "Osage Orange",
            scientificName: "Maclura pomifera",
            image: "https://jfschmidt.com/wp-content/uploads/2023/03/maclura-wichita-web-01.jpg",
            description: "The Osage Orange is a tough, drought-resistant tree with dense, thorny branches and large, bumpy green fruit. Once used as a natural fence, it forms an impenetrable barrier. Valued for its strong, decay-resistant wood, it thrives in poor soils and harsh conditions, making it perfect for windbreaks and erosion control. Native to Texas, it is not commonly found in New Mexico but will do well here.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
            waterRequirement: "Low Water",
            hardinessZones: "4-9",
            matureSize: "40' x 40'",
            native: false
          },
          {
          id: 37,
          name: "Western Hackberry",
          scientificName: "Celtis reticulata",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/westernHackberry.jpg",
          description: "The Western Hackberry is a hardy, drought-tolerant tree native to the Southwestern U.S. With rough, gray bark and simple, serrated leaves, it thrives in Albuquerque’s arid climate. This tree can be perfect for xeriscaping as once it is established it requires only small amounts of water and can tolerate poor soils and strong winds. It produces small round fruit that attracts some wildlife.",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
          waterRequirement: "Low Water",
          hardinessZones: "4-9",
          matureSize: "40' x 30'",
          native: true
        },
        
        {
          id: 38,
          name: "Smoketree",
          scientificName: "Cotinus coggygria",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/smoketree-7737797_1920.jpg",
          description: "The Smoketree is a small tree or shrub with unique, fluffy, smoke-like flower clusters that bloom in late spring to summer. Smoketree foliage is known for its vibrant colors ranging from pink, to purple to green and even red. Perfect for Albuquerque’s dry climate, it thrives in full sun with minimal water once established. Its vibrant autumn color and pollinator-friendly nature make it a favorite in xeriscaping.",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
          waterRequirement: "Low Water",
          hardinessZones: "5-8",
          matureSize: "15' x 15'",
          native: false
        },       
        {
          id: 39,
          name: "Golden Rain Tree",
          scientificName: "Koelreuteria paniculata",
          image: "https://jfschmidt.com/wp-content/uploads/2023/03/koelreuteria-goldenrain-web-01.jpg",
          description: "The Golden Rain Tree is known for its striking yellow flowers that bloom in late spring to summer, creating a vibrant canopy. It also produces papery, lantern-like seed pods that add visual interest into fall. Well-suited to Albuquerque’s dry climate, it requires minimal water once established and tolerates various soil types and environmental conditions.",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
          waterRequirement: "Low Water",
          hardinessZones: "5-9",
          matureSize: "25' x 25'",
          native: false
        },
        {
          id: 22,
          name: "Goldenball Leadtree",
          scientificName: "Leucaena retusa",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/trees/goldenball-leadtree.jpg",
          description: "Goldenball leadtree is a hardy, drought-tolerant tree perfect for New Mexico’s arid climate. This fast-growing native features delicate, fern-like foliage and bright yellow, globe-shaped flowers that bloom from spring to fall, attracting pollinators. It thrives in full sun and well-draining soil, requiring little water once established. With its airy canopy and low maintenance needs, goldenball leadtree is an excellent choice for xeriscaping, providing light shade and seasonal color.",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
          waterRequirement: "Low Water",
          hardinessZones: "7-10",
          matureSize: "10' x 10'",
          native: true
          },
          {
          id: 22,
          name: "Texas Madrone",
          scientificName: "Arbutus xalapensis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/trees/Texas_madrone_tree_arbutus_xalapensis.jpg",
          description: "Texas madrone is a striking, drought-tolerant tree well-suited for New Mexico’s arid landscapes. Known for its smooth, peeling bark in shades of red and orange, it adds year-round visual interest. This slow-growing evergreen thrives in well-draining, rocky soil and full sun to partial shade, requiring minimal water once established. In spring, it produces clusters of white, bell-shaped flowers that attract pollinators, followed by small, red berries enjoyed by birds. With its unique beauty and resilience, Texas madrone is a valuable addition to xeriscapes and native gardens.",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
          waterRequirement: "Low Water",
          hardinessZones: "7-10",
          matureSize: "10' x 10'",
          native: true
          },
          

],

    floweringtrees: [
      {
        id: 46,
        name: "Japanese Pagoda Tree",
        scientificName: "Styphnolobium japonicum",
        image: "https://jfschmidt.com/wp-content/uploads/2023/01/styphnolobium-millstonejapanese-web-01.jpg",
        description: "The Japanese Pagoda Tree is a graceful tree known for its compound leaves and clusters of creamy-white flowers in late summer. It thrives in full sun is highly resistant to pollution and can withstand colder temperatures, making it a triple threat and a great choice for those residing in Northern New Mexico given its range in temperature resistance. Its distinctive seed pods and drought tolerance add to its appeal.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
        waterRequirement: "Low Water",
        hardinessZones: "4-8",
        matureSize: "40' x 35'",
        native: false
      },
        {
            id: 22,
            name: "Mexican Bird of Paradise",
            scientificName: "Caesalpinia mexicana",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/flowering/bird-of-paradise-bush-3494940_1920.jpg",
            description: "The Mexican Bird of Paradise is an exotic, drought-tolerant plant known for its striking, bird-like flowers in shades of orange and yellow. It thrives in New Mexico’s sunny, dry climate and adds a dramatic flair to gardens with its upright, lush foliage. While it prefers full sun, it’s adaptable to other growing conditions if needed. Jericho recommends using this plant as a xeric tree or shrub to enhance the color in your xeriscaped sections of yard or garden.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
            waterRequirement: "Low Water",
            hardinessZones: "7-10",
            matureSize: "10' x 10'",
            native: true
          },
          {
            id: 23,
            name: "Wonderful Pomegranates",
            scientificName: "Punica granatum 'Wonderful'",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/fruit/pomegranate-2825556_1920.jpg",
            description: "The Wonderful Pomegranate tree is the most popular variety for New Mexico gardeners, known for its large, vibrant red fruit with sweet-tart arils. It thrives in New Mexico’s sunny, dry climate and requires full sun, well-draining soil, and deep watering. Pomegranates are drought-tolerant once established but perform best with consistent moisture during the growing season. The Wonderful variety is heat-tolerant and hardy enough for the state’s warmer regions, making it an excellent choice for home orchards.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
            waterRequirement: "Low Water",
            hardinessZones: "7-10",
            matureSize: "10' x 7'",
            native: false
          },
          {
            id: 35,
            name: "Shoal Creek Chaste Tree",
            scientificName: "Vitex agnus-castus",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/vitex.jpg",
            description: "The Shoal Creek Chaste Tree (Vitex agnus-castus ‘Shoal Creek’) is a heat- and drought-tolerant ornamental tree that thrives in Albuquerque’s arid climate. Growing 10–15 feet tall and wide, it forms a multi-trunked, vase-like shape with fragrant, gray-green foliage. From late spring through summer, it produces showy spikes of violet-blue flowers, attracting pollinators like bees and butterflies. It prefers full sun and well-draining soil, requiring low to moderate water once established.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
            waterRequirement: "Low Water",
            hardinessZones: "6-9",
            matureSize: "20' x 20'",
            native: false
          },
          {
            id: 27,
            name: "Chitalpa",
            scientificName: "Chitalpa tashkentensis",
            image: "https://jfschmidt.com/wp-content/uploads/2023/06/chitalpa-nationalarboretum-web-01.jpg",
            description: "Chitalpa is a hybrid tree combining Desert Willow and Catalpa, known for its trumpet-shaped flowers in pink, white, or lavender. Two main varieties exist: ‘Morning Cloud’ and ‘Pink Dawn,’ both were originally thought to descend from southern catalpa, but later discovered they differ in their Catalpa lineage. It has slender, lance-shaped leaves in whorls of three and produces long seed pods. Drought-tolerant and thriving in full sun, it is a great choice for any Albuquerque landscape and even works in xeriscaping.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
            waterRequirement: "Low Water",
            hardinessZones: "6-9",
            matureSize: "25' x 25'",
            native: false
          },
          {
            id: 28,
            name: "Autumn Brillance Serviceberry",
            scientificName: "Amelanchier × grandiflora 'Autumn Brilliance",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/flowering/serviceberry2.jpg",
            description: "The Autumn Brilliance Serviceberry is a small, multi-season tree prized for its white spring blossoms, edible summer berries, and brilliant red-orange fall foliage. In early spring, it blooms with clusters of fragrant white flowers, followed by sweet, blueberry-like fruits that attract birds. Adaptable and low-maintenance, it thrives in various soils and resists pests and diseases, making it an excellent choice for home gardens and naturalized plantings. Jericho Nursery recommends this to anyone looking to add a unique tree to their yard or garden that also harbors and attracts wildlife.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
            waterRequirement: "Low Water",
            hardinessZones: "6-9",
            matureSize: "20' x 15'",
            native: false
          },
          {
            id: 20,
            name: "Oklahoma Redbud",
            scientificName: "Cercis reniformis 'Oklahoma'",
            image: "https://jfschmidt.com/wp-content/uploads/2023/03/cercis-oklahoma-web-01.jpg",
            description: "Like all redbuds on this list, the Oklahoma Redbud is a hardy, drought-tolerant tree with striking purple-pink blossoms that appear in early spring, offering a vibrant contrast against the desert backdrop. Its ability to withstand the hot, dry conditions of New Mexico makes it ideal for planting anywhere from the NE heights to the South Valley, where it thrives in full sun and requires moderate watering. This might be our best-selling redbud tree at Jericho Nursery. Its compact size, along with its stunning flowers, makes it a fantastic choice for smaller yards or urban landscapes across New Mexico.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/PartSun.png",
            sunRequirement: "Partial Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
            waterRequirement: "Low Water",
            hardinessZones: "6-9",
            matureSize: "20' x 25'",
            native: false
        },
          {
            id: 2,
            name: "Chanticlear Pear",
            scientificName: "Pyrus calleryana",
            image: "https://jfschmidt.com/wp-content/uploads/2023/03/pyrus-chanticleer-web-01.jpg",
            description: "Chanticlear Pears are small to medium-sized trees with showy white blossoms in the spring and vibrant fall colors. While similar to other ornamental pear varieties, they are more resistant to diseases like fire blight. It thrives in full sun and well-drained soil, making it suitable for Albuquerque’s dry climate. Although drought-tolerant once established, it may benefit from occasional deep watering during extended dry spells, particularly during summer heat. Its compact size and attractive shape make it ideal for urban landscapes and smaller yards.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
            waterRequirement: "Low Water",
            hardinessZones: "4-8",
            matureSize: "30' x 15'",
            native: false
        },
        {
          id: 8,
          name: "Canada Red Chokecherry",
          scientificName: "Prunus virginiana 'Canada Red'",
          image: "https://jfschmidt.com/wp-content/uploads/2023/03/prunus-canadaredimproved-web-02.jpg",
          description: "The Canada Chokecherry is a native deciduous shrub or small tree commonly found in North America, known for its attractive appearance and wildlife value. It's standout characteristic has to be its purple leaves that emerge as green and slowly turn purple as they age. In late spring, it produces fragrant clusters of white flowers. The Canada Chokecherry is well-suited to Albuquerque’s climate, thriving in full sun and tolerating a range of soil types, including the region’s dry, alkaline soils. ",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
            waterRequirement: "Low Water",
          hardinessZones: "6-9",
          matureSize: "15' x 20'",
          native: true
        },
        {
          id: 16,
          name: "Indian Magic Crabapple",
          scientificName: "Malus 'Indian Magic'",
          image: "https://jfschmidt.com/wp-content/uploads/2023/03/malus-indianmagic-web-01.jpg",
          description: "Indian Magic Crabapple is the more drought tolerant crabapple on this list, making it a great choice for New Mexico gardeners. Known for its stellar fall colors and fruits that start bright red and change to a golden orange throughout the year, this crabapple would be perfect for a splash of color in any yard. Just watch out as their fruits are toxic to dogs, cats and other pets, which is somewhat typical for crabapples. Find the Indian Magic Crabapple here at Jericho Nursery while its still in stock.",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
          waterRequirement: "Low Water",
          hardinessZones: "4-8",
          matureSize: "15' x 15'",
          native: false
      },

      
    ],
    coniferoustrees: [
      {
        id: 2,
        name: "Austrian Pine",
        scientificName: "Pinus nigra",
        image: "https://jfschmidt.com/wp-content/uploads/2023/03/pinus-austrian-web-01.jpg",
        description: "Austrian pines are hardy evergreens well-suited to Albuquerque, growing 40 to 60 feet tall and providing excellent windbreaks, shade, and privacy. Their long, dark green needles form a dense canopy that withstands harsh sun and urban conditions. Drought-tolerant once established, they thrive in well-drained soils, making them a low-maintenance choice for adding greenery and structure to the high desert landscape.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
            waterRequirement: "Low Water",
        hardinessZones: "3-8",
        matureSize: "55' x 35'",
        native: false
      },
      {
        id: 1,
        name: "Pinyon Pine",
        scientificName: "Pinus edulis",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Pinon.jpg",
        description: "Pinyon pines are a staple of New Mexico’s landscape and culture, prized for their rich, buttery piñon nuts harvested for generations. Native to the Four Corners region, these hardy evergreens thrive in the high desert with minimal water, making them ideal for xeriscaping. Their rounded canopies and dense foliage provide year-round greenery, shade, and privacy, while deep roots help stabilize soil. From Farmington to Las Cruces, the pinyon pine remains a cherished symbol of the state’s rugged beauty and resilience.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
        waterRequirement: "Low Water",
        hardinessZones: "4-8",
        matureSize: "20' x 25'",
        native: true
      },
      {
        id: 7,
        name: "Rocky Mountain Juniper",
        scientificName: "Juniperus scopulorum",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/rockmtnJuniper.jpg",
        description: "Following the mountain range down from Colorado, Rocky Mountain junipers are hardy evergreens that flourish in Albuquerque’s high desert. With their dense, blue-green foliage and distinctive, twisted branches, they offer a rugged, picturesque presence in any landscape. Known for their resilience, these junipers thrive in poor soils, intense sun, and low water conditions, making them an excellent choice for xeriscaping. Their small, berry-like cones attract wildlife, while their deep roots help stabilize soil, making them a practical and visually appealing addition to New Mexico’s rugged terrain.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
        waterRequirement: "Low Water",
        hardinessZones: "3-7",
        matureSize: "30' x 10'",
        native: true
      },
      {
        id: 8,
        name: "One Seed Juniper",
        scientificName: "Juniperus monosperma",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/oneseedJuniper.jpg",
        description: "One-seed junipers, also known as the New Mexico Juniper, are tough, drought-tolerant evergreens native to the high desert of New Mexico. Preferring higher altitudes, this resilient tree is found in limited areas outside of the state. With its bushy, upright form that grows from the ground up, the One-seed juniper offers a unique, striking shape that adds character to any yard or landscape. Well-suited for Albuquerque's intense sun, poor soils, and minimal water, it is an ideal choice for xeriscaping.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
        waterRequirement: "Low Water",
        hardinessZones: "4-8",
        matureSize: "15' x 10'",
        native: true
      },
      {
        id: 6,
        name: "Utah Juniper",
        scientificName: "Juniperus osteosperma",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/utahJuniper.jpg",
        description: "Utah junipers are rugged, drought-tolerant evergreens that thrive in Albuquerque’s harsh high desert. With their gnarly, twisted, and irregular growth, they stand out with dense, gray-green foliage and small, berry-like cones. These trees feature thick, woody trunks and branches, resilient to poor soils, intense sun, and minimal water. Often seen growing seemingly straight through rocks and mountainsides, Utah junipers create a striking spectacle, their enduring presence adding a dramatic touch to the landscape.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
        waterRequirement: "Low Water",
        hardinessZones: "4-9",
        matureSize: "20' x 20'",
        native: true
      },
      {
        id: 3,
        name: "Afghan Pine",
        scientificName: "Pinus eldarica",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/pine-tree-6902428_1920.jpg",
        description: "Afghan pines are fast-growing evergreens that thrive in Albuquerque’s arid climate, reaching 30 to 60 feet tall. Native to the Middle East and Central Asia, they feature long, slender needles and a pyramidal shape, making them a popular choice for windbreaks, shade, and landscaping. Highly drought-tolerant once established, Afghan pines adapt well to poor soils and intense sun, requiring minimal maintenance.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
        waterRequirement: "Low Water",
        hardinessZones: "6-10",
        matureSize: "55' x 25'",
        native: false
      },
      {
        id: 14,
        name: "Arizona Cypress",
        scientificName: "Hesperocyparis arizonica",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/arizonaCypress.jpeg",
        description: "The Arizona Cypress is a hardy, drought-tolerant evergreen that thrives in Albuquerque’s dry climate, offering a fast-growing option for windbreaks, privacy screens, or specimen plantings. It requires full sun and well-draining soil, with low to moderate water needs once established. More cold-hardy than Italian Cypress, it has a distinctive blue-green color and dense foliage that provides excellent coverage. Resistant to pests and deer, this low-maintenance tree is perfect for adding year-round texture and resilience to Albuquerque landscapes.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
        waterRequirement: "Low Water",
        hardinessZones: "7-11",
        matureSize: "50' x 15'",
        native: true
      },
      {
        id: 16,
        name: "Leyland Cypress",
        scientificName: "Cupressocyparis leylandii",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/randomCypress.jpg",
        description: "The Leyland Cypress is a fast-growing evergreen prized for its dense, feathery foliage and rapid growth, making it a top choice for windbreaks and privacy screens. While highly adaptable, it benefits from occasional pruning to maintain its shape and prevent overcrowding. Though not as drought-hardy as some native species, it establishes quickly and provides lush, year-round greenery, making it a popular option for Southwestern landscapes.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
            waterRequirement: "Low Water",
        hardinessZones: "6-10",
        matureSize: "50' x 20'",
        native: false
      },

    ],
    lowtrees: [
    
  
    ],
}
export default xerictrees