const xericshrubs =
{
    broadleafs: [
          {
      id: 1,
      name: "Algerita",
      scientificName: "Berberis trifoliolata",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/deciduous/640px-Berberis_trifoliolata_berries.jpg",
      description: "Algerita is a hardy, evergreen shrub native to the southwestern United States, including New Mexico. It is characterized by its spiny, dark green leaves and small yellow flowers that bloom in early spring, followed by bright red berries in the fall. Algerita thrives in dry, rocky soil and is highly drought-tolerant once established, making it ideal for low-maintenance landscapes or xeriscaping. Its compact, rounded form makes it a great choice for borders, hedges, or wildlife-friendly plantings. Mulching can help retain moisture and protect the roots during extreme temperatures.",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
      waterRequirement: "Low Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "15' x 30'",
      native: true
  },
        {
            id: 35,
            name: "Turpentine Bush",
            scientificName: "Ericameria laricifolia",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/shrubs/turpentinebush.JPG",
            description: "Turpentine bush is a tough, drought-tolerant shrub native to the southwestern U.S. and northern Mexico. It grows up to three feet tall and wide, with fine, aromatic green leaves and bright yellow flowers in late summer and fall. Loved by pollinators, it thrives in poor, rocky soils with little water, making it perfect for xeric landscapes and erosion control.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/rainwater.png",
            waterRequirement: "Xeric",
            hardinessZones: "6-9",
            matureSize: "20' x 20'",
            native: false
          },
          {
            id: 1,
            name: "Curl-leaf Mountain Mahogany",
            scientificName: "Cercocarpus ledifolius",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/deciduous/Cercocarpus_ledifolius_8219.jpg",
            description: "The Curl-leaf Mountain Mahogany is a hardy, evergreen shrub that thrives in New Mexico’s arid conditions. Known for its distinctive twisting, leathery leaves and silvery-gray foliage, it provides year-round interest, especially during the winter months. This drought-tolerant shrub offers beautiful, fluffy seed tails that add texture to the landscape. Ideal for low-maintenance, xeriscape gardens, it works well in rocky, well-drained soils and full sun, making it perfect for those seeking a rugged yet attractive plant for dry landscapes.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
            waterRequirement: "Low Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "15' x 30'",
          },
          {
            id: 1,
            name: "Alderleaf Mountain Mahogany",
            scientificName: "Cercocarpus Montanus",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/deciduous/Cercocarpus_montanus_kz07.jpg",
            description: "Alderleaf Mountain Mahogany is a deciduous shrub that adds texture and structure to New Mexico gardens with its oval, dark green leaves and silky, feathery seed heads. This variety thrives in well-drained soils and full sun, offering both wildlife value and low-maintenance beauty. Its dense, upright form provides great wind protection and erosion control, making it a great choice for slopes or challenging landscapes. Alderleaf is highly drought-tolerant once established, making it well-suited to the dry, high-desert environment.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
            waterRequirement: "Low Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "15' x 30'",
          },

          {
            id: 1,
            name: "Hairy Mountain Mahogany",
            scientificName: "CCercocarpus breviflorus",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/deciduous/hairy-mountain-mahogany.jpg",
            description: "Hair Mountain Mahogany is a small, evergreen shrub that thrives in harsh, dry conditions. Known for its smooth, dark green leaves and hair-like seed tails that add elegance to the plant, it can grow as a shrub or small tree. This variety is perfect for xeriscape landscapes in New Mexico, requiring little water once established. Its hardy nature makes it ideal for slopes, dry hillsides, and rocky terrain. Hair Mountain Mahogany is also valued for its windbreak potential and wildlife habitat benefits.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
            waterRequirement: "Low Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "15' x 30'",
          },
          {
            id: 1,
            name: "Pyrenees Cotoneaster",
            scientificName: "Cotoneaster serotinus",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/deciduous/cotoneaster-4506645_1920.jpg",
            description: "Pyrenees Cotoneaster is a sprawling, low-growing shrub that offers year-round interest with its small, glossy green leaves and bright red berries in fall. It’s an excellent choice for ground cover, slopes, or low-maintenance hedges, where its dense foliage can help prevent erosion. This hardy shrub is drought-tolerant once established, and a layer of mulch can help retain moisture in New Mexico’s dry conditions.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
            waterRequirement: "Low Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "15' x 30'",
          },
        {
            id: 1,
            name: "Willowleaf Cotoneaster",
            scientificName: "Cotoneaster salicifolius",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/deciduous/willowleaf-cotoneaster.jpg",
            description: "Willowleaf Cotoneaster is a spreading, evergreen shrub with narrow, willow-like leaves that provide an elegant, airy texture. Its white flowers in spring give way to clusters of red berries in fall, which attract birds. This low-maintenance shrub works well as a ground cover, border, or trailing plant, and mulching around its base helps maintain moisture and protect the roots.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
            waterRequirement: "Low Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "15' x 30'",
          },
          {
            id: 1,
            name: "Pyracantha",
            scientificName: "Pyracantha coccinea",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/deciduous/firethorn-5758151_1920.jpg",
            description: "Pyracantha, commonly known as firethorn, is a vigorous, evergreen shrub with spiny branches and dense foliage. It produces clusters of white flowers in the spring, followed by vibrant red, orange, or yellow berries in the fall that attract birds. This hardy shrub can be used for hedges, screens, or as a cascading ground cover. It thrives in full sun and well-drained soil, and once established, it’s drought-tolerant. Pyracantha also benefits from occasional pruning to maintain its shape and encourage better flowering and berry production. Mulching around the base helps conserve moisture and protect roots from extreme temperatures.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
            waterRequirement: "Low Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "15' x 30'",
          },
  
        ],
    flowering: [
      {
        id: 1,
        name: "Black Knight Butterfly Bush",
        scientificName: "Buddleia davidii 'Black Knight'",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flower/butterflybush-dark-purple.jpg",
        description: "With its deep purple, almost velvety blooms, Black Knight is one of the most striking butterfly bushes for New Mexico gardens. Its rich color contrasts beautifully with desert landscapes, and its long, fragrant flower spikes attract butterflies, hummingbirds, and bees all season. This fast-growing shrub benefits from occasional pruning to maintain shape and encourage fresh blooms, making it a bold yet low-maintenance addition to pollinator-friendly gardens and one of Jericho Nursery's best sellers.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30'",
      },
      {
        id: 1,
        name: "Autumn Sage",
        scientificName: "Salvia greggii",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flower/autumn-sage.jpg",
        description: "Autumn Sage is a hardy, drought-tolerant perennial perfect for New Mexico gardens. Blooming from spring to fall, it produces vibrant red, pink, or purple flowers that attract hummingbirds and pollinators. Thriving in full sun and well-drained soil, it requires minimal water once established. Its aromatic foliage and compact growth make it ideal for borders, xeriscapes, or wildlife gardens, adding long-lasting color to the landscape.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30'",
      },
        {
            id: 35,
            name: "Golden Yarrow",
            scientificName: "Vitex agnus-castus",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/shrubs/yarrow.jpg",
            description: "The Shoal Creek Chaste Tree (Vitex agnus-castus ‘Shoal Creek’) is a heat- and drought-tolerant ornamental tree that thrives in Albuquerque’s arid climate. Growing 10–15 feet tall and wide, it forms a multi-trunked, vase-like shape with fragrant, gray-green foliage. From late spring through summer, it produces showy spikes of violet-blue flowers, attracting pollinators like bees and butterflies. It prefers full sun and well-draining soil, requiring low to moderate water once established.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/rainwater.png",
            waterRequirement: "Xeric",
            hardinessZones: "6-9",
            matureSize: "20' x 20'",
            native: false
          },
          {
            id: 7,
            name: "Goldfinger Potentilla",
            scientificName: "Potentilla fruticosa 'Goldfinger'",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flower/potentilla.jpg",
            description: "Goldfinger Potentilla offers a stunning display of bright yellow flowers from spring to fall, making it a standout in New Mexico gardens and one of our favorites here at Jericho Nursery. This low-growing shrub has a compact, rounded shape and fine-textured, gray-green foliage that complements its vibrant blooms. Highly drought-tolerant once established and resistant to pests, it requires minimal maintenance beyond occasional pruning, making it an excellent choice for colorful borders or low-maintenance landscaping in arid climates.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
            waterRequirement: "Low Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "15' x 30'",
          },
          {
            id: 1,
            name: "Compact Texas Sage",
            scientificName: "Leucophyllum frutescens 'Compacta'",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flower/purple-texas-sage.jpg",
            description: "Compact Texas Sage is a hardy, drought-tolerant shrub perfect for New Mexico’s arid climate. It thrives in full sun with well-drained soil, requiring little water once established. Its silvery-green foliage contrasts beautifully with its vibrant purple flowers, which bloom after summer rains and attract pollinators. With a dense, rounded form, it’s ideal for low-maintenance hedges, borders, or xeriscapes, adding year-round interest to the landscape.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
            waterRequirement: "Low Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "15' x 30'",
          },
          {
            id: 22,
            name: "Mexican Bird of Paradise",
            scientificName: "Caesalpinia mexicana",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/flowering/bird-of-paradise-bush-3494940_1920.jpg",
            description: "The Mexican Bird of Paradise is an exotic, drought-tolerant plant known for its striking, bird-like flowers in shades of orange and yellow. It thrives in New Mexico’s sunny, dry climate and adds a dramatic flair to gardens with its upright, lush foliage. While it prefers full sun, it’s adaptable to other growing conditions if needed. Jericho recommends using this plant as a xeric tree or shrub to enhance the color in your xeriscaped sections of yard or garden.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/rainwater.png",
            waterRequirement: "Xeric",
            hardinessZones: "7-10",
            matureSize: "10' x 10'",
            native: true
          },
        {
            id: 35,
            name: "Common Hyssop",
            scientificName: "Vitex agnus-castus",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/shrubs/hyssop-225065_1920.jpg",
            description: "The Shoal Creek Chaste Tree (Vitex agnus-castus ‘Shoal Creek’) is a heat- and drought-tolerant ornamental tree that thrives in Albuquerque’s arid climate. Growing 10–15 feet tall and wide, it forms a multi-trunked, vase-like shape with fragrant, gray-green foliage. From late spring through summer, it produces showy spikes of violet-blue flowers, attracting pollinators like bees and butterflies. It prefers full sun and well-draining soil, requiring low to moderate water once established.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/rainwater.png",
            waterRequirement: "Xeric",
            hardinessZones: "6-9",
            matureSize: "20' x 20'",
            native: false
          },
          {
            id: 1,
            name: "Mexican Hyssop",
            scientificName: "Agastache rupestris",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/shrubs/Agastache_rupestre.jpg",
            description: "Mexican Blue Sage is a drought-tolerant perennial that thrives in New Mexico’s hot, dry climate. It features striking blue flowers from spring to fall, attracting bees, butterflies, and hummingbirds. With silvery-green foliage and a compact, mounding habit, it’s perfect for xeriscapes, borders, or rock gardens. Thriving in full sun and well-drained soil, this low-maintenance sage adds vibrant color and texture to any landscape.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
            waterRequirement: "Low Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "15' x 30'",
          },
        {
            id: 35,
            name: "Red Hot Poker",
            scientificName: "Vitex agnus-castus",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/shrubs/red-hot-poker.jpg",
            description: "The Shoal Creek Chaste Tree (Vitex agnus-castus ‘Shoal Creek’) is a heat- and drought-tolerant ornamental tree that thrives in Albuquerque’s arid climate. Growing 10–15 feet tall and wide, it forms a multi-trunked, vase-like shape with fragrant, gray-green foliage. From late spring through summer, it produces showy spikes of violet-blue flowers, attracting pollinators like bees and butterflies. It prefers full sun and well-draining soil, requiring low to moderate water once established.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/rainwater.png",
            waterRequirement: "Xeric",
            hardinessZones: "6-9",
            matureSize: "20' x 20'",
            native: false
          },
          {
            id: 1,
            name: "Flowering Quince",
            scientificName: "Spartium junceum",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flower/flowering-quince-4139038_1920.jpg",
            description: "Spanish Broom is a sun-loving shrub that brings a touch of Mediterranean charm to New Mexico gardens with its bright yellow, pea-like flowers that bloom in late spring to early summer. Known for its long, slender stems and fine, narrow foliage, it adds a graceful, airy appearance to any landscape. Thriving in full sun and well-drained soils, Spanish Broom is drought-tolerant once established and ideal for xeriscape gardening. Its vibrant blooms attract pollinators, and its low-maintenance nature makes it an excellent choice for gardeners seeking a colorful, water-wise shrub.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
            waterRequirement: "Low Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "15' x 30'",
          },
        {
            id: 35,
            name: "Coralberry Shrub",
            scientificName: "Symphoricarpos orbiculatus",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/shrubs/coralberry.jpg",
            description: "The Shoal Creek Chaste Tree (Vitex agnus-castus ‘Shoal Creek’) is a heat- and drought-tolerant ornamental tree that thrives in Albuquerque’s arid climate. Growing 10–15 feet tall and wide, it forms a multi-trunked, vase-like shape with fragrant, gray-green foliage. From late spring through summer, it produces showy spikes of violet-blue flowers, attracting pollinators like bees and butterflies. It prefers full sun and well-draining soil, requiring low to moderate water once established.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/rainwater.png",
            waterRequirement: "Xeric",
            hardinessZones: "6-9",
            matureSize: "20' x 20'",
            native: false
          },
          {
            id: 1,
            name: "Mexican Blue Sage",
            scientificName: "Salvia chamaedryoides",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flower/Salviachamaedryoides.jpg",
            description: "Mexican Blue Sage is a drought-tolerant perennial that thrives in New Mexico’s hot, dry climate. It features striking blue flowers from spring to fall, attracting bees, butterflies, and hummingbirds. With silvery-green foliage and a compact, mounding habit, it’s perfect for xeriscapes, borders, or rock gardens. Thriving in full sun and well-drained soil, this low-maintenance sage adds vibrant color and texture to any landscape.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
            waterRequirement: "Low Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "15' x 30'",
          },
       
      
        ],
    grasses:[
      {
        id: 35,
        name: "Blue Avena",
        scientificName: "Vitex agnus-castus",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/vitex.jpg",
        description: "The Shoal Creek Chaste Tree (Vitex agnus-castus ‘Shoal Creek’) is a heat- and drought-tolerant ornamental tree that thrives in Albuquerque’s arid climate. Growing 10–15 feet tall and wide, it forms a multi-trunked, vase-like shape with fragrant, gray-green foliage. From late spring through summer, it produces showy spikes of violet-blue flowers, attracting pollinators like bees and butterflies. It prefers full sun and well-draining soil, requiring low to moderate water once established.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/rainwater.png",
        waterRequirement: "Xeric",
        hardinessZones: "6-9",
        matureSize: "20' x 20'",
        native: false
      },
      {
        id: 35,
        name: "Switchgrass",
        scientificName: "Vitex agnus-castus",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/vitex.jpg",
        description: "The Shoal Creek Chaste Tree (Vitex agnus-castus ‘Shoal Creek’) is a heat- and drought-tolerant ornamental tree that thrives in Albuquerque’s arid climate. Growing 10–15 feet tall and wide, it forms a multi-trunked, vase-like shape with fragrant, gray-green foliage. From late spring through summer, it produces showy spikes of violet-blue flowers, attracting pollinators like bees and butterflies. It prefers full sun and well-draining soil, requiring low to moderate water once established.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/rainwater.png",
        waterRequirement: "Xeric",
        hardinessZones: "6-9",
        matureSize: "20' x 20'",
        native: false
      },
      {
        id: 35,
        name: "Galleta",
        scientificName: "Vitex agnus-castus",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/vitex.jpg",
        description: "The Shoal Creek Chaste Tree (Vitex agnus-castus ‘Shoal Creek’) is a heat- and drought-tolerant ornamental tree that thrives in Albuquerque’s arid climate. Growing 10–15 feet tall and wide, it forms a multi-trunked, vase-like shape with fragrant, gray-green foliage. From late spring through summer, it produces showy spikes of violet-blue flowers, attracting pollinators like bees and butterflies. It prefers full sun and well-draining soil, requiring low to moderate water once established.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/rainwater.png",
        waterRequirement: "Xeric",
        hardinessZones: "6-9",
        matureSize: "20' x 20'",
        native: false
      },
      {
        id: 35,
        name: "Giant Sacaton",
        scientificName: "Vitex agnus-castus",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/vitex.jpg",
        description: "The Shoal Creek Chaste Tree (Vitex agnus-castus ‘Shoal Creek’) is a heat- and drought-tolerant ornamental tree that thrives in Albuquerque’s arid climate. Growing 10–15 feet tall and wide, it forms a multi-trunked, vase-like shape with fragrant, gray-green foliage. From late spring through summer, it produces showy spikes of violet-blue flowers, attracting pollinators like bees and butterflies. It prefers full sun and well-draining soil, requiring low to moderate water once established.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/rainwater.png",
        waterRequirement: "Xeric",
        hardinessZones: "6-9",
        matureSize: "20' x 20'",
        native: false
      },
      {
        id: 35,
        name: "Pinky Flamingo Muhly",
        scientificName: "Vitex agnus-castus",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/vitex.jpg",
        description: "The Shoal Creek Chaste Tree (Vitex agnus-castus ‘Shoal Creek’) is a heat- and drought-tolerant ornamental tree that thrives in Albuquerque’s arid climate. Growing 10–15 feet tall and wide, it forms a multi-trunked, vase-like shape with fragrant, gray-green foliage. From late spring through summer, it produces showy spikes of violet-blue flowers, attracting pollinators like bees and butterflies. It prefers full sun and well-draining soil, requiring low to moderate water once established.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/rainwater.png",
        waterRequirement: "Xeric",
        hardinessZones: "6-9",
        matureSize: "20' x 20'",
        native: false
      },
      {
        id: 35,
        name: "Silky Threadgrass",
        scientificName: "Vitex agnus-castus",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/vitex.jpg",
        description: "The Shoal Creek Chaste Tree (Vitex agnus-castus ‘Shoal Creek’) is a heat- and drought-tolerant ornamental tree that thrives in Albuquerque’s arid climate. Growing 10–15 feet tall and wide, it forms a multi-trunked, vase-like shape with fragrant, gray-green foliage. From late spring through summer, it produces showy spikes of violet-blue flowers, attracting pollinators like bees and butterflies. It prefers full sun and well-draining soil, requiring low to moderate water once established.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/rainwater.png",
        waterRequirement: "Xeric",
        hardinessZones: "6-9",
        matureSize: "20' x 20'",
        native: false
      },
      {
        id: 35,
        name: "Little Bluestem",
        scientificName: "Vitex agnus-castus",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/vitex.jpg",
        description: "The Shoal Creek Chaste Tree (Vitex agnus-castus ‘Shoal Creek’) is a heat- and drought-tolerant ornamental tree that thrives in Albuquerque’s arid climate. Growing 10–15 feet tall and wide, it forms a multi-trunked, vase-like shape with fragrant, gray-green foliage. From late spring through summer, it produces showy spikes of violet-blue flowers, attracting pollinators like bees and butterflies. It prefers full sun and well-draining soil, requiring low to moderate water once established.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/rainwater.png",
        waterRequirement: "Xeric",
        hardinessZones: "6-9",
        matureSize: "20' x 20'",
        native: false
      },

    ],

    hardxeric: [
    
       
     
        {
            id: 35,
            name: "Fringed Sage",
            scientificName: "Vitex agnus-castus",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/shrubs/fringed-sage.jpg",
            description: "The Shoal Creek Chaste Tree (Vitex agnus-castus ‘Shoal Creek’) is a heat- and drought-tolerant ornamental tree that thrives in Albuquerque’s arid climate. Growing 10–15 feet tall and wide, it forms a multi-trunked, vase-like shape with fragrant, gray-green foliage. From late spring through summer, it produces showy spikes of violet-blue flowers, attracting pollinators like bees and butterflies. It prefers full sun and well-draining soil, requiring low to moderate water once established.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/rainwater.png",
            waterRequirement: "Xeric",
            hardinessZones: "6-9",
            matureSize: "20' x 20'",
            native: false
          },
        {
            id: 35,
            name: "Curry Plant",
            scientificName: "Vitex agnus-castus",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/shrubs/curry-plant.jpg",
            description: "The Shoal Creek Chaste Tree (Vitex agnus-castus ‘Shoal Creek’) is a heat- and drought-tolerant ornamental tree that thrives in Albuquerque’s arid climate. Growing 10–15 feet tall and wide, it forms a multi-trunked, vase-like shape with fragrant, gray-green foliage. From late spring through summer, it produces showy spikes of violet-blue flowers, attracting pollinators like bees and butterflies. It prefers full sun and well-draining soil, requiring low to moderate water once established.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/rainwater.png",
            waterRequirement: "Xeric",
            hardinessZones: "6-9",
            matureSize: "20' x 20'",
            native: false
          },
        {
            id: 35,
            name: "Big Sagebrush",
            scientificName: "Vitex agnus-castus",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/shrubs/Big%20Sagebrush.jpg",
            description: "The Shoal Creek Chaste Tree (Vitex agnus-castus ‘Shoal Creek’) is a heat- and drought-tolerant ornamental tree that thrives in Albuquerque’s arid climate. Growing 10–15 feet tall and wide, it forms a multi-trunked, vase-like shape with fragrant, gray-green foliage. From late spring through summer, it produces showy spikes of violet-blue flowers, attracting pollinators like bees and butterflies. It prefers full sun and well-draining soil, requiring low to moderate water once established.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/rainwater.png",
            waterRequirement: "Xeric",
            hardinessZones: "6-9",
            matureSize: "20' x 20'",
            native: false
          },
          {
            id: 1,
            name: "Apache Plume",
            scientificName: "Fallugia paradoxa",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flower/apache-plume-1937218_1920.jpg",
            description: "Apache Plume is a striking shrub native to the Southwestern United States, valued for its elegant, feathery plumes that appear in late spring and early summer. These plumes are followed by small white flowers that provide a delicate contrast to its gray-green, aromatic foliage. Well-suited for New Mexico’s dry, rocky landscapes, Apache Plume thrives in full sun and well-drained soils, making it an excellent choice for xeriscape gardens. This drought-tolerant shrub attracts pollinators and offers year-round interest with its unique form and beautiful seed heads, which persist into the winter.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
            waterRequirement: "Low Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "15' x 30'",
          },
        {
            id: 35,
            name: "Three-leaf Sumac",
            scientificName: "Vitex agnus-castus",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/shrubs/three-leaf-sumac.jpg",
            description: "The Shoal Creek Chaste Tree (Vitex agnus-castus ‘Shoal Creek’) is a heat- and drought-tolerant ornamental tree that thrives in Albuquerque’s arid climate. Growing 10–15 feet tall and wide, it forms a multi-trunked, vase-like shape with fragrant, gray-green foliage. From late spring through summer, it produces showy spikes of violet-blue flowers, attracting pollinators like bees and butterflies. It prefers full sun and well-draining soil, requiring low to moderate water once established.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/rainwater.png",
            waterRequirement: "Xeric",
            hardinessZones: "6-9",
            matureSize: "20' x 20'",
            native: false
          },
          {
            id: 1,
            name: "Dwarf Fragrant Sumac",
            scientificName: "Rhus aromatica 'Gro-Low'",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/shrubs/dwarf-fragrant-sumac.jpg",
            description: "Dwarf Fragrant Sumac is a low-growing, deciduous shrub that thrives in New Mexico’s dry, sunny landscapes. Known for its fragrant, lemon-scented foliage and bright red to orange berries that attract birds, this compact shrub is perfect for ground cover or low hedges. Its dark green leaves turn vibrant shades of red, orange, and yellow in the fall, adding seasonal interest. Dwarf Fragrant Sumac is drought-tolerant and thrives in full sun and well-drained soils, making it an excellent choice for xeriscaping or low-maintenance gardens. Its resilience and attractive foliage provide year-round beauty with minimal care.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
            waterRequirement: "Low Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "15' x 30'",
          },
        {
            id: 35,
            name: "Upright Rosemarry",
            scientificName: "Vitex agnus-castus",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flower/rosemary-4912663_1920.jpg",
            description: "The Shoal Creek Chaste Tree (Vitex agnus-castus ‘Shoal Creek’) is a heat- and drought-tolerant ornamental tree that thrives in Albuquerque’s arid climate. Growing 10–15 feet tall and wide, it forms a multi-trunked, vase-like shape with fragrant, gray-green foliage. From late spring through summer, it produces showy spikes of violet-blue flowers, attracting pollinators like bees and butterflies. It prefers full sun and well-draining soil, requiring low to moderate water once established.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/rainwater.png",
            waterRequirement: "Xeric",
            hardinessZones: "6-9",
            matureSize: "20' x 20'",
            native: false
          },
        {
            id: 35,
            name: "Occotillio",
            scientificName: "Vitex agnus-castus",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/shrubs/occotillio.jpg",
            description: "The Shoal Creek Chaste Tree (Vitex agnus-castus ‘Shoal Creek’) is a heat- and drought-tolerant ornamental tree that thrives in Albuquerque’s arid climate. Growing 10–15 feet tall and wide, it forms a multi-trunked, vase-like shape with fragrant, gray-green foliage. From late spring through summer, it produces showy spikes of violet-blue flowers, attracting pollinators like bees and butterflies. It prefers full sun and well-draining soil, requiring low to moderate water once established.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/rainwater.png",
            waterRequirement: "Xeric",
            hardinessZones: "6-9",
            matureSize: "20' x 20'",
            native: false
          },
          {
            id: 1,
            name: "Fern Bush",
            scientificName: "Pinus edulis",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flower/fernbush.JPG",
            description: "Fern Bush is a native New Mexico shrub valued for its feathery, fern-like foliage and delicate, creamy-white flowers that bloom in late spring to early summer. Known for its ability to thrive in arid conditions, this shrub is highly drought-tolerant once established and grows best in well-drained soils with full sun. It’s perfect for xeriscaping, offering a graceful texture and providing wildlife habitat with its fragrant flowers that attract pollinators. With minimal maintenance, Fern Bush adds a soft, airy element to dry, desert landscapes.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
            waterRequirement: "Low Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "15' x 30'",
          },
          {
            id: 1,
            name: "Chamisa",
            scientificName: "Chrysothamnus nauseosus",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flower/needles-district-rabbitbrush-4009467_1920.jpg",
            description: "Rabbit Brush is a native shrub that flourishes in New Mexico’s dry, rocky soils. Known for its bright yellow flowers that bloom in late summer to fall, it provides a cheerful burst of color when many other plants are past their prime. This drought-tolerant shrub thrives in full sun and well-drained soils, making it ideal for xeriscaping or low-maintenance gardens. Rabbit Brush attracts pollinators and offers a natural, wild look to desert landscapes, with its silvery-green foliage adding texture and contrast. Its resilience to harsh conditions makes it a perfect fit for arid environments.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
            waterRequirement: "Low Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "15' x 30'",
          },
          {
            id: 1,
            name: "Brakelights Red Yucca",
            scientificName: "Hesperaloe parviflora 'Brakelight'",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flower/Red-Yucca.jpg",
            description: "Brakelight Red Yucca is a striking, drought-tolerant succulent that thrives in New Mexico’s dry climate. Known for its vibrant red tubular flowers that bloom on tall spikes during the summer, it adds a bold pop of color to xeriscape gardens. The plant’s narrow, spiky foliage forms a clumping rosette, offering an architectural element to landscapes. Brakelight Red Yucca thrives in full sun and well-drained soils, requiring minimal water once established. Its low-maintenance nature and ability to attract hummingbirds make it an excellent choice for low-water gardens or desert landscapes.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
            waterRequirement: "Low Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "15' x 30'",
          },

        ],
}
export default xericshrubs