

const broadleafevergreens = {
  boxwoods:  [
    {
        id: 1,
        name: "Wintergreen Boxwood",
        scientificName: "Buxus microphylla var. japonica ‘Wintergreen’",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/boxwood-1235076_1920.jpg",
        description: "Wintergreen boxwood is a hardy, low-maintenance evergreen shrub that thrives in New Mexico with proper care. It prefers moderate water but is relatively drought-tolerant once established, making it suitable for Albuquerque’s dry climate. This shrub does best in partial to full sun but benefits from afternoon shade to protect against intense summer heat. Regular pruning maintains its shape, making it ideal for hedges, borders, or foundation plantings, while mulch helps retain moisture and regulate soil temperature.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30'",
      },
    {
        id: 1,
        name: "Green Mountain Boxwood",
        scientificName: " Buxus x ‘Green Mountain’",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/boxwood-6731662_1920.jpg",
        description: "Green Mountain Boxwood is an upright, cone-shaped evergreen shrub that adds year-round structure to New Mexico gardens. Its dense, bright green foliage maintains color well through winter, though slight bronzing may occur in colder months. This slow-growing variety is perfect for hedges, topiaries, or foundation plantings, with minimal pruning needed to maintain its natural shape. Mulching around the base helps retain moisture and protect roots from temperature extremes.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30'",
      },
    {
        id: 1,
        name: "Elegans Variegated Boxwood",
        scientificName: "Buxus sempervirens ‘Elegans’",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/butterflybush.jpg",
        description: "Elegans Variegated Boxwood stands out with its eye-catching variegated foliage, featuring creamy white and green leaves that brighten shaded areas. This slow-growing shrub is ideal for borders, informal hedges, or as an accent plant, offering year-round interest with minimal maintenance. While it tolerates pruning, its naturally soft form works well with a more relaxed garden design. Mulch helps conserve moisture and keep roots cool in New Mexico’s dry climate.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30'",
      },
  ],
  euonomys:  [
    {
        id: 1,
        name: "Evergreen Euonymus",
        scientificName: "Euonymus japonicus",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/butterflybush.jpg",
        description: "Evergreen Euonymus is a versatile, dense shrub that provides year-round greenery in New Mexico landscapes. Its glossy, dark green leaves make it an excellent choice for hedges, screens, or foundation plantings. This hardy shrub is low-maintenance and adapts well to pruning, allowing for a formal or natural look. A layer of mulch helps retain moisture and regulate soil temperature for optimal growth.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30'",
      },
    {
        id: 1,
        name: "Boxleaf Euonymus",
        scientificName: "Euonymus japonicus ‘Microphyllus’",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/varigated-euonomys.jpg",
        description: "Boxleaf Euonymus is a compact, evergreen shrub prized for its small, dense foliage and neat, rounded form. It’s an excellent alternative to boxwood for hedges, borders, or foundation plantings, requiring minimal pruning to maintain its shape. This hardy shrub adapts well to different soil conditions and urban environments, making it a reliable choice for New Mexico gardens. Mulching helps conserve moisture and protect roots from temperature fluctuations.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30'",
      },
    {
        id: 1,
        name: "Manhattan Euonymus",
        scientificName: "Euonymus kiautschovicus ‘Manhattan’",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/butterflybush.jpg",
        description: "Manhattan Euonymus is a fast-growing, broadleaf evergreen valued for its lush, deep green foliage and adaptability. It forms a dense, mounded shape, making it ideal for hedges, windbreaks, or privacy screens. This tough shrub tolerates urban conditions well and can be pruned to maintain its size and shape. Mulching helps retain moisture and supports healthy root development in New Mexico’s climate.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30'",
      },
  ],
  photinias:  [
    {
        id: 1,
        name: "Red Tip Photinia",
        scientificName: "Photinia x fraseri",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/photinia.jpg",
        description: "Red Tip Photinia, sometimes known as Red Robin Photinia is a fast-growing evergreen shrub known for its striking red new growth that matures to glossy green. It’s a popular choice for hedges, screens, or specimen plantings due to its dense foliage and tolerance for pruning. While highly adaptable, good air circulation helps prevent leaf spot, and mulching supports healthy root development. This is a great choice for shrubbery in New Mexico.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30'",
      },
    {
        id: 1,
        name: " Dwarf Red Tip Photinia",
        scientificName: "Photinia x fraseri 'Little Red Robin'",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/photinia-4384372_1920.jpg",
        description: "Dwarf Red Tip Photinia offers the same vibrant red new growth as its larger counterpart but in a more compact form. Growing slower and staying smaller, it works well for low hedges, borders, or container plantings. It maintains its color best with regular trimming, and mulch helps retain moisture in New Mexico’s dry climate.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30'",
      },
    {
        id: 1,
        name: "Pink Marble Photinia",
        scientificName: "Photinia x fraseri 'Pink Marble'",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/photinia-pink.jpg",
        description: "Pink Marble Photinia adds a unique twist with variegated foliage, featuring splashes of creamy white alongside its signature red new growth. This eye-catching shrub makes a stunning hedge, accent, or foundation plant, providing year-round color. Pruning encourages fresh growth, and mulching around the base helps conserve moisture and regulate soil temperature.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30'",
      },
    {
        id: 1,
        name: "Chinese Photinia",
        scientificName: "Photinia serratifolia",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/chinese-photinia.jpg",
        description: "Chinese Photinia is a robust, evergreen shrub with large, leathery green leaves and reddish-bronze new growth. Taller and more tree-like than other photinias, it works well as a privacy screen, windbreak, or specimen plant. Its dense foliage provides year-round interest, and occasional pruning helps maintain its shape. Mulching supports moisture retention and root health in New Mexico’s dry climate.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30'",
      },
  ],
  nandinas:  [
    {
        id: 1,
        name: "Heavenly Bamboo Nandina",
        scientificName: "Nandina domestica",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/berries-22848_1920.jpg",
        description: "Heavenly Bamboo is a versatile, semi-evergreen shrub valued for its delicate, bamboo-like foliage that changes color with the seasons. In New Mexico gardens, its leaves transition from bright green in spring to fiery red and orange in fall and winter, adding year-round interest. Clusters of white flowers in summer give way to vibrant red berries that attract birds. This low-maintenance shrub works well in borders, foundation plantings, or as an accent, with occasional pruning helping to maintain its shape. Mulching aids in moisture retention and root protection in dry conditions.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30'",
      },
    {
        id: 1,
        name: "Firepower Nandina",
        scientificName: "Nandina domestica ‘Firepower’",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/heavenly-bamboo-8514863_1920.jpg",
        description: "Firepower Nandina is a compact, dwarf variety prized for its brilliant red foliage in fall and winter. Its lush green leaves turn fiery shades of red and orange as temperatures drop, providing year-round interest without requiring pruning. Ideal for borders, mass plantings, or containers, this low-maintenance shrub thrives with occasional watering and benefits from mulch to retain moisture.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30'",
      },
    {
        id: 1,
        name: "Nandina Flirt",
        scientificName: "Nandina domestica ‘Murasaki’",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/butterflybush.jpg",
        description: "Flirt Nandina is a smaller, more controlled variety that features deep red new growth, which lasts longer than other nandinas before maturing to dark green. Its compact size makes it perfect for edging, foundation plantings, or containers. With minimal care required, it thrives in well-drained soil, and a layer of mulch helps conserve moisture in New Mexico’s dry climate.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30'",
      },
    {
        id: 1,
        name: "Lemon Lime Nandina",
        scientificName: "Nandina domestica 'Lemon Lime'",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/butterflybush.jpg",
        description: "Lemon Lime Nandina stands out with its bright chartreuse foliage that adds a fresh, modern look to gardens. Unlike other nandinas, it doesn’t develop red tones in winter, instead maintaining a vibrant green year-round. This bushy, compact shrub is excellent for mass plantings, borders, or foundation plantings, with mulch helping to regulate soil moisture and temperature.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30'",
      },
  ],

  cotoneasters:  [
    {
        id: 1,
        name: "Pyrenees Cotoneaster",
        scientificName: "Cotoneaster serotinus",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/butterflybush.jpg",
        description: "Pyrenees Cotoneaster is a sprawling, low-growing shrub that offers year-round interest with its small, glossy green leaves and bright red berries in fall. It’s an excellent choice for ground cover, slopes, or low-maintenance hedges, where its dense foliage can help prevent erosion. This hardy shrub is drought-tolerant once established, and a layer of mulch can help retain moisture in New Mexico’s dry conditions.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30'",
      },
    {
        id: 1,
        name: "Willowleaf Cotoneaster",
        scientificName: "Cotoneaster salicifolius",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/butterflybush.jpg",
        description: "Willowleaf Cotoneaster is a spreading, evergreen shrub with narrow, willow-like leaves that provide an elegant, airy texture. Its white flowers in spring give way to clusters of red berries in fall, which attract birds. This low-maintenance shrub works well as a ground cover, border, or trailing plant, and mulching around its base helps maintain moisture and protect the roots.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30'",
      },
    {
        id: 1,
        name: "Streibs Findling Cotoneaster",
        scientificName: "Cotoneaster × suecicus ‘Streib’s Findling’",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/butterflybush.jpg",
        description: "Streib’s Findling Cotoneaster is a compact, mound-forming shrub with dark green leaves and small white flowers that bloom in spring, followed by red berries in the fall. Its dense growth habit makes it ideal for low hedges, foundation plantings, or as an accent shrub. This hardy variety is drought-tolerant once established and benefits from mulching to conserve moisture and regulate soil temperature.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30'",
      },
  ],
  burningbush:  [
    {
        id: 1,
        name: "Fire Ball Burning Bush",
        scientificName: "Euonymus alatus ‘Fireball’",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/butterflybush.jpg",
        description: "Fireball Burning Bush is a compact, deciduous shrub renowned for its stunning red fall foliage. This variety offers a burst of color as its leaves turn vibrant red in autumn, creating a dramatic focal point in the garden. Growing to about 3-4 feet tall, it's perfect for borders, small hedges, or as an accent plant. Minimal pruning is needed, and mulching helps retain moisture and protect roots from temperature extremes.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30'",
      },
    {
        id: 1,
        name: "Dwarf Burning Bush",
        scientificName: "Euonymus alatus ‘Compactus’",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/butterflybush.jpg",
        description: "Dwarf Burning Bush is a smaller version of the classic burning bush, reaching about 3-4 feet in height. It offers the same fiery red foliage in the fall, but with a more compact and manageable size, making it ideal for smaller gardens, containers, or as a low hedge. This shrub thrives in well-draining soil, and mulching helps keep the roots cool and moist in New Mexico’s dry climate.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30'",
      },
    {
        id: 1,
        name: "Rudy Haag Burning Bush",
        scientificName: "Euonymus alatus 'Rudy Haag'",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/butterflybush.jpg",
        description: "Rudy Haag Burning Bush is a slow-growing, compact variety that offers brilliant red color in the fall, similar to the standard burning bush but with a more refined growth habit. Growing to about 3 feet tall, it’s perfect for smaller spaces or as a low hedge. It’s low-maintenance and, when mulched, retains moisture, providing long-lasting beauty throughout the year.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30'",
      },
  ],
  barberries: [
    {
      id: 1,
      name: "Crimson Pygmy Barberry",
      scientificName: "Berberis thunbergii ‘Crimson Pygmy’",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/butterflybush.jpg",
      description: "Crimson Pygmy Barberry is a compact, deciduous shrub known for its deep red-purple foliage that provides year-round color, especially in the fall when it intensifies. Reaching about 2 feet in height, it’s perfect for low hedges, borders, or containers. This low-maintenance variety is drought-tolerant once established and thrives in well-drained soil. Mulching helps retain moisture and protect roots from extreme temperatures.",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
      waterRequirement: "Low Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "15' x 30'",
  },
    {
      id: 1,
      name: "Orange Rocket Barberry",
      scientificName: "Berberis thunbergii ‘Orange Rocket’",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/butterflybush.jpg",
      description: "Orange Rocket Barberry  is an upright, narrow shrub that stands out with its striking orange-red foliage in spring and summer, transitioning to a vibrant red in fall. Growing to about 3-4 feet tall, it makes a bold statement in gardens as a specimen plant or in borders. This hardy shrub is drought-tolerant and requires minimal care, with mulching helping to retain moisture and regulate soil temperature.",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
      waterRequirement: "Low Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "15' x 30'",
  },
    {
      id: 1,
      name: "Sunjoy Gold Barberry",
      scientificName: "Berberis thunbergii 'Sunjoy Gold'",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/butterflybush.jpg",
      description: "Sunjoy Gold Barberry is a bright and striking shrub that features golden-yellow foliage, which turns to orange and red in the fall. Growing to around 3 feet tall, it adds color and texture to gardens, working well as a border, accent, or low hedge. This hardy, low-maintenance shrub thrives in full sun and benefits from mulching to conserve moisture and protect its roots in dry climates.",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
      waterRequirement: "Low Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "15' x 30'",
  },
    {
      id: 1,
      name: "Algerita",
      scientificName: "Berberis trifoliolata",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/butterflybush.jpg",
      description: "Algerita is a hardy, evergreen shrub native to the southwestern United States, including New Mexico. It is characterized by its spiny, dark green leaves and small yellow flowers that bloom in early spring, followed by bright red berries in the fall. Algerita thrives in dry, rocky soil and is highly drought-tolerant once established, making it ideal for low-maintenance landscapes or xeriscaping. Its compact, rounded form makes it a great choice for borders, hedges, or wildlife-friendly plantings. Mulching can help retain moisture and protect the roots during extreme temperatures.",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
      waterRequirement: "Low Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "15' x 30'",
      native: true
  },

  ],
  spireas: [
    {
      id: 1,
      name: "Blue Mist Spirea",
      scientificName: "Caryopteris × clandonensis ‘Blue Mist’",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/butterflybush.jpg",
      description: "Blue Mist Spirea is a fragrant, deciduous shrub that adds a pop of color to New Mexico gardens with its stunning blue-purple flowers in late summer to fall. Its silvery-gray foliage provides a beautiful contrast to the vibrant blooms. Growing to about 2-3 feet tall, it’s perfect for borders, containers, or as a low hedge. This drought-tolerant shrub thrives in full sun, and mulching helps retain moisture and keep roots protected.",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
      waterRequirement: "Low Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "15' x 30'",
  },
    {
      id: 1,
      name: "Dark Knight Spirea",
      scientificName: "Caryopteris × clandonensis ‘Dark Knight’",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/butterflybush.jpg",
      description: "Dark Knight Spirea is a compact, hardy shrub that features deep blue, aromatic flowers against a backdrop of dark green foliage. This variety reaches about 2 feet tall and blooms in late summer to fall, attracting pollinators like bees and butterflies. It’s well-suited for dry climates, requiring minimal water once established. Mulching helps maintain soil moisture and provides root protection.",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
      waterRequirement: "Low Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "15' x 30'",
  },
    {
      id: 1,
      name: "Double Play Doozie Spirea",
      scientificName: "Spiraea japonica ‘Double Play Doozie’",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/butterflybush.jpg",
      description: "Double Play Doozie Spirea is a vibrant, compact shrub known for its bold, double pink blooms that appear in early summer and continue into fall. The deep green foliage turns to shades of red and purple in the fall, adding year-round interest. Growing to about 2 feet tall, it’s perfect for borders, containers, or mass plantings. It’s low-maintenance, drought-tolerant once established, and benefits from mulching to conserve moisture.",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
      waterRequirement: "Low Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "15' x 30'",
  },
    {
      id: 1,
      name: "Little Spark Spirea",
      scientificName: "Spiraea japonica ‘Little Spark’",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/butterflybush.jpg",
      description: "Little Spark Spirea is a small, compact shrub with striking pink flowers that bloom profusely in summer. The dark green foliage turns shades of red and orange in the fall, providing additional seasonal interest. Reaching only about 18-24 inches tall, it’s an excellent choice for smaller gardens, containers, or low hedges. It thrives in full sun and well-drained soil, with mulching helping to retain moisture and regulate temperature.",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
      waterRequirement: "Low Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "15' x 30'",
  },
    {
      id: 1,
      name: "Double Play Candy Corn Spirea",
      scientificName: "Spiraea japonica ‘Double Play Candy Corn’",
      image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/butterflybush.jpg",
      description: "Double Play Candy Corn Spirea is a vibrant, compact shrub with multicolored foliage that starts with yellow and orange hues in spring, transitioning to red and purple in the fall. Its pink flowers bloom in summer, attracting pollinators to the garden. Reaching about 2 feet tall, it’s perfect for small hedges, borders, or as an accent plant. This low-maintenance shrub thrives in full sun, and mulching helps retain moisture and regulate temperature.",
      sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
      sunRequirement: "Full Sun",
      waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
      waterRequirement: "Low Water",
      hardinessZones: [4, 5, 6, 7],
      matureSize: "15' x 30'",
  },

  ],
  others:  [
    {
        id: 1,
        name: "Texas Mountain Laurel",
        scientificName: "Sophora secundiflora",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/butterflybush.jpg",
        description: "Texas Mountain Laurel is a striking evergreen shrub or small tree known for its vibrant clusters of purple, pea-like flowers that bloom in early spring, emitting a sweet fragrance. This native New Mexico plant has leathery, dark green leaves that provide year-round interest. Reaching up to 10 feet tall, it’s perfect for accent plantings, hedges, or as a specimen tree. Once established, it’s highly drought-tolerant and thrives in well-drained soil. Mulching around its base helps retain moisture and protect roots from temperature fluctuations.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30'",
      },
      {
        id: 1,
        name: "Cherry Laurel",
        scientificName: "Prunus laurocerasus",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/butterflybush.jpg",
        description: "Cherry Laurel is a versatile, evergreen shrub with glossy, dark green leaves that provide year-round interest. Known for its white, fragrant flower spikes that appear in spring, followed by dark berries in the fall, this shrub makes an excellent choice for hedges, screens, or foundation plantings. Growing up to 10 feet tall, it thrives in shaded or partially shaded areas, though it can tolerate full sun in cooler climates. Regular watering and mulching can help retain moisture and protect the roots in New Mexico’s dry conditions.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30'",
      },
    {
        id: 1,
        name: "Pyracantha",
        scientificName: "Pyracantha coccinea",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/butterflybush.jpg",
        description: "Pyracantha, commonly known as firethorn, is a vigorous, evergreen shrub with spiny branches and dense foliage. It produces clusters of white flowers in the spring, followed by vibrant red, orange, or yellow berries in the fall that attract birds. This hardy shrub can be used for hedges, screens, or as a cascading ground cover. It thrives in full sun and well-drained soil, and once established, it’s drought-tolerant. Pyracantha also benefits from occasional pruning to maintain its shape and encourage better flowering and berry production. Mulching around the base helps conserve moisture and protect roots from extreme temperatures.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30'",
      },
    {
        id: 1,
        name: "Hollyleaf Redberry",
        scientificName: "Rhamnus ilicifolia",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/butterflybush.jpg",
        description: "Hollyleaf Redberry is a hardy, evergreen shrub native to the southwestern United States, including New Mexico. Known for its glossy, holly-like leaves, it produces small, inconspicuous yellow-green flowers in spring, followed by clusters of red berries that persist into winter, attracting birds. This drought-tolerant shrub thrives in well-drained, rocky soils and is perfect for xeriscaping, erosion control, or wildlife-friendly plantings. It requires minimal maintenance and benefits from mulching to retain moisture and protect the roots in dry climates.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30'",
      },
    {
        id: 1,
        name: "Waxleaf Privet",
        scientificName: "Ligustrum japonicum",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/butterflybush.jpg",
        description: "Waxleaf Privet is a versatile, fast-growing evergreen shrub known for its dense, dark green foliage and fragrant white flowers that bloom in late spring to early summer. It produces small, black berries in the fall, which are attractive to birds. Reaching up to 8 feet tall, it’s commonly used for hedges, screens, or foundation plantings. While it thrives in full sun to partial shade, Waxleaf Privet is adaptable to various soil types and is relatively low-maintenance. Mulching around its base helps retain moisture, and regular pruning keeps it in shape and encourages healthy growth.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30'",
      },
      {
        id: 1,
        name: "Spanish Broom",
        scientificName: "Prunus laurocerasus",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/spanish-broom.jpg",
        description: "With its deep purple, almost velvety blooms, Black Knight is one of the most striking butterfly bushes for New Mexico gardens. Its rich color contrasts beautifully with desert landscapes, and its long, fragrant flower spikes attract butterflies, hummingbirds, and bees all season. This fast-growing shrub benefits from occasional pruning to maintain shape and encourage fresh blooms, making it a bold yet low-maintenance addition to pollinator-friendly gardens and one of Jericho Nursery's best sellers.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30'",
      },
      {
        id: 1,
        name: "Holly Osmanthus",
        scientificName: "Osmanthus heterophyllus",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/butterflybush.jpg",
        description: "Holly Osmanthus is an evergreen shrub that resembles holly with its spiny, glossy green leaves. Known for its fragrant white flowers that bloom in late fall to early winter, it’s a great addition to gardens for its aromatic appeal. This compact shrub grows to about 6-10 feet tall and works well in hedges, screens, or as a specimen plant. It thrives in partial to full shade and is relatively drought-tolerant once established. Mulching helps retain moisture and protect roots from temperature extremes, making it suitable for xeriscaping in New Mexico.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30'",
      },
    {
        id: 1,
        name: "Arizona Rosewood",
        scientificName: "Vauquelinia californica",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/butterflybush.jpg",
        description: "Arizona Rosewood is a slow-growing, evergreen shrub or small tree native to the southwestern United States, including New Mexico. Known for its dark green, leathery leaves and fragrant white flowers that bloom in late spring, this plant produces small, black berries in the fall, which attract wildlife. Reaching up to 15 feet tall, Arizona Rosewood is perfect for use as a specimen tree, hedge, or screen. It thrives in well-drained soil and full sun, and is highly drought-tolerant once established. Mulching around its base helps retain moisture and protects the roots from temperature fluctuations.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30'",
    },

  ],
  

}

export default broadleafevergreens;