const coniferousshrubs = {
    pines: [
   {
        id: 1,
        name: "Mugo Pine",
        scientificName: "Buddleia davidii 'Black Knight'",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/butterflybush.jpg",
        description: "With its deep purple, almost velvety blooms, Black Knight is one of the most striking butterfly bushes for New Mexico gardens. Its rich color contrasts beautifully with desert landscapes, and its long, fragrant flower spikes attract butterflies, hummingbirds, and bees all season. This fast-growing shrub benefits from occasional pruning to maintain shape and encourage fresh blooms, making it a bold yet low-maintenance addition to pollinator-friendly gardens and one of Jericho Nursery's best sellers.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30'",
      },
   {
        id: 1,
        name: "Limber Pine",
        scientificName: "Buddleia davidii 'Black Knight'",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/butterflybush.jpg",
        description: "With its deep purple, almost velvety blooms, Black Knight is one of the most striking butterfly bushes for New Mexico gardens. Its rich color contrasts beautifully with desert landscapes, and its long, fragrant flower spikes attract butterflies, hummingbirds, and bees all season. This fast-growing shrub benefits from occasional pruning to maintain shape and encourage fresh blooms, making it a bold yet low-maintenance addition to pollinator-friendly gardens and one of Jericho Nursery's best sellers.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30'",
      },
   {
        id: 1,
        name: "Dwarf Mountain Pine",
        scientificName: "Buddleia davidii 'Black Knight'",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/butterflybush.jpg",
        description: "With its deep purple, almost velvety blooms, Black Knight is one of the most striking butterfly bushes for New Mexico gardens. Its rich color contrasts beautifully with desert landscapes, and its long, fragrant flower spikes attract butterflies, hummingbirds, and bees all season. This fast-growing shrub benefits from occasional pruning to maintain shape and encourage fresh blooms, making it a bold yet low-maintenance addition to pollinator-friendly gardens and one of Jericho Nursery's best sellers.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30'",
      },

    ],
    junipers: [
    {
        id: 1,
        name: "Blue Rug Juniper",
        scientificName: "Buddleia davidii 'Black Knight'",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/butterflybush.jpg",
        description: "With its deep purple, almost velvety blooms, Black Knight is one of the most striking butterfly bushes for New Mexico gardens. Its rich color contrasts beautifully with desert landscapes, and its long, fragrant flower spikes attract butterflies, hummingbirds, and bees all season. This fast-growing shrub benefits from occasional pruning to maintain shape and encourage fresh blooms, making it a bold yet low-maintenance addition to pollinator-friendly gardens and one of Jericho Nursery's best sellers.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30'",
    },
    {
        id: 1,
        name: "Creeping Blue Juniper",
        scientificName: "Buddleia davidii 'Black Knight'",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/butterflybush.jpg",
        description: "With its deep purple, almost velvety blooms, Black Knight is one of the most striking butterfly bushes for New Mexico gardens. Its rich color contrasts beautifully with desert landscapes, and its long, fragrant flower spikes attract butterflies, hummingbirds, and bees all season. This fast-growing shrub benefits from occasional pruning to maintain shape and encourage fresh blooms, making it a bold yet low-maintenance addition to pollinator-friendly gardens and one of Jericho Nursery's best sellers.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30'",
    },
    {
        id: 1,
        name: "Parson's Juniper",
        scientificName: "Buddleia davidii 'Black Knight'",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/butterflybush.jpg",
        description: "With its deep purple, almost velvety blooms, Black Knight is one of the most striking butterfly bushes for New Mexico gardens. Its rich color contrasts beautifully with desert landscapes, and its long, fragrant flower spikes attract butterflies, hummingbirds, and bees all season. This fast-growing shrub benefits from occasional pruning to maintain shape and encourage fresh blooms, making it a bold yet low-maintenance addition to pollinator-friendly gardens and one of Jericho Nursery's best sellers.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30'",
    },
    {
        id: 1,
        name: "Dwarf Japanese Garden Juniper",
        scientificName: "Buddleia davidii 'Black Knight'",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/butterflybush.jpg",
        description: "With its deep purple, almost velvety blooms, Black Knight is one of the most striking butterfly bushes for New Mexico gardens. Its rich color contrasts beautifully with desert landscapes, and its long, fragrant flower spikes attract butterflies, hummingbirds, and bees all season. This fast-growing shrub benefits from occasional pruning to maintain shape and encourage fresh blooms, making it a bold yet low-maintenance addition to pollinator-friendly gardens and one of Jericho Nursery's best sellers.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30'",
    },



    ],
    spruces: [
    {
        id: 1,
        name: "Dwarf Alberta Spruce",
        scientificName: "Buddleia davidii 'Black Knight'",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/butterflybush.jpg",
        description: "With its deep purple, almost velvety blooms, Black Knight is one of the most striking butterfly bushes for New Mexico gardens. Its rich color contrasts beautifully with desert landscapes, and its long, fragrant flower spikes attract butterflies, hummingbirds, and bees all season. This fast-growing shrub benefits from occasional pruning to maintain shape and encourage fresh blooms, making it a bold yet low-maintenance addition to pollinator-friendly gardens and one of Jericho Nursery's best sellers.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30'",
    },
    {
        id: 1,
        name: "Baby Blue Spruce",
        scientificName: "Buddleia davidii 'Black Knight'",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/butterflybush.jpg",
        description: "With its deep purple, almost velvety blooms, Black Knight is one of the most striking butterfly bushes for New Mexico gardens. Its rich color contrasts beautifully with desert landscapes, and its long, fragrant flower spikes attract butterflies, hummingbirds, and bees all season. This fast-growing shrub benefits from occasional pruning to maintain shape and encourage fresh blooms, making it a bold yet low-maintenance addition to pollinator-friendly gardens and one of Jericho Nursery's best sellers.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30'",
    },
    {
        id: 1,
        name: "Nest Spruce",
        scientificName: "Buddleia davidii 'Black Knight'",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/butterflybush.jpg",
        description: "With its deep purple, almost velvety blooms, Black Knight is one of the most striking butterfly bushes for New Mexico gardens. Its rich color contrasts beautifully with desert landscapes, and its long, fragrant flower spikes attract butterflies, hummingbirds, and bees all season. This fast-growing shrub benefits from occasional pruning to maintain shape and encourage fresh blooms, making it a bold yet low-maintenance addition to pollinator-friendly gardens and one of Jericho Nursery's best sellers.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30'",
    },

    ],
    arborvitaes: [
    {
        id: 1,
        name: "Tater Tot Thuja",
        scientificName: "Buddleia davidii 'Black Knight'",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/butterflybush.jpg",
        description: "With its deep purple, almost velvety blooms, Black Knight is one of the most striking butterfly bushes for New Mexico gardens. Its rich color contrasts beautifully with desert landscapes, and its long, fragrant flower spikes attract butterflies, hummingbirds, and bees all season. This fast-growing shrub benefits from occasional pruning to maintain shape and encourage fresh blooms, making it a bold yet low-maintenance addition to pollinator-friendly gardens and one of Jericho Nursery's best sellers.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30'",
    },
    {
        id: 1,
        name: "Golden Globe Arborvitae",
        scientificName: "Buddleia davidii 'Black Knight'",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/butterflybush.jpg",
        description: "With its deep purple, almost velvety blooms, Black Knight is one of the most striking butterfly bushes for New Mexico gardens. Its rich color contrasts beautifully with desert landscapes, and its long, fragrant flower spikes attract butterflies, hummingbirds, and bees all season. This fast-growing shrub benefits from occasional pruning to maintain shape and encourage fresh blooms, making it a bold yet low-maintenance addition to pollinator-friendly gardens and one of Jericho Nursery's best sellers.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30'",
    },
    {
        id: 1,
        name: "Little Giant Arborvitae",
        scientificName: "Buddleia davidii 'Black Knight'",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/butterflybush.jpg",
        description: "With its deep purple, almost velvety blooms, Black Knight is one of the most striking butterfly bushes for New Mexico gardens. Its rich color contrasts beautifully with desert landscapes, and its long, fragrant flower spikes attract butterflies, hummingbirds, and bees all season. This fast-growing shrub benefits from occasional pruning to maintain shape and encourage fresh blooms, making it a bold yet low-maintenance addition to pollinator-friendly gardens and one of Jericho Nursery's best sellers.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30'",
    },
    {
        id: 1,
        name: "Leprechaun Arborvitae",
        scientificName: "Buddleia davidii 'Black Knight'",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/butterflybush.jpg",
        description: "With its deep purple, almost velvety blooms, Black Knight is one of the most striking butterfly bushes for New Mexico gardens. Its rich color contrasts beautifully with desert landscapes, and its long, fragrant flower spikes attract butterflies, hummingbirds, and bees all season. This fast-growing shrub benefits from occasional pruning to maintain shape and encourage fresh blooms, making it a bold yet low-maintenance addition to pollinator-friendly gardens and one of Jericho Nursery's best sellers.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30'",
    },
    
    ],
    hollies: [
    {
        id: 1,
        name: "Desert Holly",
        scientificName: "Buddleia davidii 'Black Knight'",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/butterflybush.jpg",
        description: "With its deep purple, almost velvety blooms, Black Knight is one of the most striking butterfly bushes for New Mexico gardens. Its rich color contrasts beautifully with desert landscapes, and its long, fragrant flower spikes attract butterflies, hummingbirds, and bees all season. This fast-growing shrub benefits from occasional pruning to maintain shape and encourage fresh blooms, making it a bold yet low-maintenance addition to pollinator-friendly gardens and one of Jericho Nursery's best sellers.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30'",
    },
    {
        id: 1,
        name: "American Holly",
        scientificName: "Buddleia davidii 'Black Knight'",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/butterflybush.jpg",
        description: "With its deep purple, almost velvety blooms, Black Knight is one of the most striking butterfly bushes for New Mexico gardens. Its rich color contrasts beautifully with desert landscapes, and its long, fragrant flower spikes attract butterflies, hummingbirds, and bees all season. This fast-growing shrub benefits from occasional pruning to maintain shape and encourage fresh blooms, making it a bold yet low-maintenance addition to pollinator-friendly gardens and one of Jericho Nursery's best sellers.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30'",
    },
    {
        id: 1,
        name: "Japanese Holly",
        scientificName: "Buddleia davidii 'Black Knight'",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/butterflybush.jpg",
        description: "With its deep purple, almost velvety blooms, Black Knight is one of the most striking butterfly bushes for New Mexico gardens. Its rich color contrasts beautifully with desert landscapes, and its long, fragrant flower spikes attract butterflies, hummingbirds, and bees all season. This fast-growing shrub benefits from occasional pruning to maintain shape and encourage fresh blooms, making it a bold yet low-maintenance addition to pollinator-friendly gardens and one of Jericho Nursery's best sellers.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30'",
    },
    {
        id: 1,
        name: "Yaupon Holly",
        scientificName: "Buddleia davidii 'Black Knight'",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/butterflybush.jpg",
        description: "With its deep purple, almost velvety blooms, Black Knight is one of the most striking butterfly bushes for New Mexico gardens. Its rich color contrasts beautifully with desert landscapes, and its long, fragrant flower spikes attract butterflies, hummingbirds, and bees all season. This fast-growing shrub benefits from occasional pruning to maintain shape and encourage fresh blooms, making it a bold yet low-maintenance addition to pollinator-friendly gardens and one of Jericho Nursery's best sellers.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30'",
    },

    ],


}
export default coniferousshrubs;