const floweringshrubdata = {
    butterflybushes: [
      {
        id: 1,
        name: "Black Knight Butterfly Bush",
        scientificName: "Buddleia 'Black Knight'",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/butterflybush.jpg",
        description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30'",
      },
      {
        id: 2,
        name: "Pink Delight Butterfly Bush",
        scientificName: "Buddleia davidii 'Pink Delight'",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/butterflybush.jpg",
        description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30'",
      },
      {
        id: 3,
        name: "Hot Raspberry Butterfly Bush",
        scientificName: "Buddleia davidii 'Tobud1202' PPAF",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/butterflybush.jpg",
        description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30'",
      },
    
    ],
  
    indianhawthornes: [
        {
          id: 4,
          name: "Spring Sonata Indian Hawthorne",
          scientificName: "Rhaphiolepis indica 'Wilcor' PP17972",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/IndianHawthorne.png",
          description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 5,
          name: "Clean Sweep Snowbank Indian Hawthorne",
          scientificName: "Raphiolepis Hybrid ‘DB-01’ PP32786",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/IndianHawthorne.png",
          description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 6,
          name: "Snow White Indian Hawthorne",
          scientificName: "Rhaphiolepis indica 'Snow White' ",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/IndianHawthorne.png",
          description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
      
      ],
  
    potentillas: [
        {
          id: 7,
          name: "Goldfinger Potentilla",
          scientificName: "Potentilla fruticosa 'Goldfinger'",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/potentilla.jpg",
          description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 8,
          name: "McKays White Potentilla",
          scientificName: "Potentilla fruticosa 'McKay's White'",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/potentilla.jpg",
          description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 8,
          name: "Happy Face Pink Paradise Potentilla ",
          scientificName: "Potentilla fruticosa HAPPY FACE 'Kupinpa'",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/potentilla.jpg",
          description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
      
      ],
      sages: [
        {
          id: 1,
          name: "Mexican Blue Sage",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/SpanishBroom.png",
          description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Autumn Sage",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/SpanishBroom.png",
          description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Russian Sage",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/SpanishBroom.png",
          description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Compact Texas Sage",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/SpanishBroom.png",
          description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Lynn's Legacy Texas Sage",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/SpanishBroom.png",
          description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Rosemary",
          scientificName: "Salvia rosmarinus",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/SpanishBroom.png",
          description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
      
      ],
      
      lilacs: [
        {
          id: 1,
          name: "Miss Kim Lilac",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/lilac.jpg",
          description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Ludwig Spaeth Lilac",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/lilac.jpg",
          description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Sensation Lilac",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/lilac.jpg",
          description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Alba Lilac",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/lilac.jpg",
          description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Tinkerbell Bailbelle Lilac",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/lilac.jpg",
          description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
      
      
      ],
      
    
      crapemyrtles: [
        {
          id: 1,
          name: "Dynamite Crape Myrtle",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/crapemyrtle.jpg",
          description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Arapaho Crape Myrtle",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/crapemyrtle.jpg",
          description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Catawba Crape Myrtle",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/crapemyrtle.jpg",
          description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Pink Velour Crape Myrtle",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/crapemyrtle.jpg",
          description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Black Diamond Crape Myrtle",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/crapemyrtle.jpg",
          description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Red Rocket Crape Myrtle",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/crapemyrtle.jpg",
          description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
      
      ],
      
      roseofsharons: [
        {
          id: 1,
          name: "Diana Rose of Sharon",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/roseofsharon.jpg",
          description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Helene Rose of Sharon",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/roseofsharon.jpg",
          description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Aphrodite Rose of Sharon",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/roseofsharon.jpg",
          description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Red Heart Rose of Sharon",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/roseofsharon.jpg",
          description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Purple Pillar Rose of Sharon",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/roseofsharon.jpg",
          description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Minerva Rose of Sharon",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/roseofsharon.jpg",
          description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
      
      ],
      
      forsythias: [
        {
          id: 1,
          name: "Spring Glory Forsythia",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/forsythia.jpg",
          description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Medowlark Forsythia",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/forsythia.jpg",
          description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Magic Gold Forsythia",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/forsythia.jpg",
          description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Sunrise Forsythia",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/forsythia.jpg",
          description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
      
      ],
      mahogonies: [
        {
          id: 1,
          name: "Curl-leaf Mountain Mahogany",
          scientificName: "Cercocarpus ledifolius",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/lilac.jpg",
          description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Alderleaf Mountain Mahogany",
          scientificName: "Cercocarpus Montanus",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/lilac.jpg",
          description: "Sometimes known as Birchleaf or True Mountain Mahogany, you will foten see this drought tolerant shrub in the Western United States on rocky bluffs or mountainsides.",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Hairy Mountain Mahogany",
          scientificName: "CCercocarpus breviflorus",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/lilac.jpg",
          description: "Sometimes known as Birchleaf or True Mountain Mahogany, you will foten see this drought tolerant shrub in the Western United States on rocky bluffs or mountainsides.",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
      
      ],
      xerics:[
        {
          id: 1,
          name: "Western Sand Cherry",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/forsythia.jpg",
          description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Fern Bush",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/forsythia.jpg",
          description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Blue Rubber",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/forsythia.jpg",
          description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Rabbitbrush",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/forsythia.jpg",
          description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Apache Plume",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/forsythia.jpg",
          description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Brakelights Red Yucca",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/forsythia.jpg",
          description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
      ],

      others: [
        {
          id: 1,
          name: "Spanish Broom",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/forsythia.jpg",
          description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Arizona Rosewood",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/forsythia.jpg",
          description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Blue Mist Spirea",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/forsythia.jpg",
          description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Mexican Bird of Paradise",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/forsythia.jpg",
          description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Dwarf Fragrant Sumac",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/forsythia.jpg",
          description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
  
      ],
      
  
   
  
  
  };
  
  export default floweringshrubdata;
  