const floweringshrubdata = {
    butterflybushes: [
      {
        id: 1,
        name: "Black Knight Butterfly Bush",
        scientificName: "Buddleia davidii 'Black Knight'",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/butterflybush.jpg",
        description: "With its deep purple, almost velvety blooms, Black Knight is one of the most striking butterfly bushes for New Mexico gardens. Its rich color contrasts beautifully with desert landscapes, and its long, fragrant flower spikes attract butterflies, hummingbirds, and bees all season. This fast-growing shrub benefits from occasional pruning to maintain shape and encourage fresh blooms, making it a bold yet low-maintenance addition to pollinator-friendly gardens and one of Jericho Nursery's best sellers.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30'",
      },
      {
        id: 2,
        name: "Pink Delight Butterfly Bush",
        scientificName: "Buddleia davidii 'Pink Delight'",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/butterflybush.jpg",
        description: "Known for its large, bright pink flower clusters, Pink Delight brings vibrant color and a sweet fragrance to any garden. It thrives in dry conditions and blooms profusely from summer into fall, providing a long-lasting nectar source for pollinators. With its graceful, arching branches and silvery-green foliage, this variety adds soft texture and movement to landscapes while requiring minimal upkeep.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30'",
      },
      {
        id: 3,
        name: "Hot Raspberry Butterfly Bush",
        scientificName: "Buddleia davidii 'Tobud1202' PPAF",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/butterflybush.jpg",
        description: "A standout for its bold reddish-pink blooms, Hot Raspberry offers a unique color variation among butterfly bushes. Its compact, upright habit makes it ideal for smaller spaces or container plantings, while its flowers draw in butterflies and hummingbirds throughout the season. From Las Cruces to Albuqueruque, butterfly bushes are drought-tolerant and easy to care for, adding a touch of color to any lush green yard or low-water xeric garden.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30'",
      },
    
    ],
  
    indianhawthornes: [
        {
          id: 4,
          name: "Spring Sonata Indian Hawthorne",
          scientificName: "Rhaphiolepis indica 'Wilcor' PP17972",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/IndianHawthorne.png",
          description: "A reliable evergreen shrub, Indian Hawthorn is valued for its glossy green leaves and clusters of fragrant pink or white flowers in spring. Its compact growth habit makes it ideal for low hedges, foundation plantings, or accent shrubs. Drought-tolerant and resistant to pests, it requires little maintenance beyond occasional shaping, making it a great choice for New Mexico’s dry landscapes.",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 5,
          name: "Clean Sweep Snowbank Indian Hawthorne",
          scientificName: "Rhaphiolepis indica ‘DB-01’ PP32786",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/IndianHawthorne.png",
          description: "With its pure white blossoms and clean, mounded growth habit, Clean Sweep Snowbank is a standout choice for low-maintenance landscaping. This variety is bred for enhanced disease resistance, making it a worry-free option for gardeners. Its compact size and neat appearance work well in both formal and casual designs, offering year-round greenery with a burst of springtime color.",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 6,
          name: "Snow White Indian Hawthorne",
          scientificName: "Rhaphiolepis indica 'Snow White' ",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/IndianHawthorne.png",
          description: "A classic variety with abundant white blooms, Snow White Indian Hawthorn brings elegance to any garden. Its dark green foliage provides contrast for the bright flowers, which attract pollinators in spring. Naturally rounded and slow-growing, it requires little pruning, making it a perfect choice for foundation plantings, borders, or decorative containers in New Mexico’s climate.",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
      
      ],
  
    potentillas: [
        {
          id: 7,
          name: "Goldfinger Potentilla",
          scientificName: "Potentilla fruticosa 'Goldfinger'",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/potentilla.jpg",
          description: "Goldfinger Potentilla offers a stunning display of bright yellow flowers from spring to fall, making it a standout in New Mexico gardens and one of our favorites here at Jericho Nursery. This low-growing shrub has a compact, rounded shape and fine-textured, gray-green foliage that complements its vibrant blooms. Highly drought-tolerant once established and resistant to pests, it requires minimal maintenance beyond occasional pruning, making it an excellent choice for colorful borders or low-maintenance landscaping in arid climates.",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 8,
          name: "McKays White Potentilla",
          scientificName: "Potentilla fruticosa 'McKay's White'",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/potentilla.jpg",
          description: "With its vibrant pink flowers and tidy, rounded growth habit, Happy Face Pink Paradise brings year-round interest and color to New Mexico gardens. This compact shrub thrives in dry conditions and blooms profusely from spring to fall, attracting pollinators with its sweet fragrance. Ideal for low-maintenance landscapes, it requires little more than occasional trimming to maintain its neat appearance, making it a perfect addition to Southwestern gardens.",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 8,
          name: "Happy Face Pink Paradise Potentilla ",
          scientificName: "Potentilla fruticosa HAPPY FACE 'Kupinpa'",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/potentilla.jpg",
          description: "McKay’s White Potentilla stands out with its pure white blooms that create a striking contrast against its dark green foliage. This low-maintenance shrub is well-suited for dry landscapes, offering a long blooming season from spring through fall. It has a compact, rounded form that makes it perfect for borders, ground covers, or mass plantings, and it’s highly drought-tolerant and resistant to pests, ensuring lasting beauty with minimal care.",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
      
      ],
      sages: [
        {
          id: 1,
          name: "Mexican Blue Sage",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/SpanishBroom.png",
          description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Autumn Sage",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/SpanishBroom.png",
          description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Russian Sage",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/SpanishBroom.png",
          description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Compact Texas Sage",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/SpanishBroom.png",
          description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Lynn's Legacy Texas Sage",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/SpanishBroom.png",
          description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Rosemary",
          scientificName: "Salvia rosmarinus",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/SpanishBroom.png",
          description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
      
      ],
      
      lilacs: [
        {
          id: 1,
          name: "Miss Kim Lilac",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/lilac.jpg",
          description: "The Miss Kim Lilac is a compact, fragrant shrub that blooms profusely with lavender-blue flowers in late spring. Known for its cold hardiness and compact size, it fits well in smaller gardens or as an ornamental hedge. This variety has a strong resistance to pests and diseases, and its dense, rounded form offers seasonal beauty with minimal maintenance. Its lovely fragrance attracts pollinators, making it a perfect addition to any Southwestern garden.",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Ludwig Spaeth Lilac",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/lilac.jpg",
          description: "With deep purple blooms that stand out against dark green foliage, Ludwig Spaeth Lilac offers a bold pop of color in the spring. Its rich fragrance fills the air, attracting both pollinators and gardeners alike. This variety thrives in well-drained soil and requires little care once established, making it a great option for New Mexico gardeners seeking an easy-to-maintain shrub with striking seasonal appeal.",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Sensation Lilac",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/lilac.jpg",
          description: "The Sensation Lilac is a standout for its bi-color flowers, featuring rich purple petals with a contrasting white edge. This variety offers a unique twist on the classic lilac, with a strong, sweet fragrance that fills the garden in spring. Thriving in full sun, Sensation is a hardy and low-maintenance shrub that requires minimal pruning, making it a perfect choice for adding color and fragrance to New Mexico landscapes with ease.",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Alba Lilac",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/lilac.jpg",
          description: "Alba Lilac is known for its classic white flowers that fill the air with a sweet, nostalgic fragrance every spring. This variety offers a striking contrast against its dark green foliage and grows in a compact, upright form. Hardy and easy to grow, Alba is well-suited to New Mexico’s climate and requires minimal care, making it a perfect choice for gardeners looking to add a touch of elegance and fragrance to their landscape.",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Tinkerbell Bailbelle Lilac",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/lilac.jpg",
          description: "A unique and compact variety, the Tinkerbell Bailbelle Lilac features lavender-pink flowers that bloom in early to mid-spring. Its smaller size makes it ideal for smaller gardens or as a focal point in borders. The flowers are intensely fragrant, attracting pollinators and adding seasonal beauty with minimal maintenance. Tinkerbell thrives in well-drained soil and full sun, making it a wonderful addition to New Mexico’s gardens for those seeking both color and fragrance in a manageable shrub.",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
      
      
      ],
      
    
      crapemyrtles: [
        {
          id: 1,
          name: "Dynamite Crape Myrtle",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/crapemyrtle.jpg",
          description: "The Dynamite Crape Myrtle is a standout for its vibrant red blooms, which create a bold splash of color throughout the summer. Known for its drought tolerance and heat resistance, this variety thrives in New Mexico’s dry climate with minimal care. Its smooth bark and glossy green leaves provide year-round interest, while its dense, upright growth habit makes it perfect for specimen planting or as a colorful hedge.",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Arapaho Crape Myrtle",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/crapemyrtle.jpg",
          description: "With its rich pink flowers and compact size, the Arapaho Crape Myrtle is a perfect choice for smaller landscapes or container plantings. This variety blooms heavily in summer, attracting butterflies and hummingbirds, and has a strong resistance to powdery mildew, making it a low-maintenance option. Its glossy, dark green foliage transitions beautifully in the fall, and its smooth, exfoliating bark adds visual interest year-round.",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Catawba Crape Myrtle",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/crapemyrtle.jpg",
          description: "The Catawba Crape Myrtle features vivid purple blooms that provide striking color in the summer months. Its uniform, rounded shape makes it an excellent addition to formal gardens or mixed shrub borders. This variety is heat-tolerant, drought-tolerant, and resistant to mildew, ensuring a vibrant display with minimal maintenance. Catawba’s smooth, attractive bark and rich fall foliage offer visual appeal throughout the year.",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Pink Velour Crape Myrtle",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/crapemyrtle.jpg",
          description: "With its deep pink flowers and striking dark foliage, Pink Velour Crape Myrtle offers a unique twist on traditional crape myrtles. This variety thrives in the heat, providing long-lasting blooms from summer through fall. Its contrasting foliage and smooth bark make it a standout in the landscape, perfect for adding both color and texture. Pink Velour is also known for its resistance to mildew and minimal maintenance needs, making it an excellent choice for low-care gardens.",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Black Diamond Crape Myrtle",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/crapemyrtle.jpg",
          description: "Black Diamond Crape Myrtle stands out with its dark purple to black foliage, creating a striking contrast with its vivid pink, red, or purple blooms. Known for its ability to thrive in hot, dry conditions, it blooms profusely throughout the summer and into fall, attracting pollinators. Its compact, rounded form makes it perfect for smaller gardens or as a specimen plant. The combination of dark foliage, colorful flowers, and exfoliating bark makes Black Diamond a unique and eye-catching addition to New Mexico landscapes.",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Red Rocket Crape Myrtle",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/crapemyrtle.jpg",
          description: "The Red Rocket Crape Myrtle is a standout for its bright red flowers that bloom profusely from summer to fall, providing a bold pop of color in the landscape. Known for its fast-growing nature and disease resistance, this variety thrives in hot, dry climates like New Mexico, requiring minimal care once established. Its smooth bark and attractive green foliage add year-round interest, while its compact, upright growth habit makes it an excellent choice for hedges, borders, or specimen plantings.",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
      
      ],
      
      roseofsharons: [
        {
          id: 1,
          name: "Diana Rose of Sharon",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/roseofsharon.jpg",
          description: "Diana Rose of Sharon is a stunning variety with pure white flowers that feature a deep purple center, providing a striking contrast. This shrub blooms generously from late summer through fall, making it a long-lasting addition to gardens. Its upright, multi-stemmed form is ideal for adding structure and color to landscapes, and it’s well-suited for New Mexico’s dry conditions, offering low-maintenance beauty with minimal water needs.",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Helene Rose of Sharon",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/roseofsharon.jpg",
          description: "With beautiful double blooms in shades of lavender and pink, Helene Rose of Sharon brings a touch of elegance to the garden. This variety blooms profusely throughout the summer, attracting pollinators with its sweet scent. Its tall, upright form makes it an excellent choice for adding vertical interest to borders or as a specimen plant. Helene is drought-tolerant and easy to maintain, perfect for New Mexico’s climate.",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Aphrodite Rose of Sharon",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/roseofsharon.jpg",
          description: "Aphrodite Rose of Sharon features large, pink blooms with a darker red center, offering a bold pop of color from late summer to fall. Known for its disease resistance and compact, rounded form, this variety is ideal for smaller gardens or as an accent shrub. Aphrodite thrives in hot, dry climates and requires minimal care, making it a perfect choice for New Mexico gardeners looking for vibrant, low-maintenance blooms.",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Red Heart Rose of Sharon",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/roseofsharon.jpg",
          description: "Red Heart Rose of Sharon is known for its large, striking white flowers with a deep red center, creating a dramatic contrast. Its upright, dense habit makes it perfect for adding height and structure to gardens, while the flowers provide a late-summer burst of color. Red Heart is low-maintenance, drought-tolerant, and attracts butterflies, making it a great choice for pollinator-friendly landscaping in New Mexico.",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Purple Pillar Rose of Sharon",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/roseofsharon.jpg",
          description: "The Purple Pillar Rose of Sharon is a unique, columnar variety that grows upright, with striking purple flowers that bloom in late summer. Perfect for narrow spaces, this variety adds vertical interest and seasonal color to gardens. It’s a hardy shrub, well-suited for New Mexico’s dry conditions, and attracts pollinators with its showy blooms. Purple Pillar is low-maintenance, requiring little pruning and providing beauty with minimal effort.",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Minerva Rose of Sharon",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/roseofsharon.jpg",
          description: "Minerva Rose of Sharon features large, vibrant lavender-pink flowers with a deep red center that bloom from late summer into fall. This hardy shrub offers a stunning display of color, attracting pollinators with its sweet nectar. Its upright, multi-stemmed growth makes it perfect for hedges, screens, or as a focal point in gardens. Once established, it is drought-tolerant and low-maintenance, thriving in New Mexico’s dry climate with minimal care.",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
      
      ],
      
      forsythias: [
        {
          id: 1,
          name: "Spring Glory Forsythia",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/forsythia.jpg",
          description: "Spring Glory Forsythia is one of the earliest bloomers in the garden, featuring bright yellow flowers that burst forth in early spring, often before the leaves appear. This fast-growing shrub offers vibrant color and fills the garden with cheer after a long winter. It thrives in full sun and well-drained soil, providing a stunning early-season display with minimal maintenance. Its dense, upright growth habit makes it ideal for hedges or as a backdrop for spring flowering plants.",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Medowlark Forsythia",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/forsythia.jpg",
          description: "Meadowlark Forsythia is known for its abundant yellow blooms that light up the garden in early spring, offering an eye-catching display of color. This variety is a bit more compact than others, making it a great choice for smaller gardens or as a low-maintenance hedge. It adapts well to various soil types and can tolerate New Mexico’s varying climate, providing early-season beauty with minimal water needs.",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Magic Gold Forsythia",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/forsythia.jpg",
          description: "Magic Gold Forsythia offers a profusion of bright yellow flowers that appear in early spring, signaling the end of winter and the start of the growing season. Known for its strong, upright growth habit, this variety reaches a manageable size, making it perfect for hedges, borders, or accent plantings. Magic Gold is drought-tolerant once established and thrives in full sun, making it an excellent choice for New Mexico gardeners looking for vibrant, low-maintenance blooms.",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Sunrise Forsythia",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/forsythia.jpg",
          description: "Sunrise Forsythia is a striking variety that delivers a bright yellow floral display in early spring, followed by rich green foliage throughout the growing season. Its dense, upright habit makes it an excellent choice for creating hedges or as a specimen plant. Sunrise Forsythia is easy to grow, tolerates a variety of soil types, and requires little maintenance once established, making it ideal for New Mexico gardens that benefit from early-season color and minimal care.",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
      
      ],
      mahogonies: [
        {
          id: 1,
          name: "Curl-leaf Mountain Mahogany",
          scientificName: "Cercocarpus ledifolius",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/lilac.jpg",
          description: "The Curl-leaf Mountain Mahogany is a hardy, evergreen shrub that thrives in New Mexico’s arid conditions. Known for its distinctive twisting, leathery leaves and silvery-gray foliage, it provides year-round interest, especially during the winter months. This drought-tolerant shrub offers beautiful, fluffy seed tails that add texture to the landscape. Ideal for low-maintenance, xeriscape gardens, it works well in rocky, well-drained soils and full sun, making it perfect for those seeking a rugged yet attractive plant for dry landscapes.",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Alderleaf Mountain Mahogany",
          scientificName: "Cercocarpus Montanus",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/lilac.jpg",
          description: "Alderleaf Mountain Mahogany is a deciduous shrub that adds texture and structure to New Mexico gardens with its oval, dark green leaves and silky, feathery seed heads. This variety thrives in well-drained soils and full sun, offering both wildlife value and low-maintenance beauty. Its dense, upright form provides great wind protection and erosion control, making it a great choice for slopes or challenging landscapes. Alderleaf is highly drought-tolerant once established, making it well-suited to the dry, high-desert environment.",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Hairy Mountain Mahogany",
          scientificName: "CCercocarpus breviflorus",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/lilac.jpg",
          description: "Hair Mountain Mahogany is a small, evergreen shrub that thrives in harsh, dry conditions. Known for its smooth, dark green leaves and hair-like seed tails that add elegance to the plant, it can grow as a shrub or small tree. This variety is perfect for xeriscape landscapes in New Mexico, requiring little water once established. Its hardy nature makes it ideal for slopes, dry hillsides, and rocky terrain. Hair Mountain Mahogany is also valued for its windbreak potential and wildlife habitat benefits.",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
      
      ],
      xerics:[
        {
          id: 1,
          name: "Western Sand Cherry",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/forsythia.jpg",
          description: "The Western Sand Cherry is a hardy, compact shrub that thrives in the dry, rocky soils of New Mexico. Known for its white spring blossoms, it produces dark purple to black edible cherries that attract birds and wildlife. Its glossy, dark green foliage transitions to vibrant autumn colors, adding seasonal interest. This shrub is drought-tolerant once established and does well in full sun and well-drained soil, making it an excellent choice for xeriscape gardens or as a low-maintenance shrub in the landscape.",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Fern Bush",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/forsythia.jpg",
          description: "Fern Bush is a native New Mexico shrub valued for its feathery, fern-like foliage and delicate, creamy-white flowers that bloom in late spring to early summer. Known for its ability to thrive in arid conditions, this shrub is highly drought-tolerant once established and grows best in well-drained soils with full sun. It’s perfect for xeriscaping, offering a graceful texture and providing wildlife habitat with its fragrant flowers that attract pollinators. With minimal maintenance, Fern Bush adds a soft, airy element to dry, desert landscapes.",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Blue Rubber",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/forsythia.jpg",
          description: "Blue Rubber is a striking, low-maintenance cactus native to the Southwestern United States, known for its vibrant blue-gray skin and bright pink to purple flowers that bloom in late spring. This hardy plant thrives in full sun and well-drained, rocky soils, making it an excellent choice for xeriscape gardens in New Mexico’s arid climate. Its distinctive appearance and colorful blooms add a bold, sculptural element to dry landscapes. Blue Rubber is drought-tolerant and requires very little care, making it ideal for those seeking an attractive, water-wise plant for desert gardens.",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Rabbitbrush",
          scientificName: "Chrysothamnus nauseosus",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/forsythia.jpg",
          description: "Rabbit Brush is a native shrub that flourishes in New Mexico’s dry, rocky soils. Known for its bright yellow flowers that bloom in late summer to fall, it provides a cheerful burst of color when many other plants are past their prime. This drought-tolerant shrub thrives in full sun and well-drained soils, making it ideal for xeriscaping or low-maintenance gardens. Rabbit Brush attracts pollinators and offers a natural, wild look to desert landscapes, with its silvery-green foliage adding texture and contrast. Its resilience to harsh conditions makes it a perfect fit for arid environments.",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Apache Plume",
          scientificName: "Fallugia paradoxa",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/forsythia.jpg",
          description: "Apache Plume is a striking shrub native to the Southwestern United States, valued for its elegant, feathery plumes that appear in late spring and early summer. These plumes are followed by small white flowers that provide a delicate contrast to its gray-green, aromatic foliage. Well-suited for New Mexico’s dry, rocky landscapes, Apache Plume thrives in full sun and well-drained soils, making it an excellent choice for xeriscape gardens. This drought-tolerant shrub attracts pollinators and offers year-round interest with its unique form and beautiful seed heads, which persist into the winter.",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Brakelights Red Yucca",
          scientificName: "Hesperaloe parviflora 'Brakelight'",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/forsythia.jpg",
          description: "Brakelight Red Yucca is a striking, drought-tolerant succulent that thrives in New Mexico’s dry climate. Known for its vibrant red tubular flowers that bloom on tall spikes during the summer, it adds a bold pop of color to xeriscape gardens. The plant’s narrow, spiky foliage forms a clumping rosette, offering an architectural element to landscapes. Brakelight Red Yucca thrives in full sun and well-drained soils, requiring minimal water once established. Its low-maintenance nature and ability to attract hummingbirds make it an excellent choice for low-water gardens or desert landscapes.",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
      ],

      others: [
        {
          id: 1,
          name: "Spanish Broom",
          scientificName: "Spartium junceum",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/forsythia.jpg",
          description: "Spanish Broom is a sun-loving shrub that brings a touch of Mediterranean charm to New Mexico gardens with its bright yellow, pea-like flowers that bloom in late spring to early summer. Known for its long, slender stems and fine, narrow foliage, it adds a graceful, airy appearance to any landscape. Thriving in full sun and well-drained soils, Spanish Broom is drought-tolerant once established and ideal for xeriscape gardening. Its vibrant blooms attract pollinators, and its low-maintenance nature makes it an excellent choice for gardeners seeking a colorful, water-wise shrub.",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Arizona Rosewood",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/forsythia.jpg",
          description: "Arizona Rosewood is an evergreen shrub or small tree that thrives in New Mexico’s dry, rocky landscapes. Known for its dark green, leathery leaves and small, white to cream-colored flowers that bloom in late spring, this hardy plant adds a touch of elegance to xeriscape gardens. The plant's dense foliage provides great privacy or windbreaks, while its smooth, reddish-brown bark offers visual interest throughout the year. Arizona Rosewood thrives in full sun and well-drained soils, requiring minimal water once established, making it an excellent choice for low-maintenance, water-efficient gardens.",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
        {
          id: 1,
          name: "Blue Mist Spirea",
          scientificName: "Pinus edulis",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/forsythia.jpg",
          description: "Blue Mist Spirea is a compact, deciduous shrub known for its striking blue to lavender flowers that bloom in late summer to fall, providing a vibrant contrast to its aromatic, silvery-green foliage. This drought-tolerant shrub thrives in full sun and well-drained soils, making it ideal for New Mexico’s arid climate. The plant’s fragrant flowers attract pollinators, while its tidy, mounding shape adds a soft, bushy texture to garden landscapes. Blue Mist Spirea requires little maintenance once established and is an excellent choice for adding late-season color and wildlife appeal to xeriscape gardens.",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        }, 
        {
        id: 1,
        name: "Mexican Bird of Paradise",
        scientificName: "Caesalpinia mexicana",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/flowering/bird-of-paradise-bush-3494940_1920.jpg",
        description: "The Mexican Bird of Paradise is an exotic, drought-tolerant plant known for its striking, bird-like flowers in shades of orange and yellow. It thrives in New Mexico’s sunny, dry climate and adds a dramatic flair to gardens with its upright, lush foliage. While it prefers full sun, it’s adaptable to other growing conditions if needed. Jericho recommends using this plant as a xeric tree or shrub to enhance the color in your xeriscaped sections of yard or garden.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/rainwater.png",
        waterRequirement: "Xeric",
        hardinessZones: "7-10",
        matureSize: "10' x 10'",
        native: true
        },
        {
          id: 1,
          name: "Dwarf Fragrant Sumac",
          scientificName: "Rhus aromatica 'Gro-Low'",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Shrubs/flowering/forsythia.jpg",
          description: "Dwarf Fragrant Sumac is a low-growing, deciduous shrub that thrives in New Mexico’s dry, sunny landscapes. Known for its fragrant, lemon-scented foliage and bright red to orange berries that attract birds, this compact shrub is perfect for ground cover or low hedges. Its dark green leaves turn vibrant shades of red, orange, and yellow in the fall, adding seasonal interest. Dwarf Fragrant Sumac is drought-tolerant and thrives in full sun and well-drained soils, making it an excellent choice for xeriscaping or low-maintenance gardens. Its resilience and attractive foliage provide year-round beauty with minimal care.",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
          waterRequirement: "Low Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "15' x 30'",
        },
  
      ],
      
  
   
  
  
  };
  
  export default floweringshrubdata;
  