const ornamentaldata = {
    pears: [
      {
        id: 1,
        name: "Bradford Pear",
        scientificName: "Pinus edulis",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Pinon.jpg",
        description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30'",
      },
      {
        id: 2,
        name: "Chanticlear Pear",
        scientificName: "Pinus edulis",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Pinon.jpg",
        description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30'",
      },
      {
        id: 2,
        name: "Cleavand Select Pear",
        scientificName: "Pinus edulis",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Pinon.jpg",
        description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30'",
      },
      {
        id: 2,
        name: "Callery Pear",
        scientificName: "Pinus edulis",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Pinon.jpg",
        description: "A hardy conifer native to the Southwest, known for its edible pine nuts...",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/LowestWater.png",
        waterRequirement: "Low Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "15' x 30'",
      },
   
    ],
  
    cherries: [
      {
        id: 4,
        name: "Kwanzan Cherry",
        scientificName: "Juniperus scopulorum",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
        description: "A drought-tolerant conifer with dense foliage and berries...",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "10' x 20'",
      },
      {
        id: 4,
        name: "Autumn Flowering Cherry",
        scientificName: "Juniperus scopulorum",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
        description: "A drought-tolerant conifer with dense foliage and berries...",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "10' x 20'",
      },
      {
        id: 4,
        name: "Okame Cherry",
        scientificName: "Juniperus scopulorum",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
        description: "A drought-tolerant conifer with dense foliage and berries...",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "10' x 20'",
      },
      {
        id: 4,
        name: "Chokecherry",
        scientificName: "Juniperus scopulorum",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
        description: "A drought-tolerant conifer with dense foliage and berries...",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "10' x 20'",
      },
    ],
  
    plums: [
      {
        id: 4,
        name: "Thundercloud Plum",
        scientificName: "Thundercloud Plum",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
        description: "A drought-tolerant conifer with dense foliage and berries...",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "10' x 20'",
      },
      {
        id: 4,
        name: "American Plum",
        scientificName: "Thundercloud Plum",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
        description: "A drought-tolerant conifer with dense foliage and berries...",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "10' x 20'",
      },
      {
        id: 4,
        name: "Newport Plum",
        scientificName: "Thundercloud Plum",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
        description: "A drought-tolerant conifer with dense foliage and berries...",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "10' x 20'",
      },
      {
        id: 4,
        name: "Purple Leaf Plum",
        scientificName: "Thundercloud Plum",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
        description: "Often considered fruitless but can provide small inconsequential fruit.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "10' x 20'",
      },
      
    ],
    crabapples: [
        {
          id: 4,
          name: "Prarie Fire Crabapple",
          scientificName: "Juniperus scopulorum",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
          description: "A drought-tolerant conifer with dense foliage and berries...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
          waterRequirement: "Moderate Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "10' x 20'",
        },
        {
            id: 4,
            name: "Sugar Tyme",
            scientificName: "Juniperus scopulorum",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
          {
            id: 4,
            name: "Centurion Crabapple",
            scientificName: "Juniperus scopulorum",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
      ],
    redbuds: [
        {
          id: 4,
          name: "Oaklahoma Redbud",
          scientificName: "Juniperus scopulorum",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
          description: "A drought-tolerant conifer with dense foliage and berries...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
          waterRequirement: "Moderate Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "10' x 20'",
        },
        {
            id: 4,
            name: "Mexican Redbud",
            scientificName: "Juniperus scopulorum",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
          {
            id: 4,
            name: "Eastern Redbud",
            scientificName: "Juniperus scopulorum",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
          {
            id: 4,
            name: "Western/Texas Redbud",
            scientificName: "Juniperus scopulorum",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
      ],
      flowering: [
        {
          id: 4,
          name: "Red Cedar",
          scientificName: "Juniperus scopulorum",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
          description: "A drought-tolerant conifer with dense foliage and berries...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
          waterRequirement: "Moderate Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "10' x 20'",
        },
      ],
      shrublike: [
        {
          id: 4,
          name: "Red Cedar",
          scientificName: "Juniperus scopulorum",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
          description: "A drought-tolerant conifer with dense foliage and berries...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
          waterRequirement: "Moderate Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "10' x 20'",
        },
      ],
  
  
  };
  
  export default ornamentaldata;
  