const shadedata = {
    ash: [
      {
        id: 1,
        name: "Arizona Ash",
        scientificName: "Fraxinus velutina",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Pinon.jpg",
        description: "The Arizona Ash is a fast-growing deciduous tree native to the southwestern United States and parts of Mexico. It typically reaches heights of 40 to 50 feet with a canopy spread of 30 to 40 feet. The tree features a rounded canopy with deep green leaves that turn bright golden-yellow in the fall.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: [7, 8, 9, 10],
        matureSize: "45' x 35'",
        native: true
      },
      {
        id: 2,
        name: "Raywood Ashe",
        scientificName: "Fraxinus oxycarpa",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Pinon.jpg",
        description: "The Raywood Ash is a beautiful deciduous tree known for its rich red-purple foliage in the fall. It grows rapidly and is often used for shade in residential and urban areas. This tree can reach impressive heights and provides a dense canopy, offering excellent shade in the warmer months. Its leaves turn golden-yellow before dropping in the fall, making it an attractive tree throughout the seasons.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: [5, 6, 7, 8, 9],
        matureSize: "45' x 35'",
        native: false
      },
      {
        id: 3,
        name: "Urbanite Ash",
        scientificName: "Fraxinus americana",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Pinon.jpg",
        description: "The Urbanite Ash is a fast-growing deciduous tree that is highly valued for its uniform shape and strong, upright growth. It has deep green foliage that transitions to bright yellow in the fall, offering vibrant autumn color. This tree is particularly suited for urban environments due to its tolerance to pollution and compact soil. It's an excellent choice for street plantings and urban parks, where space is limited but shade is needed.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: [4, 5, 6, 7, 8, 9],
        matureSize: "45' x 35'",
        native: false
      },
      {
        id: 4,
        name: "Patmore Ash",
        scientificName: "Fraxinus pennsylvanica",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Pinon.jpg",
        description: "The Patmore Ash is a fast-growing tree known for its striking green foliage that turns vibrant yellow in the fall. This variety of Green Ash is particularly well-suited for colder climates and is often planted in urban and suburban areas for its resilience and excellent shade. It has a strong, upright structure and a broad canopy, making it ideal for providing shade and as a windbreak.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: [3,4, 5, 6, 7, 8, 9],
        matureSize: "45' x 35'",
        native: false
      },
      {
        id: 5,
        name: "Green Ash",
        scientificName: "Fraxinus pennsylvanica",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Pinon.jpg",
        description: " The Green Ash is a hardy deciduous tree native to North America. It is known for its rapid growth and adaptability to a wide range of soil conditions. The tree has a broad canopy with rich green leaves that turn yellow in the fall, providing beautiful seasonal color. Green Ash is often used for shade and can grow well in both urban and rural settings, making it a popular choice for landscaping. A Patmore Ash is a rounded seedless variety of the Green Ash.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: [3,4, 5, 6, 7, 8, 9],
        matureSize: "45' x 35'",
        native: false
      },
    
    ],
  
    cottonwood: [
        {
            id: 6,
            name: "Rio Grande Cottonwood",
            scientificName: "Populus deltoides",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
            description: " The Rio Grande Cottonwood is a large deciduous tree native to the southwestern U.S. It is commonly found along rivers and wetlands and is known for its broad, heart-shaped leaves that turn bright yellow in the fall. This tree grows quickly and provides extensive shade with its large canopy. The Rio Grande Cottonwood is well-suited for areas with ample water, making it ideal for riparian zones or floodplains.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/HighWater.png",
            waterRequirement: "High Water",
            hardinessZones: [5, 6, 7, 8, 9],
            matureSize: "50' x 40'",
            native: true
          },
      {
        id: 7,
        name: "Mountain Cottonwood",
        scientificName: "Populus angustifolia",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
        description: "The Mountain Cottonwood is a large, deciduous tree native to the western U.S., often found along riverbanks and in moist, mountainous regions. It has a broad, spreading canopy with triangular leaves that turn golden-yellow in the fall. This tree grows quickly and is known for its resilience in various soil types, though it prefers moist conditions. It provides excellent shade, making it a popular choice for larger landscapes and natural areas.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "10' x 20'",
      },
      {
        id: 8,
        name: "Fremont Cottonwood",
        scientificName: "Juniperus scopulorum",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
        description: "A drought-tolerant conifer with dense foliage and berries...",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "10' x 20'",
      },
      {
        id: 9,
        name: "Black Cottonwood",
        scientificName: "Juniperus scopulorum",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
        description: "A drought-tolerant conifer with dense foliage and berries...",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "10' x 20'",
      },
    ],
  
    elm: [
      {
        id: 10,
        name: "American Elm",
        scientificName: "Juniperus scopulorum",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
        description: "A drought-tolerant conifer with dense foliage and berries...",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "10' x 20'",
      },
      {
        id: 11,
        name: "Lacebark Elm",
        scientificName: "Juniperus scopulorum",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
        description: "A drought-tolerant conifer with dense foliage and berries...",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "10' x 20'",
      },
      {
        id: 12,
        name: "Cedar Elm",
        scientificName: "Juniperus scopulorum",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
        description: "A drought-tolerant conifer with dense foliage and berries...",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
        waterRequirement: "Moderate Water",
        hardinessZones: [4, 5, 6, 7],
        matureSize: "10' x 20'",
      },
    ],

    willow: [
        {
            id: 13,
            name: "Globe Willow",
            scientificName: "Juniperus scopulorum",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
        {
            id: 14,
            name: "Weeping Willow",
            scientificName: "Juniperus scopulorum",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
        {
            id: 15,
            name: "White Willow",
            scientificName: "Juniperus scopulorum",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
      ],

      maple: [
        {
            id: 16,
            name: "Boxelder Maple",
            scientificName: "Juniperus scopulorum",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
        {
            id: 17,
            name: "Bigtooth Maple",
            scientificName: "Juniperus scopulorum",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
        {
            id: 18,
            name: "Big Leaf Maple",
            scientificName: "Juniperus scopulorum",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
        {
            id: 19,
            name: "Japanese Maple",
            scientificName: "Juniperus scopulorum",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
          {
            id: 21,
            name: "Tatarian Maple",
            scientificName: "Juniperus scopulorum",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
      ],

      sycamore: [
        {
          id: 22,
          name: "Arizona Sycamore",
          scientificName: "Juniperus scopulorum",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
          description: "A drought-tolerant conifer with dense foliage and berries...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
          waterRequirement: "Moderate Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "10' x 20'",
        },
        {
          id: 23,
          name: "Mexican Sycamore",
          scientificName: "Juniperus scopulorum",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
          description: "A drought-tolerant conifer with dense foliage and berries...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
          waterRequirement: "Moderate Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "10' x 20'",
        },
        {
          id: 24,
          name: "American Sycamore",
          scientificName: "Juniperus scopulorum",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
          description: "A drought-tolerant conifer with dense foliage and berries...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
          waterRequirement: "Moderate Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "10' x 20'",
        },
      ],

      oak: [
        {
            id: 25,
            name: "Bur Oak",
            scientificName: "Juniperus scopulorum",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
          {
            id: 26,
            name: "Chinqapin Oak",
            scientificName: "Juniperus scopulorum",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
          {
            id: 26,
            name: "Gambel Oak",
            scientificName: "Juniperus scopulorum",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
      ],

      honeylocust: [
        {
            id: 27,
            name: "Sunburst Honey Locust",
            scientificName: "Juniperus scopulorum",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
          {
            id: 28,
            name: "Skyline Honey Locust",
            scientificName: "Juniperus scopulorum",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
          {
            id: 29,
            name: "Shademaster Honey Locust",
            scientificName: "Juniperus scopulorum",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
      ],

      other: [
        {
          id: 30,
          name: "Chaste Tree (Vitex)",
          scientificName: "Juniperus scopulorum",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
          description: "A drought-tolerant conifer with dense foliage and berries...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
          waterRequirement: "Moderate Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "10' x 20'",
        },
        {
            id: 31,
            name: "Western Hackberry",
            scientificName: "Juniperus scopulorum",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
        {
            id: 32,
            name: "Smoketree",
            scientificName: "Juniperus scopulorum",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
        {
            id: 33,
            name: "Chinese Pistache",
            scientificName: "Juniperus scopulorum",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
        {
            id: 34,
            name: "Golden Rain Tree",
            scientificName: "Juniperus scopulorum",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
        {
            id: 35,
            name: "Washinton Hawthorne",
            scientificName: "Juniperus scopulorum",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
        {
            id: 36,
            name: "Catalpa",
            scientificName: "Juniperus scopulorum",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
          {
            id: 37,
            name: "Chitalpa",
            scientificName: "Juniperus scopulorum",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
      ],

      unique: [
        {
          id: 38,
          name: "Japanese Pagoda",
          scientificName: "Juniperus scopulorum",
          image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
          description: "A drought-tolerant conifer with dense foliage and berries...",
          sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
          sunRequirement: "Full Sun",
          waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
          waterRequirement: "Moderate Water",
          hardinessZones: [4, 5, 6, 7],
          matureSize: "10' x 20'",
        },
        {
            id: 39,
            name: "Qauking Aspen",
            scientificName: "Juniperus scopulorum",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
          {
            id: 40,
            name: "Orange Sage",
            scientificName: "Juniperus scopulorum",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
          {
            id: 41,
            name: "Kentucky CoffeTree",
            scientificName: "Juniperus scopulorum",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
          {
            id: 42,
            name: "Velvet Mesquite",
            scientificName: "Juniperus scopulorum",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Trees/conifer/Juniper.jpg",
            description: "A drought-tolerant conifer with dense foliage and berries...",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/medHiWater.png",
            waterRequirement: "Moderate Water",
            hardinessZones: [4, 5, 6, 7],
            matureSize: "10' x 20'",
          },
      ],
  
  
  };
  
  export default shadedata;
  